// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package ttdworkflows

// Generated from OpenAPI doc version v1 and generator version 2.673.2

import (
	"context"
	"fmt"
	"github.com/thetradedesk/ttd-workflows-go/internal/config"
	"github.com/thetradedesk/ttd-workflows-go/internal/hooks"
	"github.com/thetradedesk/ttd-workflows-go/internal/utils"
	"github.com/thetradedesk/ttd-workflows-go/models/components"
	"github.com/thetradedesk/ttd-workflows-go/retry"
	"net/http"
	"time"
)

const (
	// The production environment.
	ServerProd string = "prod"
	// The sandbox environment for testing.
	ServerSandbox string = "sandbox"
)

// ServerList contains the list of servers available to the SDK
var ServerList = map[string]string{
	ServerProd:    "https://api.thetradedesk.com/workflows",
	ServerSandbox: "https://ext-api.sb.thetradedesk.com/workflows",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// Workflows Service:
// This service provides operations for commonly used workflows on The Trade Desk's platform.
// In addition, this service provides generic operations for submitting:
//
// - GraphQL API requests
// - REST API requests
//
// For further explanation on the entities encountered in this documentation (e.g.,
// [campaigns](https://partner.thetradedesk.com/v3/portal/api/doc/Campaigns) and
// [ad groups](https://partner.thetradedesk.com/v3/portal/api/doc/AdGroup)), visit the
// [Partner Portal](https://partner.thetradedesk.com/v3/portal/api/doc/ApiUseCases).
type Workflows struct {
	SDKVersion      string
	AdGroups        *AdGroups
	Campaigns       *Campaigns
	Dmps            *Dmps
	GraphQlRequests *GraphQlRequests
	Jobs            *Jobs
	RestRequests    *RestRequests
	JobStatus       *JobStatus

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*Workflows)

// WithServerURL allows the overriding of the default server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *Workflows) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *Workflows) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServer allows the overriding of the default server by name
func WithServer(server string) SDKOption {
	return func(sdk *Workflows) {
		_, ok := ServerList[server]
		if !ok {
			panic(fmt.Errorf("server %s not found", server))
		}

		sdk.sdkConfiguration.Server = server
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *Workflows) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(ttdAuth string) SDKOption {
	return func(sdk *Workflows) {
		security := components.Security{TTDAuth: &ttdAuth}
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(&security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (components.Security, error)) SDKOption {
	return func(sdk *Workflows) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *Workflows) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *Workflows) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *Workflows {
	sdk := &Workflows{
		SDKVersion: "0.10.0",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:  "speakeasy-sdk/go 0.10.0 2.673.2 v1 github.com/thetradedesk/ttd-workflows-go",
			ServerList: ServerList,
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	if sdk.sdkConfiguration.Security == nil {
		var envVarSecurity components.Security
		if utils.PopulateSecurityFromEnv(&envVarSecurity) {
			sdk.sdkConfiguration.Security = utils.AsSecuritySource(envVarSecurity)
		}
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.AdGroups = newAdGroups(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Campaigns = newCampaigns(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Dmps = newDmps(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.GraphQlRequests = newGraphQlRequests(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Jobs = newJobs(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.RestRequests = newRestRequests(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.JobStatus = newJobStatus(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
