// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/internal/utils"
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type ArchiveAdGroupsRequest struct {
	ForceArchive *bool    `default:"false" queryParam:"style=form,explode=true,name=forceArchive"`
	RequestBody  []string `request:"mediaType=application/json"`
}

func (a ArchiveAdGroupsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ArchiveAdGroupsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ArchiveAdGroupsRequest) GetForceArchive() *bool {
	if a == nil {
		return nil
	}
	return a.ForceArchive
}

func (a *ArchiveAdGroupsRequest) GetRequestBody() []string {
	if a == nil {
		return nil
	}
	return a.RequestBody
}

type ArchiveAdGroupsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Strings []string
}

func (a *ArchiveAdGroupsResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *ArchiveAdGroupsResponse) GetStrings() []string {
	if a == nil {
		return nil
	}
	return a.Strings
}
