// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"ttd-workflows/internal/utils"
	"ttd-workflows/models/components"
)

type ArchiveCampaignsRequest struct {
	ForceArchive *bool    `default:"false" queryParam:"style=form,explode=true,name=forceArchive"`
	RequestBody  []string `request:"mediaType=application/json"`
}

func (a ArchiveCampaignsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ArchiveCampaignsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ArchiveCampaignsRequest) GetForceArchive() *bool {
	if o == nil {
		return nil
	}
	return o.ForceArchive
}

func (o *ArchiveCampaignsRequest) GetRequestBody() []string {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type ArchiveCampaignsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Strings []string
}

func (o *ArchiveCampaignsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ArchiveCampaignsResponse) GetStrings() []string {
	if o == nil {
		return nil
	}
	return o.Strings
}
