// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"ttd-workflows/models/components"
)

type CreateAdGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	AdGroupPayload *components.AdGroupPayload
}

func (o *CreateAdGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateAdGroupResponse) GetAdGroupPayload() *components.AdGroupPayload {
	if o == nil {
		return nil
	}
	return o.AdGroupPayload
}
