// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type CreateCampaignsJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Accepted
	StandardJobSubmitResponse *components.StandardJobSubmitResponse
}

func (o *CreateCampaignsJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateCampaignsJobResponse) GetStandardJobSubmitResponse() *components.StandardJobSubmitResponse {
	if o == nil {
		return nil
	}
	return o.StandardJobSubmitResponse
}
