// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type CreateAdGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	AdGroupPayload *components.AdGroupPayload
}

func (c *CreateAdGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateAdGroupResponse) GetAdGroupPayload() *components.AdGroupPayload {
	if c == nil {
		return nil
	}
	return c.AdGroupPayload
}
