// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type CreateCampaignsJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Accepted
	StandardJobSubmitResponse *components.StandardJobSubmitResponse
}

func (c *CreateCampaignsJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCampaignsJobResponse) GetStandardJobSubmitResponse() *components.StandardJobSubmitResponse {
	if c == nil {
		return nil
	}
	return c.StandardJobSubmitResponse
}
