// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type CreateCampaignResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	CampaignPayload *components.CampaignPayload
}

func (c *CreateCampaignResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCampaignResponse) GetCampaignPayload() *components.CampaignPayload {
	if c == nil {
		return nil
	}
	return c.CampaignPayload
}
