// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type GetCampaignVersionRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetCampaignVersionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetCampaignVersionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	CampaignVersionWorkflow *components.CampaignVersionWorkflow
}

func (o *GetCampaignVersionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetCampaignVersionResponse) GetCampaignVersionWorkflow() *components.CampaignVersionWorkflow {
	if o == nil {
		return nil
	}
	return o.CampaignVersionWorkflow
}
