// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type GetGraphQlBulkJobStatusRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetGraphQlBulkJobStatusRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetGraphQlBulkJobStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GraphQLBulkJobRetrievalResponse *components.GraphQLBulkJobRetrievalResponse
}

func (g *GetGraphQlBulkJobStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetGraphQlBulkJobStatusResponse) GetGraphQLBulkJobRetrievalResponse() *components.GraphQLBulkJobRetrievalResponse {
	if g == nil {
		return nil
	}
	return g.GraphQLBulkJobRetrievalResponse
}
