// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"ttd-workflows/models/components"
)

type GetGraphQlQueryJobStatusRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetGraphQlQueryJobStatusRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetGraphQlQueryJobStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GraphQLQueryJobRetrievalResponse *components.GraphQLQueryJobRetrievalResponse
}

func (o *GetGraphQlQueryJobStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetGraphQlQueryJobStatusResponse) GetGraphQLQueryJobRetrievalResponse() *components.GraphQLQueryJobRetrievalResponse {
	if o == nil {
		return nil
	}
	return o.GraphQLQueryJobRetrievalResponse
}
