// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type GetJobStatusRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetJobStatusRequest) GetID() int64 {
	if g == nil {
		return 0
	}
	return g.ID
}

type GetJobStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	StandardJobStatusResponse *components.StandardJobStatusResponse
}

func (g *GetJobStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetJobStatusResponse) GetStandardJobStatusResponse() *components.StandardJobStatusResponse {
	if g == nil {
		return nil
	}
	return g.StandardJobStatusResponse
}
