// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"ttd-workflows/models/components"
)

type GetJobStatusRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetJobStatusRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type GetJobStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	StandardJobStatusResponse *components.StandardJobStatusResponse
}

func (o *GetJobStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetJobStatusResponse) GetStandardJobStatusResponse() *components.StandardJobStatusResponse {
	if o == nil {
		return nil
	}
	return o.StandardJobStatusResponse
}
