// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type GetThirdPartyDataJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Accepted
	StandardJobSubmitResponse *components.StandardJobSubmitResponse
}

func (g *GetThirdPartyDataJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetThirdPartyDataJobResponse) GetStandardJobSubmitResponse() *components.StandardJobSubmitResponse {
	if g == nil {
		return nil
	}
	return g.StandardJobSubmitResponse
}
