// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"ttd-workflows/models/components"
)

type SubmitGraphQlRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object map[string]any
}

func (o *SubmitGraphQlRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SubmitGraphQlRequestResponse) GetObject() map[string]any {
	if o == nil {
		return nil
	}
	return o.Object
}
