// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"ttd-workflows/models/components"
)

type SubmitGraphQlQueryJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GraphQlQueryJobResponse *components.GraphQlQueryJobResponse
}

func (o *SubmitGraphQlQueryJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SubmitGraphQlQueryJobResponse) GetGraphQlQueryJobResponse() *components.GraphQlQueryJobResponse {
	if o == nil {
		return nil
	}
	return o.GraphQlQueryJobResponse
}
