// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"ttd-workflows/models/components"
)

// SubmitGraphQlRequestResponseBody - OK
type SubmitGraphQlRequestResponseBody struct {
}

type SubmitGraphQlRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object *SubmitGraphQlRequestResponseBody
}

func (o *SubmitGraphQlRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SubmitGraphQlRequestResponse) GetObject() *SubmitGraphQlRequestResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
