// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"ttd-workflows/models/components"
)

// SubmitRestRequestResponseBody - OK
type SubmitRestRequestResponseBody struct {
}

type SubmitRestRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object *SubmitRestRequestResponseBody
}

func (o *SubmitRestRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SubmitRestRequestResponse) GetObject() *SubmitRestRequestResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
