// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type SubmitGraphQlBulkQueryJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GraphQlBulkJobResponse *components.GraphQlBulkJobResponse
}

func (s *SubmitGraphQlBulkQueryJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SubmitGraphQlBulkQueryJobResponse) GetGraphQlBulkJobResponse() *components.GraphQlBulkJobResponse {
	if s == nil {
		return nil
	}
	return s.GraphQlBulkJobResponse
}
