// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type SubmitGraphQlRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object map[string]any
}

func (s *SubmitGraphQlRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SubmitGraphQlRequestResponse) GetObject() map[string]any {
	if s == nil {
		return nil
	}
	return s.Object
}
