// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type UpdateCampaignResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	CampaignPayload *components.CampaignPayload
}

func (o *UpdateCampaignResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateCampaignResponse) GetCampaignPayload() *components.CampaignPayload {
	if o == nil {
		return nil
	}
	return o.CampaignPayload
}
