// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type UpdateCampaignsJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Accepted
	StandardJobSubmitResponse *components.StandardJobSubmitResponse
	// OK
	CampaignPayload *components.CampaignPayload
}

func (o *UpdateCampaignsJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateCampaignsJobResponse) GetStandardJobSubmitResponse() *components.StandardJobSubmitResponse {
	if o == nil {
		return nil
	}
	return o.StandardJobSubmitResponse
}

func (o *UpdateCampaignsJobResponse) GetCampaignPayload() *components.CampaignPayload {
	if o == nil {
		return nil
	}
	return o.CampaignPayload
}
