// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type UpdateCampaignResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	CampaignPayload *components.CampaignPayload
}

func (u *UpdateCampaignResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateCampaignResponse) GetCampaignPayload() *components.CampaignPayload {
	if u == nil {
		return nil
	}
	return u.CampaignPayload
}
