// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type UpdateAdGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AdGroupPayload *components.AdGroupPayload
}

func (u *UpdateAdGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateAdGroupResponse) GetAdGroupPayload() *components.AdGroupPayload {
	if u == nil {
		return nil
	}
	return u.AdGroupPayload
}
