// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type UpdateAdGroupsJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Accepted
	StandardJobSubmitResponse *components.StandardJobSubmitResponse
}

func (u *UpdateAdGroupsJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateAdGroupsJobResponse) GetStandardJobSubmitResponse() *components.StandardJobSubmitResponse {
	if u == nil {
		return nil
	}
	return u.StandardJobSubmitResponse
}
