// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"ttd-workflows/models/components"
)

type UpdateAdGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AdGroupPayload *components.AdGroupPayload
}

func (o *UpdateAdGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateAdGroupResponse) GetAdGroupPayload() *components.AdGroupPayload {
	if o == nil {
		return nil
	}
	return o.AdGroupPayload
}
