// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"ttd-workflows/models/components"
)

type UpdateAdGroupsJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Accepted
	StandardJobSubmitResponse *components.StandardJobSubmitResponse
}

func (o *UpdateAdGroupsJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateAdGroupsJobResponse) GetStandardJobSubmitResponse() *components.StandardJobSubmitResponse {
	if o == nil {
		return nil
	}
	return o.StandardJobSubmitResponse
}
