// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thetradedesk/ttd-workflows-go/models/components"
)

type UpdateCampaignsJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Accepted
	StandardJobSubmitResponse *components.StandardJobSubmitResponse
	// OK
	CampaignPayload *components.CampaignPayload
}

func (u *UpdateCampaignsJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateCampaignsJobResponse) GetStandardJobSubmitResponse() *components.StandardJobSubmitResponse {
	if u == nil {
		return nil
	}
	return u.StandardJobSubmitResponse
}

func (u *UpdateCampaignsJobResponse) GetCampaignPayload() *components.CampaignPayload {
	if u == nil {
		return nil
	}
	return u.CampaignPayload
}
