// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupAudienceTargeting struct {
	AudienceID                           *string `json:"audienceId,omitempty"`
	AudienceAcceleratorExclusionsEnabled bool    `json:"audienceAcceleratorExclusionsEnabled"`
	AudienceBoosterEnabled               bool    `json:"audienceBoosterEnabled"`
	AudienceExcluderEnabled              bool    `json:"audienceExcluderEnabled"`
	AudiencePredictorEnabled             bool    `json:"audiencePredictorEnabled"`
	CrossDeviceVendorListForAudience     []int   `json:"crossDeviceVendorListForAudience"`
	RecencyExclusionWindowInMinutes      int     `json:"recencyExclusionWindowInMinutes"`
	TargetTrackableUsersEnabled          bool    `json:"targetTrackableUsersEnabled"`
	UseMcIDAsPrimary                     bool    `json:"useMcIdAsPrimary"`
}

func (o *AdGroupAudienceTargeting) GetAudienceID() *string {
	if o == nil {
		return nil
	}
	return o.AudienceID
}

func (o *AdGroupAudienceTargeting) GetAudienceAcceleratorExclusionsEnabled() bool {
	if o == nil {
		return false
	}
	return o.AudienceAcceleratorExclusionsEnabled
}

func (o *AdGroupAudienceTargeting) GetAudienceBoosterEnabled() bool {
	if o == nil {
		return false
	}
	return o.AudienceBoosterEnabled
}

func (o *AdGroupAudienceTargeting) GetAudienceExcluderEnabled() bool {
	if o == nil {
		return false
	}
	return o.AudienceExcluderEnabled
}

func (o *AdGroupAudienceTargeting) GetAudiencePredictorEnabled() bool {
	if o == nil {
		return false
	}
	return o.AudiencePredictorEnabled
}

func (o *AdGroupAudienceTargeting) GetCrossDeviceVendorListForAudience() []int {
	if o == nil {
		return nil
	}
	return o.CrossDeviceVendorListForAudience
}

func (o *AdGroupAudienceTargeting) GetRecencyExclusionWindowInMinutes() int {
	if o == nil {
		return 0
	}
	return o.RecencyExclusionWindowInMinutes
}

func (o *AdGroupAudienceTargeting) GetTargetTrackableUsersEnabled() bool {
	if o == nil {
		return false
	}
	return o.TargetTrackableUsersEnabled
}

func (o *AdGroupAudienceTargeting) GetUseMcIDAsPrimary() bool {
	if o == nil {
		return false
	}
	return o.UseMcIDAsPrimary
}
