// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupCreateWorkflowOwnedBidListInput struct {
	Name                     *string                       `json:"name,omitempty"`
	AdjustmentType           *BidListAdjustmentType        `json:"adjustmentType,omitempty"`
	ResolutionType           *MultipleMatchResolutionType  `json:"resolutionType,omitempty"`
	Dimensions               []BidListDimension            `json:"dimensions,omitempty"`
	BidLines                 []BidLineCreateInput          `json:"bidLines,omitempty"`
	Source                   *BidListSource                `json:"source,omitempty"`
	IsAvailableForLibraryUse *bool                         `json:"isAvailableForLibraryUse,omitempty"`
	AssociateBehavior        *BidListAssociateBehavior     `json:"associateBehavior,omitempty"`
	DimensionConfig          *BidListDimensionOptionsInput `json:"dimensionConfig,omitempty"`
	IsDefaultForDimension    *bool                         `json:"isDefaultForDimension,omitempty"`
}

func (a *AdGroupCreateWorkflowOwnedBidListInput) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AdGroupCreateWorkflowOwnedBidListInput) GetAdjustmentType() *BidListAdjustmentType {
	if a == nil {
		return nil
	}
	return a.AdjustmentType
}

func (a *AdGroupCreateWorkflowOwnedBidListInput) GetResolutionType() *MultipleMatchResolutionType {
	if a == nil {
		return nil
	}
	return a.ResolutionType
}

func (a *AdGroupCreateWorkflowOwnedBidListInput) GetDimensions() []BidListDimension {
	if a == nil {
		return nil
	}
	return a.Dimensions
}

func (a *AdGroupCreateWorkflowOwnedBidListInput) GetBidLines() []BidLineCreateInput {
	if a == nil {
		return nil
	}
	return a.BidLines
}

func (a *AdGroupCreateWorkflowOwnedBidListInput) GetSource() *BidListSource {
	if a == nil {
		return nil
	}
	return a.Source
}

func (a *AdGroupCreateWorkflowOwnedBidListInput) GetIsAvailableForLibraryUse() *bool {
	if a == nil {
		return nil
	}
	return a.IsAvailableForLibraryUse
}

func (a *AdGroupCreateWorkflowOwnedBidListInput) GetAssociateBehavior() *BidListAssociateBehavior {
	if a == nil {
		return nil
	}
	return a.AssociateBehavior
}

func (a *AdGroupCreateWorkflowOwnedBidListInput) GetDimensionConfig() *BidListDimensionOptionsInput {
	if a == nil {
		return nil
	}
	return a.DimensionConfig
}

func (a *AdGroupCreateWorkflowOwnedBidListInput) GetIsDefaultForDimension() *bool {
	if a == nil {
		return nil
	}
	return a.IsDefaultForDimension
}
