// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupFlight struct {
	AllocationType                  AllocationType `json:"allocationType"`
	BudgetInAdvertiserCurrency      float64        `json:"budgetInAdvertiserCurrency"`
	BudgetInImpressions             *int64         `json:"budgetInImpressions,omitempty"`
	DailyTargetInAdvertiserCurrency *float64       `json:"dailyTargetInAdvertiserCurrency,omitempty"`
	DailyTargetInImpressions        *int64         `json:"dailyTargetInImpressions,omitempty"`
	CampaignFlightID                int64          `json:"campaignFlightId"`
	AdGroupID                       *string        `json:"adGroupId"`
}

func (o *AdGroupFlight) GetAllocationType() AllocationType {
	if o == nil {
		return AllocationType("")
	}
	return o.AllocationType
}

func (o *AdGroupFlight) GetBudgetInAdvertiserCurrency() float64 {
	if o == nil {
		return 0.0
	}
	return o.BudgetInAdvertiserCurrency
}

func (o *AdGroupFlight) GetBudgetInImpressions() *int64 {
	if o == nil {
		return nil
	}
	return o.BudgetInImpressions
}

func (o *AdGroupFlight) GetDailyTargetInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.DailyTargetInAdvertiserCurrency
}

func (o *AdGroupFlight) GetDailyTargetInImpressions() *int64 {
	if o == nil {
		return nil
	}
	return o.DailyTargetInImpressions
}

func (o *AdGroupFlight) GetCampaignFlightID() int64 {
	if o == nil {
		return 0
	}
	return o.CampaignFlightID
}

func (o *AdGroupFlight) GetAdGroupID() *string {
	if o == nil {
		return nil
	}
	return o.AdGroupID
}
