// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupCreateWorkflowInput struct {
	PrimaryInput  AdGroupCreateWorkflowPrimaryInput `json:"primaryInput"`
	CampaignID    *string                           `json:"campaignId"`
	AdvancedInput *AdGroupWorkflowAdvancedInput     `json:"advancedInput,omitempty"`
}

func (o *AdGroupCreateWorkflowInput) GetPrimaryInput() AdGroupCreateWorkflowPrimaryInput {
	if o == nil {
		return AdGroupCreateWorkflowPrimaryInput{}
	}
	return o.PrimaryInput
}

func (o *AdGroupCreateWorkflowInput) GetCampaignID() *string {
	if o == nil {
		return nil
	}
	return o.CampaignID
}

func (o *AdGroupCreateWorkflowInput) GetAdvancedInput() *AdGroupWorkflowAdvancedInput {
	if o == nil {
		return nil
	}
	return o.AdvancedInput
}
