// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupBulkUpdateWorkflowInputWithValidation struct {
	Input             []AdGroupUpdateWorkflowInput `json:"input"`
	ValidateInputOnly *bool                        `json:"validateInputOnly,omitempty"`
	CallbackInput     *WorkflowCallbackInput       `json:"callbackInput,omitempty"`
}

func (o *AdGroupBulkUpdateWorkflowInputWithValidation) GetInput() []AdGroupUpdateWorkflowInput {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *AdGroupBulkUpdateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if o == nil {
		return nil
	}
	return o.ValidateInputOnly
}

func (o *AdGroupBulkUpdateWorkflowInputWithValidation) GetCallbackInput() *WorkflowCallbackInput {
	if o == nil {
		return nil
	}
	return o.CallbackInput
}
