// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupNielsenTrackingAttributes struct {
	EnhancedReportingOption EnhancedNielsenReportingOptions `json:"enhancedReportingOption"`
	Gender                  TargetingGender                 `json:"gender"`
	StartAge                TargetingStartAge               `json:"startAge"`
	EndAge                  TargetingEndAge                 `json:"endAge"`
	Countries               []string                        `json:"countries"`
}

func (o *AdGroupNielsenTrackingAttributes) GetEnhancedReportingOption() EnhancedNielsenReportingOptions {
	if o == nil {
		return EnhancedNielsenReportingOptions("")
	}
	return o.EnhancedReportingOption
}

func (o *AdGroupNielsenTrackingAttributes) GetGender() TargetingGender {
	if o == nil {
		return TargetingGender("")
	}
	return o.Gender
}

func (o *AdGroupNielsenTrackingAttributes) GetStartAge() TargetingStartAge {
	if o == nil {
		return TargetingStartAge("")
	}
	return o.StartAge
}

func (o *AdGroupNielsenTrackingAttributes) GetEndAge() TargetingEndAge {
	if o == nil {
		return TargetingEndAge("")
	}
	return o.EndAge
}

func (o *AdGroupNielsenTrackingAttributes) GetCountries() []string {
	if o == nil {
		return nil
	}
	return o.Countries
}
