// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupUpdateWorkflowInput struct {
	ID            *string                            `json:"id"`
	PrimaryInput  *AdGroupUpdateWorkflowPrimaryInput `json:"primaryInput,omitempty"`
	AdvancedInput *AdGroupWorkflowAdvancedInput      `json:"advancedInput,omitempty"`
}

func (a *AdGroupUpdateWorkflowInput) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AdGroupUpdateWorkflowInput) GetPrimaryInput() *AdGroupUpdateWorkflowPrimaryInput {
	if a == nil {
		return nil
	}
	return a.PrimaryInput
}

func (a *AdGroupUpdateWorkflowInput) GetAdvancedInput() *AdGroupWorkflowAdvancedInput {
	if a == nil {
		return nil
	}
	return a.AdvancedInput
}
