// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowAssociateBidListInput struct {
	BidListID             string `json:"bidListId"`
	IsEnabled             *bool  `json:"isEnabled,omitempty"`
	IsDefaultForDimension *bool  `json:"isDefaultForDimension,omitempty"`
}

func (o *AdGroupWorkflowAssociateBidListInput) GetBidListID() string {
	if o == nil {
		return ""
	}
	return o.BidListID
}

func (o *AdGroupWorkflowAssociateBidListInput) GetIsEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.IsEnabled
}

func (o *AdGroupWorkflowAssociateBidListInput) GetIsDefaultForDimension() *bool {
	if o == nil {
		return nil
	}
	return o.IsDefaultForDimension
}
