// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupUpdateWorkflowPrimaryInput struct {
	IsEnabled                      *bool                                  `json:"isEnabled,omitempty"`
	Description                    *string                                `json:"description,omitempty"`
	Budget                         *AdGroupWorkflowBudgetInput            `json:"budget,omitempty"`
	BaseBidCPMInAdvertiserCurrency *float64                               `json:"baseBidCPMInAdvertiserCurrency,omitempty"`
	MaxBidCPMInAdvertiserCurrency  *float64                               `json:"maxBidCPMInAdvertiserCurrency,omitempty"`
	AudienceTargeting              *AdGroupWorkflowAudienceTargetingInput `json:"audienceTargeting,omitempty"`
	RoiGoal                        *AdGroupWorkflowROIGoalInput           `json:"roiGoal,omitempty"`
	CreativeIds                    []string                               `json:"creativeIds,omitempty"`
	AssociatedBidLists             []AdGroupWorkflowAssociateBidListInput `json:"associatedBidLists,omitempty"`
	Name                           *string                                `json:"name,omitempty"`
	Channel                        *AdGroupChannel                        `json:"channel,omitempty"`
	FunnelLocation                 *AdGroupFunnelLocation                 `json:"funnelLocation,omitempty"`
	MarketType                     *MarketType                            `json:"marketType,omitempty"`
}

func (a *AdGroupUpdateWorkflowPrimaryInput) GetIsEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.IsEnabled
}

func (a *AdGroupUpdateWorkflowPrimaryInput) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AdGroupUpdateWorkflowPrimaryInput) GetBudget() *AdGroupWorkflowBudgetInput {
	if a == nil {
		return nil
	}
	return a.Budget
}

func (a *AdGroupUpdateWorkflowPrimaryInput) GetBaseBidCPMInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.BaseBidCPMInAdvertiserCurrency
}

func (a *AdGroupUpdateWorkflowPrimaryInput) GetMaxBidCPMInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.MaxBidCPMInAdvertiserCurrency
}

func (a *AdGroupUpdateWorkflowPrimaryInput) GetAudienceTargeting() *AdGroupWorkflowAudienceTargetingInput {
	if a == nil {
		return nil
	}
	return a.AudienceTargeting
}

func (a *AdGroupUpdateWorkflowPrimaryInput) GetRoiGoal() *AdGroupWorkflowROIGoalInput {
	if a == nil {
		return nil
	}
	return a.RoiGoal
}

func (a *AdGroupUpdateWorkflowPrimaryInput) GetCreativeIds() []string {
	if a == nil {
		return nil
	}
	return a.CreativeIds
}

func (a *AdGroupUpdateWorkflowPrimaryInput) GetAssociatedBidLists() []AdGroupWorkflowAssociateBidListInput {
	if a == nil {
		return nil
	}
	return a.AssociatedBidLists
}

func (a *AdGroupUpdateWorkflowPrimaryInput) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AdGroupUpdateWorkflowPrimaryInput) GetChannel() *AdGroupChannel {
	if a == nil {
		return nil
	}
	return a.Channel
}

func (a *AdGroupUpdateWorkflowPrimaryInput) GetFunnelLocation() *AdGroupFunnelLocation {
	if a == nil {
		return nil
	}
	return a.FunnelLocation
}

func (a *AdGroupUpdateWorkflowPrimaryInput) GetMarketType() *MarketType {
	if a == nil {
		return nil
	}
	return a.MarketType
}
