// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupContractTargeting struct {
	AllowOpenMarketBiddingWhenTargetingContracts bool `json:"allowOpenMarketBiddingWhenTargetingContracts"`
}

func (o *AdGroupContractTargeting) GetAllowOpenMarketBiddingWhenTargetingContracts() bool {
	if o == nil {
		return false
	}
	return o.AllowOpenMarketBiddingWhenTargetingContracts
}
