// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupCreateWorkflowInputWithValidation struct {
	PrimaryInput      AdGroupCreateWorkflowPrimaryInput `json:"primaryInput"`
	CampaignID        *string                           `json:"campaignId"`
	AdvancedInput     *AdGroupWorkflowAdvancedInput     `json:"advancedInput,omitempty"`
	ValidateInputOnly *bool                             `json:"validateInputOnly,omitempty"`
}

func (o *AdGroupCreateWorkflowInputWithValidation) GetPrimaryInput() AdGroupCreateWorkflowPrimaryInput {
	if o == nil {
		return AdGroupCreateWorkflowPrimaryInput{}
	}
	return o.PrimaryInput
}

func (o *AdGroupCreateWorkflowInputWithValidation) GetCampaignID() *string {
	if o == nil {
		return nil
	}
	return o.CampaignID
}

func (o *AdGroupCreateWorkflowInputWithValidation) GetAdvancedInput() *AdGroupWorkflowAdvancedInput {
	if o == nil {
		return nil
	}
	return o.AdvancedInput
}

func (o *AdGroupCreateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if o == nil {
		return nil
	}
	return o.ValidateInputOnly
}
