// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupBulkCreateWorkflowInputWithValidation struct {
	Input             []AdGroupCreateWorkflowInput `json:"input"`
	ValidateInputOnly *bool                        `json:"validateInputOnly,omitempty"`
	CallbackInput     *WorkflowCallbackInput       `json:"callbackInput,omitempty"`
}

func (o *AdGroupBulkCreateWorkflowInputWithValidation) GetInput() []AdGroupCreateWorkflowInput {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *AdGroupBulkCreateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if o == nil {
		return nil
	}
	return o.ValidateInputOnly
}

func (o *AdGroupBulkCreateWorkflowInputWithValidation) GetCallbackInput() *WorkflowCallbackInput {
	if o == nil {
		return nil
	}
	return o.CallbackInput
}
