// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupCreateWorkflowInput struct {
	PrimaryInput  AdGroupCreateWorkflowPrimaryInput `json:"primaryInput"`
	CampaignID    *string                           `json:"campaignId"`
	AdvancedInput *AdGroupWorkflowAdvancedInput     `json:"advancedInput,omitempty"`
}

func (a *AdGroupCreateWorkflowInput) GetPrimaryInput() AdGroupCreateWorkflowPrimaryInput {
	if a == nil {
		return AdGroupCreateWorkflowPrimaryInput{}
	}
	return a.PrimaryInput
}

func (a *AdGroupCreateWorkflowInput) GetCampaignID() *string {
	if a == nil {
		return nil
	}
	return a.CampaignID
}

func (a *AdGroupCreateWorkflowInput) GetAdvancedInput() *AdGroupWorkflowAdvancedInput {
	if a == nil {
		return nil
	}
	return a.AdvancedInput
}
