// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type AdGroupChannel string

const (
	AdGroupChannelOther         AdGroupChannel = "Other"
	AdGroupChannelDisplay       AdGroupChannel = "Display"
	AdGroupChannelVideo         AdGroupChannel = "Video"
	AdGroupChannelAudio         AdGroupChannel = "Audio"
	AdGroupChannelNative        AdGroupChannel = "Native"
	AdGroupChannelNativeDisplay AdGroupChannel = "NativeDisplay"
	AdGroupChannelNativeVideo   AdGroupChannel = "NativeVideo"
	AdGroupChannelTv            AdGroupChannel = "TV"
	AdGroupChannelOutOfHome     AdGroupChannel = "OutOfHome"
)

func (e AdGroupChannel) ToPointer() *AdGroupChannel {
	return &e
}
func (e *AdGroupChannel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Other":
		fallthrough
	case "Display":
		fallthrough
	case "Video":
		fallthrough
	case "Audio":
		fallthrough
	case "Native":
		fallthrough
	case "NativeDisplay":
		fallthrough
	case "NativeVideo":
		fallthrough
	case "TV":
		fallthrough
	case "OutOfHome":
		*e = AdGroupChannel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AdGroupChannel: %v", v)
	}
}
