// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupUpdateWorkflowInputWithValidation struct {
	ID                *string                            `json:"id"`
	PrimaryInput      *AdGroupUpdateWorkflowPrimaryInput `json:"primaryInput,omitempty"`
	AdvancedInput     *AdGroupWorkflowAdvancedInput      `json:"advancedInput,omitempty"`
	ValidateInputOnly *bool                              `json:"validateInputOnly,omitempty"`
}

func (a *AdGroupUpdateWorkflowInputWithValidation) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AdGroupUpdateWorkflowInputWithValidation) GetPrimaryInput() *AdGroupUpdateWorkflowPrimaryInput {
	if a == nil {
		return nil
	}
	return a.PrimaryInput
}

func (a *AdGroupUpdateWorkflowInputWithValidation) GetAdvancedInput() *AdGroupWorkflowAdvancedInput {
	if a == nil {
		return nil
	}
	return a.AdvancedInput
}

func (a *AdGroupUpdateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if a == nil {
		return nil
	}
	return a.ValidateInputOnly
}
