// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowNielsenTrackingAttributesInput struct {
	EnhancedReportingOption *EnhancedNielsenReportingOptionsInput `json:"enhancedReportingOption,omitempty"`
	Gender                  TargetingGenderInput                  `json:"gender"`
	StartAge                TargetingStartAgeInput                `json:"startAge"`
	EndAge                  TargetingEndAgeInput                  `json:"endAge"`
	Countries               []string                              `json:"countries"`
}

func (a *AdGroupWorkflowNielsenTrackingAttributesInput) GetEnhancedReportingOption() *EnhancedNielsenReportingOptionsInput {
	if a == nil {
		return nil
	}
	return a.EnhancedReportingOption
}

func (a *AdGroupWorkflowNielsenTrackingAttributesInput) GetGender() TargetingGenderInput {
	if a == nil {
		return TargetingGenderInput("")
	}
	return a.Gender
}

func (a *AdGroupWorkflowNielsenTrackingAttributesInput) GetStartAge() TargetingStartAgeInput {
	if a == nil {
		return TargetingStartAgeInput("")
	}
	return a.StartAge
}

func (a *AdGroupWorkflowNielsenTrackingAttributesInput) GetEndAge() TargetingEndAgeInput {
	if a == nil {
		return TargetingEndAgeInput("")
	}
	return a.EndAge
}

func (a *AdGroupWorkflowNielsenTrackingAttributesInput) GetCountries() []string {
	if a == nil {
		return nil
	}
	return a.Countries
}
