// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupComscoreSettings struct {
	IsEnabled                  bool  `json:"isEnabled"`
	PopulationID               *int  `json:"populationId,omitempty"`
	DemographicMemberIds       []int `json:"demographicMemberIds"`
	MobileDemographicMemberIds []int `json:"mobileDemographicMemberIds"`
}

func (o *AdGroupComscoreSettings) GetIsEnabled() bool {
	if o == nil {
		return false
	}
	return o.IsEnabled
}

func (o *AdGroupComscoreSettings) GetPopulationID() *int {
	if o == nil {
		return nil
	}
	return o.PopulationID
}

func (o *AdGroupComscoreSettings) GetDemographicMemberIds() []int {
	if o == nil {
		return nil
	}
	return o.DemographicMemberIds
}

func (o *AdGroupComscoreSettings) GetMobileDemographicMemberIds() []int {
	if o == nil {
		return nil
	}
	return o.MobileDemographicMemberIds
}
