// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupUpdateWorkflowPrimaryInput struct {
	IsEnabled                      *bool                                  `json:"isEnabled,omitempty"`
	Description                    *string                                `json:"description,omitempty"`
	Budget                         *AdGroupWorkflowBudgetInput            `json:"budget,omitempty"`
	BaseBidCPMInAdvertiserCurrency *float64                               `json:"baseBidCPMInAdvertiserCurrency,omitempty"`
	MaxBidCPMInAdvertiserCurrency  *float64                               `json:"maxBidCPMInAdvertiserCurrency,omitempty"`
	AudienceTargeting              *AdGroupWorkflowAudienceTargetingInput `json:"audienceTargeting,omitempty"`
	RoiGoal                        *AdGroupWorkflowROIGoalInput           `json:"roiGoal,omitempty"`
	CreativeIds                    []string                               `json:"creativeIds,omitempty"`
	AssociatedBidLists             []AdGroupWorkflowAssociateBidListInput `json:"associatedBidLists,omitempty"`
	Name                           *string                                `json:"name,omitempty"`
	Channel                        *AdGroupChannel                        `json:"channel,omitempty"`
	FunnelLocation                 *AdGroupFunnelLocation                 `json:"funnelLocation,omitempty"`
}

func (o *AdGroupUpdateWorkflowPrimaryInput) GetIsEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.IsEnabled
}

func (o *AdGroupUpdateWorkflowPrimaryInput) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *AdGroupUpdateWorkflowPrimaryInput) GetBudget() *AdGroupWorkflowBudgetInput {
	if o == nil {
		return nil
	}
	return o.Budget
}

func (o *AdGroupUpdateWorkflowPrimaryInput) GetBaseBidCPMInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.BaseBidCPMInAdvertiserCurrency
}

func (o *AdGroupUpdateWorkflowPrimaryInput) GetMaxBidCPMInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.MaxBidCPMInAdvertiserCurrency
}

func (o *AdGroupUpdateWorkflowPrimaryInput) GetAudienceTargeting() *AdGroupWorkflowAudienceTargetingInput {
	if o == nil {
		return nil
	}
	return o.AudienceTargeting
}

func (o *AdGroupUpdateWorkflowPrimaryInput) GetRoiGoal() *AdGroupWorkflowROIGoalInput {
	if o == nil {
		return nil
	}
	return o.RoiGoal
}

func (o *AdGroupUpdateWorkflowPrimaryInput) GetCreativeIds() []string {
	if o == nil {
		return nil
	}
	return o.CreativeIds
}

func (o *AdGroupUpdateWorkflowPrimaryInput) GetAssociatedBidLists() []AdGroupWorkflowAssociateBidListInput {
	if o == nil {
		return nil
	}
	return o.AssociatedBidLists
}

func (o *AdGroupUpdateWorkflowPrimaryInput) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AdGroupUpdateWorkflowPrimaryInput) GetChannel() *AdGroupChannel {
	if o == nil {
		return nil
	}
	return o.Channel
}

func (o *AdGroupUpdateWorkflowPrimaryInput) GetFunnelLocation() *AdGroupFunnelLocation {
	if o == nil {
		return nil
	}
	return o.FunnelLocation
}
