// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupAssociateBidList struct {
	BidListID             *string `json:"bidListId"`
	IsEnabled             bool    `json:"isEnabled"`
	IsDefaultForDimension bool    `json:"isDefaultForDimension"`
}

func (a *AdGroupAssociateBidList) GetBidListID() *string {
	if a == nil {
		return nil
	}
	return a.BidListID
}

func (a *AdGroupAssociateBidList) GetIsEnabled() bool {
	if a == nil {
		return false
	}
	return a.IsEnabled
}

func (a *AdGroupAssociateBidList) GetIsDefaultForDimension() bool {
	if a == nil {
		return false
	}
	return a.IsDefaultForDimension
}
