// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowContractTargetingInput struct {
	AllowOpenMarketBiddingWhenTargetingContracts *bool `json:"allowOpenMarketBiddingWhenTargetingContracts,omitempty"`
}

func (a *AdGroupWorkflowContractTargetingInput) GetAllowOpenMarketBiddingWhenTargetingContracts() *bool {
	if a == nil {
		return nil
	}
	return a.AllowOpenMarketBiddingWhenTargetingContracts
}
