// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowAudienceTargetingInput struct {
	AudienceID                           *string `json:"audienceId,omitempty"`
	AudienceAcceleratorExclusionsEnabled *bool   `json:"audienceAcceleratorExclusionsEnabled,omitempty"`
	AudienceBoosterEnabled               *bool   `json:"audienceBoosterEnabled,omitempty"`
	AudienceExcluderEnabled              *bool   `json:"audienceExcluderEnabled,omitempty"`
	AudiencePredictorEnabled             *bool   `json:"audiencePredictorEnabled,omitempty"`
	CrossDeviceVendorListForAudience     []int   `json:"crossDeviceVendorListForAudience,omitempty"`
	RecencyExclusionWindowInMinutes      *int    `json:"recencyExclusionWindowInMinutes,omitempty"`
	TargetTrackableUsersEnabled          *bool   `json:"targetTrackableUsersEnabled,omitempty"`
	UseMcIDAsPrimary                     *bool   `json:"useMcIdAsPrimary,omitempty"`
}

func (a *AdGroupWorkflowAudienceTargetingInput) GetAudienceID() *string {
	if a == nil {
		return nil
	}
	return a.AudienceID
}

func (a *AdGroupWorkflowAudienceTargetingInput) GetAudienceAcceleratorExclusionsEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.AudienceAcceleratorExclusionsEnabled
}

func (a *AdGroupWorkflowAudienceTargetingInput) GetAudienceBoosterEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.AudienceBoosterEnabled
}

func (a *AdGroupWorkflowAudienceTargetingInput) GetAudienceExcluderEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.AudienceExcluderEnabled
}

func (a *AdGroupWorkflowAudienceTargetingInput) GetAudiencePredictorEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.AudiencePredictorEnabled
}

func (a *AdGroupWorkflowAudienceTargetingInput) GetCrossDeviceVendorListForAudience() []int {
	if a == nil {
		return nil
	}
	return a.CrossDeviceVendorListForAudience
}

func (a *AdGroupWorkflowAudienceTargetingInput) GetRecencyExclusionWindowInMinutes() *int {
	if a == nil {
		return nil
	}
	return a.RecencyExclusionWindowInMinutes
}

func (a *AdGroupWorkflowAudienceTargetingInput) GetTargetTrackableUsersEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.TargetTrackableUsersEnabled
}

func (a *AdGroupWorkflowAudienceTargetingInput) GetUseMcIDAsPrimary() *bool {
	if a == nil {
		return nil
	}
	return a.UseMcIDAsPrimary
}
