// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupPayload struct {
	AdGroup *AdGroupWorkflow `json:"adGroup,omitempty"`
}

func (o *AdGroupPayload) GetAdGroup() *AdGroupWorkflow {
	if o == nil {
		return nil
	}
	return o.AdGroup
}
