// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowFlightInput struct {
	AllocationType                  *AllocationType `json:"allocationType,omitempty"`
	BudgetInAdvertiserCurrency      *float64        `json:"budgetInAdvertiserCurrency,omitempty"`
	BudgetInImpressions             *int64          `json:"budgetInImpressions,omitempty"`
	DailyTargetInAdvertiserCurrency *float64        `json:"dailyTargetInAdvertiserCurrency,omitempty"`
	DailyTargetInImpressions        *int64          `json:"dailyTargetInImpressions,omitempty"`
	CampaignFlightID                int64           `json:"campaignFlightId"`
}

func (o *AdGroupWorkflowFlightInput) GetAllocationType() *AllocationType {
	if o == nil {
		return nil
	}
	return o.AllocationType
}

func (o *AdGroupWorkflowFlightInput) GetBudgetInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.BudgetInAdvertiserCurrency
}

func (o *AdGroupWorkflowFlightInput) GetBudgetInImpressions() *int64 {
	if o == nil {
		return nil
	}
	return o.BudgetInImpressions
}

func (o *AdGroupWorkflowFlightInput) GetDailyTargetInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.DailyTargetInAdvertiserCurrency
}

func (o *AdGroupWorkflowFlightInput) GetDailyTargetInImpressions() *int64 {
	if o == nil {
		return nil
	}
	return o.DailyTargetInImpressions
}

func (o *AdGroupWorkflowFlightInput) GetCampaignFlightID() int64 {
	if o == nil {
		return 0
	}
	return o.CampaignFlightID
}
