// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowROIGoalInput struct {
	MaximizeReach               *bool    `json:"maximizeReach,omitempty"`
	MaximizeLtvIncrementalReach *bool    `json:"maximizeLtvIncrementalReach,omitempty"`
	CpcInAdvertiserCurrency     *float64 `json:"cpcInAdvertiserCurrency,omitempty"`
	CtrInPercent                *float64 `json:"ctrInPercent,omitempty"`
	NielsenOTPInPercent         *float64 `json:"nielsenOTPInPercent,omitempty"`
	CpaInAdvertiserCurrency     *float64 `json:"cpaInAdvertiserCurrency,omitempty"`
	ReturnOnAdSpendPercent      *float64 `json:"returnOnAdSpendPercent,omitempty"`
	VcrInPercent                *float64 `json:"vcrInPercent,omitempty"`
	ViewabilityInPercent        *float64 `json:"viewabilityInPercent,omitempty"`
	VcpmInAdvertiserCurrency    *float64 `json:"vcpmInAdvertiserCurrency,omitempty"`
	CpcvInAdvertiserCurrency    *float64 `json:"cpcvInAdvertiserCurrency,omitempty"`
	MiaozhenOTPInPercent        *float64 `json:"miaozhenOTPInPercent,omitempty"`
}

func (a *AdGroupWorkflowROIGoalInput) GetMaximizeReach() *bool {
	if a == nil {
		return nil
	}
	return a.MaximizeReach
}

func (a *AdGroupWorkflowROIGoalInput) GetMaximizeLtvIncrementalReach() *bool {
	if a == nil {
		return nil
	}
	return a.MaximizeLtvIncrementalReach
}

func (a *AdGroupWorkflowROIGoalInput) GetCpcInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.CpcInAdvertiserCurrency
}

func (a *AdGroupWorkflowROIGoalInput) GetCtrInPercent() *float64 {
	if a == nil {
		return nil
	}
	return a.CtrInPercent
}

func (a *AdGroupWorkflowROIGoalInput) GetNielsenOTPInPercent() *float64 {
	if a == nil {
		return nil
	}
	return a.NielsenOTPInPercent
}

func (a *AdGroupWorkflowROIGoalInput) GetCpaInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.CpaInAdvertiserCurrency
}

func (a *AdGroupWorkflowROIGoalInput) GetReturnOnAdSpendPercent() *float64 {
	if a == nil {
		return nil
	}
	return a.ReturnOnAdSpendPercent
}

func (a *AdGroupWorkflowROIGoalInput) GetVcrInPercent() *float64 {
	if a == nil {
		return nil
	}
	return a.VcrInPercent
}

func (a *AdGroupWorkflowROIGoalInput) GetViewabilityInPercent() *float64 {
	if a == nil {
		return nil
	}
	return a.ViewabilityInPercent
}

func (a *AdGroupWorkflowROIGoalInput) GetVcpmInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.VcpmInAdvertiserCurrency
}

func (a *AdGroupWorkflowROIGoalInput) GetCpcvInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.CpcvInAdvertiserCurrency
}

func (a *AdGroupWorkflowROIGoalInput) GetMiaozhenOTPInPercent() *float64 {
	if a == nil {
		return nil
	}
	return a.MiaozhenOTPInPercent
}
