// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupAudienceTargeting struct {
	AudienceID                           *string `json:"audienceId,omitempty"`
	AudienceAcceleratorExclusionsEnabled bool    `json:"audienceAcceleratorExclusionsEnabled"`
	AudienceBoosterEnabled               bool    `json:"audienceBoosterEnabled"`
	AudienceExcluderEnabled              bool    `json:"audienceExcluderEnabled"`
	AudiencePredictorEnabled             bool    `json:"audiencePredictorEnabled"`
	CrossDeviceVendorListForAudience     []int   `json:"crossDeviceVendorListForAudience"`
	RecencyExclusionWindowInMinutes      int     `json:"recencyExclusionWindowInMinutes"`
	TargetTrackableUsersEnabled          bool    `json:"targetTrackableUsersEnabled"`
	UseMcIDAsPrimary                     bool    `json:"useMcIdAsPrimary"`
}

func (a *AdGroupAudienceTargeting) GetAudienceID() *string {
	if a == nil {
		return nil
	}
	return a.AudienceID
}

func (a *AdGroupAudienceTargeting) GetAudienceAcceleratorExclusionsEnabled() bool {
	if a == nil {
		return false
	}
	return a.AudienceAcceleratorExclusionsEnabled
}

func (a *AdGroupAudienceTargeting) GetAudienceBoosterEnabled() bool {
	if a == nil {
		return false
	}
	return a.AudienceBoosterEnabled
}

func (a *AdGroupAudienceTargeting) GetAudienceExcluderEnabled() bool {
	if a == nil {
		return false
	}
	return a.AudienceExcluderEnabled
}

func (a *AdGroupAudienceTargeting) GetAudiencePredictorEnabled() bool {
	if a == nil {
		return false
	}
	return a.AudiencePredictorEnabled
}

func (a *AdGroupAudienceTargeting) GetCrossDeviceVendorListForAudience() []int {
	if a == nil {
		return nil
	}
	return a.CrossDeviceVendorListForAudience
}

func (a *AdGroupAudienceTargeting) GetRecencyExclusionWindowInMinutes() int {
	if a == nil {
		return 0
	}
	return a.RecencyExclusionWindowInMinutes
}

func (a *AdGroupAudienceTargeting) GetTargetTrackableUsersEnabled() bool {
	if a == nil {
		return false
	}
	return a.TargetTrackableUsersEnabled
}

func (a *AdGroupAudienceTargeting) GetUseMcIDAsPrimary() bool {
	if a == nil {
		return false
	}
	return a.UseMcIDAsPrimary
}
