// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupPayload struct {
	AdGroup *AdGroupWorkflow `json:"adGroup,omitempty"`
}

func (a *AdGroupPayload) GetAdGroup() *AdGroupWorkflow {
	if a == nil {
		return nil
	}
	return a.AdGroup
}
