// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupAssociateBidList struct {
	BidListID             *string `json:"bidListId"`
	IsEnabled             bool    `json:"isEnabled"`
	IsDefaultForDimension bool    `json:"isDefaultForDimension"`
}

func (o *AdGroupAssociateBidList) GetBidListID() *string {
	if o == nil {
		return nil
	}
	return o.BidListID
}

func (o *AdGroupAssociateBidList) GetIsEnabled() bool {
	if o == nil {
		return false
	}
	return o.IsEnabled
}

func (o *AdGroupAssociateBidList) GetIsDefaultForDimension() bool {
	if o == nil {
		return false
	}
	return o.IsDefaultForDimension
}
