// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupOwnedBidList struct {
	BidListID *string `json:"bidListId"`
}

func (a *AdGroupOwnedBidList) GetBidListID() *string {
	if a == nil {
		return nil
	}
	return a.BidListID
}
