// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowNewFrequencyConfigInput struct {
	CounterName            *string `json:"counterName"`
	FrequencyCap           *int    `json:"frequencyCap,omitempty"`
	FrequencyGoal          *int    `json:"frequencyGoal,omitempty"`
	ResetIntervalInMinutes *int    `json:"resetIntervalInMinutes,omitempty"`
}

func (o *AdGroupWorkflowNewFrequencyConfigInput) GetCounterName() *string {
	if o == nil {
		return nil
	}
	return o.CounterName
}

func (o *AdGroupWorkflowNewFrequencyConfigInput) GetFrequencyCap() *int {
	if o == nil {
		return nil
	}
	return o.FrequencyCap
}

func (o *AdGroupWorkflowNewFrequencyConfigInput) GetFrequencyGoal() *int {
	if o == nil {
		return nil
	}
	return o.FrequencyGoal
}

func (o *AdGroupWorkflowNewFrequencyConfigInput) GetResetIntervalInMinutes() *int {
	if o == nil {
		return nil
	}
	return o.ResetIntervalInMinutes
}
