// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowNewFrequencyConfigInput struct {
	CounterName            *string `json:"counterName"`
	FrequencyCap           *int    `json:"frequencyCap,omitempty"`
	FrequencyGoal          *int    `json:"frequencyGoal,omitempty"`
	ResetIntervalInMinutes *int    `json:"resetIntervalInMinutes,omitempty"`
}

func (a *AdGroupWorkflowNewFrequencyConfigInput) GetCounterName() *string {
	if a == nil {
		return nil
	}
	return a.CounterName
}

func (a *AdGroupWorkflowNewFrequencyConfigInput) GetFrequencyCap() *int {
	if a == nil {
		return nil
	}
	return a.FrequencyCap
}

func (a *AdGroupWorkflowNewFrequencyConfigInput) GetFrequencyGoal() *int {
	if a == nil {
		return nil
	}
	return a.FrequencyGoal
}

func (a *AdGroupWorkflowNewFrequencyConfigInput) GetResetIntervalInMinutes() *int {
	if a == nil {
		return nil
	}
	return a.ResetIntervalInMinutes
}
