// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupFlight struct {
	AllocationType                  AllocationType `json:"allocationType"`
	BudgetInAdvertiserCurrency      float64        `json:"budgetInAdvertiserCurrency"`
	BudgetInImpressions             *int64         `json:"budgetInImpressions,omitempty"`
	DailyTargetInAdvertiserCurrency *float64       `json:"dailyTargetInAdvertiserCurrency,omitempty"`
	DailyTargetInImpressions        *int64         `json:"dailyTargetInImpressions,omitempty"`
	CampaignFlightID                int64          `json:"campaignFlightId"`
	AdGroupID                       *string        `json:"adGroupId"`
}

func (a *AdGroupFlight) GetAllocationType() AllocationType {
	if a == nil {
		return AllocationType("")
	}
	return a.AllocationType
}

func (a *AdGroupFlight) GetBudgetInAdvertiserCurrency() float64 {
	if a == nil {
		return 0.0
	}
	return a.BudgetInAdvertiserCurrency
}

func (a *AdGroupFlight) GetBudgetInImpressions() *int64 {
	if a == nil {
		return nil
	}
	return a.BudgetInImpressions
}

func (a *AdGroupFlight) GetDailyTargetInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.DailyTargetInAdvertiserCurrency
}

func (a *AdGroupFlight) GetDailyTargetInImpressions() *int64 {
	if a == nil {
		return nil
	}
	return a.DailyTargetInImpressions
}

func (a *AdGroupFlight) GetCampaignFlightID() int64 {
	if a == nil {
		return 0
	}
	return a.CampaignFlightID
}

func (a *AdGroupFlight) GetAdGroupID() *string {
	if a == nil {
		return nil
	}
	return a.AdGroupID
}
