// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflow struct {
	ID                                         *string                           `json:"id"`
	Name                                       *string                           `json:"name"`
	CampaignID                                 *string                           `json:"campaignId"`
	IsEnabled                                  bool                              `json:"isEnabled"`
	Description                                *string                           `json:"description,omitempty"`
	ProgrammaticGuaranteedPrivateContractID    *string                           `json:"programmaticGuaranteedPrivateContractId,omitempty"`
	Channel                                    AdGroupChannel                    `json:"channel"`
	FunnelLocation                             AdGroupFunnelLocation             `json:"funnelLocation"`
	Budget                                     AdGroupBudget                     `json:"budget"`
	BaseBidCPMInAdvertiserCurrency             *float64                          `json:"baseBidCPMInAdvertiserCurrency,omitempty"`
	MaxBidCPMInAdvertiserCurrency              *float64                          `json:"maxBidCPMInAdvertiserCurrency,omitempty"`
	AudienceTargeting                          *AdGroupAudienceTargeting         `json:"audienceTargeting,omitempty"`
	RoiGoal                                    AdGroupROIGoal                    `json:"roiGoal"`
	CreativeIds                                []string                          `json:"creativeIds"`
	AssociatedBidLists                         []AdGroupAssociateBidList         `json:"associatedBidLists"`
	Flights                                    []AdGroupFlight                   `json:"flights"`
	KoaOptimizationSettings                    *AdGroupKoaOptimizationSettings   `json:"koaOptimizationSettings,omitempty"`
	ComscoreSettings                           AdGroupComscoreSettings           `json:"comscoreSettings"`
	ContractTargeting                          AdGroupContractTargeting          `json:"contractTargeting"`
	DimensionalBiddingAutoOptimizationSettings [][]DimensionalBiddingDimensions  `json:"dimensionalBiddingAutoOptimizationSettings"`
	IsUseClicksAsConversionsEnabled            bool                              `json:"isUseClicksAsConversionsEnabled"`
	IsUseSecondaryConversionsEnabled           bool                              `json:"isUseSecondaryConversionsEnabled"`
	NielsenTrackingAttributes                  *AdGroupNielsenTrackingAttributes `json:"nielsenTrackingAttributes,omitempty"`
}

func (o *AdGroupWorkflow) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AdGroupWorkflow) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AdGroupWorkflow) GetCampaignID() *string {
	if o == nil {
		return nil
	}
	return o.CampaignID
}

func (o *AdGroupWorkflow) GetIsEnabled() bool {
	if o == nil {
		return false
	}
	return o.IsEnabled
}

func (o *AdGroupWorkflow) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *AdGroupWorkflow) GetProgrammaticGuaranteedPrivateContractID() *string {
	if o == nil {
		return nil
	}
	return o.ProgrammaticGuaranteedPrivateContractID
}

func (o *AdGroupWorkflow) GetChannel() AdGroupChannel {
	if o == nil {
		return AdGroupChannel("")
	}
	return o.Channel
}

func (o *AdGroupWorkflow) GetFunnelLocation() AdGroupFunnelLocation {
	if o == nil {
		return AdGroupFunnelLocation("")
	}
	return o.FunnelLocation
}

func (o *AdGroupWorkflow) GetBudget() AdGroupBudget {
	if o == nil {
		return AdGroupBudget{}
	}
	return o.Budget
}

func (o *AdGroupWorkflow) GetBaseBidCPMInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.BaseBidCPMInAdvertiserCurrency
}

func (o *AdGroupWorkflow) GetMaxBidCPMInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.MaxBidCPMInAdvertiserCurrency
}

func (o *AdGroupWorkflow) GetAudienceTargeting() *AdGroupAudienceTargeting {
	if o == nil {
		return nil
	}
	return o.AudienceTargeting
}

func (o *AdGroupWorkflow) GetRoiGoal() AdGroupROIGoal {
	if o == nil {
		return AdGroupROIGoal{}
	}
	return o.RoiGoal
}

func (o *AdGroupWorkflow) GetCreativeIds() []string {
	if o == nil {
		return nil
	}
	return o.CreativeIds
}

func (o *AdGroupWorkflow) GetAssociatedBidLists() []AdGroupAssociateBidList {
	if o == nil {
		return nil
	}
	return o.AssociatedBidLists
}

func (o *AdGroupWorkflow) GetFlights() []AdGroupFlight {
	if o == nil {
		return nil
	}
	return o.Flights
}

func (o *AdGroupWorkflow) GetKoaOptimizationSettings() *AdGroupKoaOptimizationSettings {
	if o == nil {
		return nil
	}
	return o.KoaOptimizationSettings
}

func (o *AdGroupWorkflow) GetComscoreSettings() AdGroupComscoreSettings {
	if o == nil {
		return AdGroupComscoreSettings{}
	}
	return o.ComscoreSettings
}

func (o *AdGroupWorkflow) GetContractTargeting() AdGroupContractTargeting {
	if o == nil {
		return AdGroupContractTargeting{}
	}
	return o.ContractTargeting
}

func (o *AdGroupWorkflow) GetDimensionalBiddingAutoOptimizationSettings() [][]DimensionalBiddingDimensions {
	if o == nil {
		return nil
	}
	return o.DimensionalBiddingAutoOptimizationSettings
}

func (o *AdGroupWorkflow) GetIsUseClicksAsConversionsEnabled() bool {
	if o == nil {
		return false
	}
	return o.IsUseClicksAsConversionsEnabled
}

func (o *AdGroupWorkflow) GetIsUseSecondaryConversionsEnabled() bool {
	if o == nil {
		return false
	}
	return o.IsUseSecondaryConversionsEnabled
}

func (o *AdGroupWorkflow) GetNielsenTrackingAttributes() *AdGroupNielsenTrackingAttributes {
	if o == nil {
		return nil
	}
	return o.NielsenTrackingAttributes
}
