// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowAssociateBidListInput struct {
	BidListID             string `json:"bidListId"`
	IsEnabled             *bool  `json:"isEnabled,omitempty"`
	IsDefaultForDimension *bool  `json:"isDefaultForDimension,omitempty"`
}

func (a *AdGroupWorkflowAssociateBidListInput) GetBidListID() string {
	if a == nil {
		return ""
	}
	return a.BidListID
}

func (a *AdGroupWorkflowAssociateBidListInput) GetIsEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.IsEnabled
}

func (a *AdGroupWorkflowAssociateBidListInput) GetIsDefaultForDimension() *bool {
	if a == nil {
		return nil
	}
	return a.IsDefaultForDimension
}
