// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowROIGoalInput struct {
	MaximizeReach               *bool    `json:"maximizeReach,omitempty"`
	MaximizeLtvIncrementalReach *bool    `json:"maximizeLtvIncrementalReach,omitempty"`
	CpcInAdvertiserCurrency     *float64 `json:"cpcInAdvertiserCurrency,omitempty"`
	CtrInPercent                *float64 `json:"ctrInPercent,omitempty"`
	NielsenOTPInPercent         *float64 `json:"nielsenOTPInPercent,omitempty"`
	CpaInAdvertiserCurrency     *float64 `json:"cpaInAdvertiserCurrency,omitempty"`
	ReturnOnAdSpendPercent      *float64 `json:"returnOnAdSpendPercent,omitempty"`
	VcrInPercent                *float64 `json:"vcrInPercent,omitempty"`
	ViewabilityInPercent        *float64 `json:"viewabilityInPercent,omitempty"`
	VcpmInAdvertiserCurrency    *float64 `json:"vcpmInAdvertiserCurrency,omitempty"`
	CpcvInAdvertiserCurrency    *float64 `json:"cpcvInAdvertiserCurrency,omitempty"`
	MiaozhenOTPInPercent        *float64 `json:"miaozhenOTPInPercent,omitempty"`
}

func (o *AdGroupWorkflowROIGoalInput) GetMaximizeReach() *bool {
	if o == nil {
		return nil
	}
	return o.MaximizeReach
}

func (o *AdGroupWorkflowROIGoalInput) GetMaximizeLtvIncrementalReach() *bool {
	if o == nil {
		return nil
	}
	return o.MaximizeLtvIncrementalReach
}

func (o *AdGroupWorkflowROIGoalInput) GetCpcInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.CpcInAdvertiserCurrency
}

func (o *AdGroupWorkflowROIGoalInput) GetCtrInPercent() *float64 {
	if o == nil {
		return nil
	}
	return o.CtrInPercent
}

func (o *AdGroupWorkflowROIGoalInput) GetNielsenOTPInPercent() *float64 {
	if o == nil {
		return nil
	}
	return o.NielsenOTPInPercent
}

func (o *AdGroupWorkflowROIGoalInput) GetCpaInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.CpaInAdvertiserCurrency
}

func (o *AdGroupWorkflowROIGoalInput) GetReturnOnAdSpendPercent() *float64 {
	if o == nil {
		return nil
	}
	return o.ReturnOnAdSpendPercent
}

func (o *AdGroupWorkflowROIGoalInput) GetVcrInPercent() *float64 {
	if o == nil {
		return nil
	}
	return o.VcrInPercent
}

func (o *AdGroupWorkflowROIGoalInput) GetViewabilityInPercent() *float64 {
	if o == nil {
		return nil
	}
	return o.ViewabilityInPercent
}

func (o *AdGroupWorkflowROIGoalInput) GetVcpmInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.VcpmInAdvertiserCurrency
}

func (o *AdGroupWorkflowROIGoalInput) GetCpcvInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.CpcvInAdvertiserCurrency
}

func (o *AdGroupWorkflowROIGoalInput) GetMiaozhenOTPInPercent() *float64 {
	if o == nil {
		return nil
	}
	return o.MiaozhenOTPInPercent
}
