// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowComscoreSettingsInput struct {
	IsEnabled                  bool  `json:"isEnabled"`
	PopulationID               *int  `json:"populationId,omitempty"`
	DemographicMemberIds       []int `json:"demographicMemberIds,omitempty"`
	MobileDemographicMemberIds []int `json:"mobileDemographicMemberIds,omitempty"`
}

func (o *AdGroupWorkflowComscoreSettingsInput) GetIsEnabled() bool {
	if o == nil {
		return false
	}
	return o.IsEnabled
}

func (o *AdGroupWorkflowComscoreSettingsInput) GetPopulationID() *int {
	if o == nil {
		return nil
	}
	return o.PopulationID
}

func (o *AdGroupWorkflowComscoreSettingsInput) GetDemographicMemberIds() []int {
	if o == nil {
		return nil
	}
	return o.DemographicMemberIds
}

func (o *AdGroupWorkflowComscoreSettingsInput) GetMobileDemographicMemberIds() []int {
	if o == nil {
		return nil
	}
	return o.MobileDemographicMemberIds
}
