// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupBulkCreateWorkflowInputWithValidation struct {
	Input             []AdGroupCreateWorkflowInput `json:"input"`
	ValidateInputOnly *bool                        `json:"validateInputOnly,omitempty"`
	CallbackInput     *WorkflowCallbackInput       `json:"callbackInput,omitempty"`
}

func (a *AdGroupBulkCreateWorkflowInputWithValidation) GetInput() []AdGroupCreateWorkflowInput {
	if a == nil {
		return nil
	}
	return a.Input
}

func (a *AdGroupBulkCreateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if a == nil {
		return nil
	}
	return a.ValidateInputOnly
}

func (a *AdGroupBulkCreateWorkflowInputWithValidation) GetCallbackInput() *WorkflowCallbackInput {
	if a == nil {
		return nil
	}
	return a.CallbackInput
}
