// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupBulkUpdateWorkflowInputWithValidation struct {
	Input             []AdGroupUpdateWorkflowInput `json:"input"`
	ValidateInputOnly *bool                        `json:"validateInputOnly,omitempty"`
	CallbackInput     *WorkflowCallbackInput       `json:"callbackInput,omitempty"`
}

func (a *AdGroupBulkUpdateWorkflowInputWithValidation) GetInput() []AdGroupUpdateWorkflowInput {
	if a == nil {
		return nil
	}
	return a.Input
}

func (a *AdGroupBulkUpdateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if a == nil {
		return nil
	}
	return a.ValidateInputOnly
}

func (a *AdGroupBulkUpdateWorkflowInputWithValidation) GetCallbackInput() *WorkflowCallbackInput {
	if a == nil {
		return nil
	}
	return a.CallbackInput
}
