// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupComscoreSettings struct {
	IsEnabled                  bool  `json:"isEnabled"`
	PopulationID               *int  `json:"populationId,omitempty"`
	DemographicMemberIds       []int `json:"demographicMemberIds"`
	MobileDemographicMemberIds []int `json:"mobileDemographicMemberIds"`
}

func (a *AdGroupComscoreSettings) GetIsEnabled() bool {
	if a == nil {
		return false
	}
	return a.IsEnabled
}

func (a *AdGroupComscoreSettings) GetPopulationID() *int {
	if a == nil {
		return nil
	}
	return a.PopulationID
}

func (a *AdGroupComscoreSettings) GetDemographicMemberIds() []int {
	if a == nil {
		return nil
	}
	return a.DemographicMemberIds
}

func (a *AdGroupComscoreSettings) GetMobileDemographicMemberIds() []int {
	if a == nil {
		return nil
	}
	return a.MobileDemographicMemberIds
}
