// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowInventoryTargetingInput struct {
	DealGroupIdsToInclude []string `json:"dealGroupIdsToInclude,omitempty"`
	DealGroupIdsToExclude []string `json:"dealGroupIdsToExclude,omitempty"`
	DealIdsToExclude      []int64  `json:"dealIdsToExclude,omitempty"`
	DealIdsToInclude      []int64  `json:"dealIdsToInclude,omitempty"`
	IncludeDefaultOnDeals *bool    `json:"includeDefaultOnDeals,omitempty"`
}

func (a *AdGroupWorkflowInventoryTargetingInput) GetDealGroupIdsToInclude() []string {
	if a == nil {
		return nil
	}
	return a.DealGroupIdsToInclude
}

func (a *AdGroupWorkflowInventoryTargetingInput) GetDealGroupIdsToExclude() []string {
	if a == nil {
		return nil
	}
	return a.DealGroupIdsToExclude
}

func (a *AdGroupWorkflowInventoryTargetingInput) GetDealIdsToExclude() []int64 {
	if a == nil {
		return nil
	}
	return a.DealIdsToExclude
}

func (a *AdGroupWorkflowInventoryTargetingInput) GetDealIdsToInclude() []int64 {
	if a == nil {
		return nil
	}
	return a.DealIdsToInclude
}

func (a *AdGroupWorkflowInventoryTargetingInput) GetIncludeDefaultOnDeals() *bool {
	if a == nil {
		return nil
	}
	return a.IncludeDefaultOnDeals
}
