// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupContractTargeting struct {
	AllowOpenMarketBiddingWhenTargetingContracts bool `json:"allowOpenMarketBiddingWhenTargetingContracts"`
}

func (a *AdGroupContractTargeting) GetAllowOpenMarketBiddingWhenTargetingContracts() bool {
	if a == nil {
		return false
	}
	return a.AllowOpenMarketBiddingWhenTargetingContracts
}
