// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupUpdateWorkflowInputWithValidation struct {
	ID                *string                            `json:"id"`
	PrimaryInput      *AdGroupUpdateWorkflowPrimaryInput `json:"primaryInput,omitempty"`
	AdvancedInput     *AdGroupWorkflowAdvancedInput      `json:"advancedInput,omitempty"`
	ValidateInputOnly *bool                              `json:"validateInputOnly,omitempty"`
}

func (o *AdGroupUpdateWorkflowInputWithValidation) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AdGroupUpdateWorkflowInputWithValidation) GetPrimaryInput() *AdGroupUpdateWorkflowPrimaryInput {
	if o == nil {
		return nil
	}
	return o.PrimaryInput
}

func (o *AdGroupUpdateWorkflowInputWithValidation) GetAdvancedInput() *AdGroupWorkflowAdvancedInput {
	if o == nil {
		return nil
	}
	return o.AdvancedInput
}

func (o *AdGroupUpdateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if o == nil {
		return nil
	}
	return o.ValidateInputOnly
}
