// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupCreateWorkflowPrimaryInput struct {
	IsEnabled                               *bool                                  `json:"isEnabled,omitempty"`
	Description                             *string                                `json:"description,omitempty"`
	Budget                                  *AdGroupWorkflowBudgetInput            `json:"budget,omitempty"`
	BaseBidCPMInAdvertiserCurrency          *float64                               `json:"baseBidCPMInAdvertiserCurrency,omitempty"`
	MaxBidCPMInAdvertiserCurrency           *float64                               `json:"maxBidCPMInAdvertiserCurrency,omitempty"`
	AudienceTargeting                       *AdGroupWorkflowAudienceTargetingInput `json:"audienceTargeting,omitempty"`
	RoiGoal                                 *AdGroupWorkflowROIGoalInput           `json:"roiGoal,omitempty"`
	CreativeIds                             []string                               `json:"creativeIds,omitempty"`
	AssociatedBidLists                      []AdGroupWorkflowAssociateBidListInput `json:"associatedBidLists,omitempty"`
	Name                                    *string                                `json:"name"`
	Channel                                 AdGroupChannel                         `json:"channel"`
	FunnelLocation                          AdGroupFunnelLocation                  `json:"funnelLocation"`
	ProgrammaticGuaranteedPrivateContractID *string                                `json:"programmaticGuaranteedPrivateContractId,omitempty"`
}

func (a *AdGroupCreateWorkflowPrimaryInput) GetIsEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.IsEnabled
}

func (a *AdGroupCreateWorkflowPrimaryInput) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AdGroupCreateWorkflowPrimaryInput) GetBudget() *AdGroupWorkflowBudgetInput {
	if a == nil {
		return nil
	}
	return a.Budget
}

func (a *AdGroupCreateWorkflowPrimaryInput) GetBaseBidCPMInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.BaseBidCPMInAdvertiserCurrency
}

func (a *AdGroupCreateWorkflowPrimaryInput) GetMaxBidCPMInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.MaxBidCPMInAdvertiserCurrency
}

func (a *AdGroupCreateWorkflowPrimaryInput) GetAudienceTargeting() *AdGroupWorkflowAudienceTargetingInput {
	if a == nil {
		return nil
	}
	return a.AudienceTargeting
}

func (a *AdGroupCreateWorkflowPrimaryInput) GetRoiGoal() *AdGroupWorkflowROIGoalInput {
	if a == nil {
		return nil
	}
	return a.RoiGoal
}

func (a *AdGroupCreateWorkflowPrimaryInput) GetCreativeIds() []string {
	if a == nil {
		return nil
	}
	return a.CreativeIds
}

func (a *AdGroupCreateWorkflowPrimaryInput) GetAssociatedBidLists() []AdGroupWorkflowAssociateBidListInput {
	if a == nil {
		return nil
	}
	return a.AssociatedBidLists
}

func (a *AdGroupCreateWorkflowPrimaryInput) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AdGroupCreateWorkflowPrimaryInput) GetChannel() AdGroupChannel {
	if a == nil {
		return AdGroupChannel("")
	}
	return a.Channel
}

func (a *AdGroupCreateWorkflowPrimaryInput) GetFunnelLocation() AdGroupFunnelLocation {
	if a == nil {
		return AdGroupFunnelLocation("")
	}
	return a.FunnelLocation
}

func (a *AdGroupCreateWorkflowPrimaryInput) GetProgrammaticGuaranteedPrivateContractID() *string {
	if a == nil {
		return nil
	}
	return a.ProgrammaticGuaranteedPrivateContractID
}
