// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupUpdateWorkflowInput struct {
	ID            *string                            `json:"id"`
	PrimaryInput  *AdGroupUpdateWorkflowPrimaryInput `json:"primaryInput,omitempty"`
	AdvancedInput *AdGroupWorkflowAdvancedInput      `json:"advancedInput,omitempty"`
}

func (o *AdGroupUpdateWorkflowInput) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AdGroupUpdateWorkflowInput) GetPrimaryInput() *AdGroupUpdateWorkflowPrimaryInput {
	if o == nil {
		return nil
	}
	return o.PrimaryInput
}

func (o *AdGroupUpdateWorkflowInput) GetAdvancedInput() *AdGroupWorkflowAdvancedInput {
	if o == nil {
		return nil
	}
	return o.AdvancedInput
}
