// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupBudget struct {
	AllocationType                  AllocationType `json:"allocationType"`
	BudgetInAdvertiserCurrency      float64        `json:"budgetInAdvertiserCurrency"`
	BudgetInImpressions             *int64         `json:"budgetInImpressions,omitempty"`
	DailyTargetInAdvertiserCurrency *float64       `json:"dailyTargetInAdvertiserCurrency,omitempty"`
	DailyTargetInImpressions        *int64         `json:"dailyTargetInImpressions,omitempty"`
}

func (a *AdGroupBudget) GetAllocationType() AllocationType {
	if a == nil {
		return AllocationType("")
	}
	return a.AllocationType
}

func (a *AdGroupBudget) GetBudgetInAdvertiserCurrency() float64 {
	if a == nil {
		return 0.0
	}
	return a.BudgetInAdvertiserCurrency
}

func (a *AdGroupBudget) GetBudgetInImpressions() *int64 {
	if a == nil {
		return nil
	}
	return a.BudgetInImpressions
}

func (a *AdGroupBudget) GetDailyTargetInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.DailyTargetInAdvertiserCurrency
}

func (a *AdGroupBudget) GetDailyTargetInImpressions() *int64 {
	if a == nil {
		return nil
	}
	return a.DailyTargetInImpressions
}
