// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupCreateWorkflowInputWithValidation struct {
	PrimaryInput      AdGroupCreateWorkflowPrimaryInput `json:"primaryInput"`
	CampaignID        *string                           `json:"campaignId"`
	AdvancedInput     *AdGroupWorkflowAdvancedInput     `json:"advancedInput,omitempty"`
	ValidateInputOnly *bool                             `json:"validateInputOnly,omitempty"`
}

func (a *AdGroupCreateWorkflowInputWithValidation) GetPrimaryInput() AdGroupCreateWorkflowPrimaryInput {
	if a == nil {
		return AdGroupCreateWorkflowPrimaryInput{}
	}
	return a.PrimaryInput
}

func (a *AdGroupCreateWorkflowInputWithValidation) GetCampaignID() *string {
	if a == nil {
		return nil
	}
	return a.CampaignID
}

func (a *AdGroupCreateWorkflowInputWithValidation) GetAdvancedInput() *AdGroupWorkflowAdvancedInput {
	if a == nil {
		return nil
	}
	return a.AdvancedInput
}

func (a *AdGroupCreateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if a == nil {
		return nil
	}
	return a.ValidateInputOnly
}
