// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowNielsenTrackingAttributesInput struct {
	EnhancedReportingOption *EnhancedNielsenReportingOptions `json:"enhancedReportingOption,omitempty"`
	Gender                  TargetingGender                  `json:"gender"`
	StartAge                TargetingStartAge                `json:"startAge"`
	EndAge                  TargetingEndAge                  `json:"endAge"`
	Countries               []string                         `json:"countries"`
}

func (o *AdGroupWorkflowNielsenTrackingAttributesInput) GetEnhancedReportingOption() *EnhancedNielsenReportingOptions {
	if o == nil {
		return nil
	}
	return o.EnhancedReportingOption
}

func (o *AdGroupWorkflowNielsenTrackingAttributesInput) GetGender() TargetingGender {
	if o == nil {
		return TargetingGender("")
	}
	return o.Gender
}

func (o *AdGroupWorkflowNielsenTrackingAttributesInput) GetStartAge() TargetingStartAge {
	if o == nil {
		return TargetingStartAge("")
	}
	return o.StartAge
}

func (o *AdGroupWorkflowNielsenTrackingAttributesInput) GetEndAge() TargetingEndAge {
	if o == nil {
		return TargetingEndAge("")
	}
	return o.EndAge
}

func (o *AdGroupWorkflowNielsenTrackingAttributesInput) GetCountries() []string {
	if o == nil {
		return nil
	}
	return o.Countries
}
