// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflow struct {
	ID                                         *string                           `json:"id"`
	Name                                       *string                           `json:"name"`
	CampaignID                                 *string                           `json:"campaignId"`
	IsEnabled                                  bool                              `json:"isEnabled"`
	Description                                *string                           `json:"description,omitempty"`
	ProgrammaticGuaranteedPrivateContractID    *string                           `json:"programmaticGuaranteedPrivateContractId,omitempty"`
	Channel                                    AdGroupChannel                    `json:"channel"`
	FunnelLocation                             AdGroupFunnelLocation             `json:"funnelLocation"`
	Budget                                     AdGroupBudget                     `json:"budget"`
	BaseBidCPMInAdvertiserCurrency             *float64                          `json:"baseBidCPMInAdvertiserCurrency,omitempty"`
	MaxBidCPMInAdvertiserCurrency              *float64                          `json:"maxBidCPMInAdvertiserCurrency,omitempty"`
	MarketType                                 *MarketType                       `json:"marketType,omitempty"`
	AudienceTargeting                          *AdGroupAudienceTargeting         `json:"audienceTargeting,omitempty"`
	RoiGoal                                    AdGroupROIGoal                    `json:"roiGoal"`
	CreativeIds                                []string                          `json:"creativeIds"`
	AssociatedBidLists                         []AdGroupAssociateBidList         `json:"associatedBidLists"`
	Flights                                    []AdGroupFlight                   `json:"flights"`
	KoaOptimizationSettings                    *AdGroupKoaOptimizationSettings   `json:"koaOptimizationSettings,omitempty"`
	ComscoreSettings                           AdGroupComscoreSettings           `json:"comscoreSettings"`
	ContractTargeting                          AdGroupContractTargeting          `json:"contractTargeting"`
	DimensionalBiddingAutoOptimizationSettings [][]DimensionalBiddingDimensions  `json:"dimensionalBiddingAutoOptimizationSettings"`
	IsUseClicksAsConversionsEnabled            bool                              `json:"isUseClicksAsConversionsEnabled"`
	IsUseSecondaryConversionsEnabled           bool                              `json:"isUseSecondaryConversionsEnabled"`
	NielsenTrackingAttributes                  *AdGroupNielsenTrackingAttributes `json:"nielsenTrackingAttributes,omitempty"`
}

func (a *AdGroupWorkflow) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AdGroupWorkflow) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AdGroupWorkflow) GetCampaignID() *string {
	if a == nil {
		return nil
	}
	return a.CampaignID
}

func (a *AdGroupWorkflow) GetIsEnabled() bool {
	if a == nil {
		return false
	}
	return a.IsEnabled
}

func (a *AdGroupWorkflow) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AdGroupWorkflow) GetProgrammaticGuaranteedPrivateContractID() *string {
	if a == nil {
		return nil
	}
	return a.ProgrammaticGuaranteedPrivateContractID
}

func (a *AdGroupWorkflow) GetChannel() AdGroupChannel {
	if a == nil {
		return AdGroupChannel("")
	}
	return a.Channel
}

func (a *AdGroupWorkflow) GetFunnelLocation() AdGroupFunnelLocation {
	if a == nil {
		return AdGroupFunnelLocation("")
	}
	return a.FunnelLocation
}

func (a *AdGroupWorkflow) GetBudget() AdGroupBudget {
	if a == nil {
		return AdGroupBudget{}
	}
	return a.Budget
}

func (a *AdGroupWorkflow) GetBaseBidCPMInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.BaseBidCPMInAdvertiserCurrency
}

func (a *AdGroupWorkflow) GetMaxBidCPMInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.MaxBidCPMInAdvertiserCurrency
}

func (a *AdGroupWorkflow) GetMarketType() *MarketType {
	if a == nil {
		return nil
	}
	return a.MarketType
}

func (a *AdGroupWorkflow) GetAudienceTargeting() *AdGroupAudienceTargeting {
	if a == nil {
		return nil
	}
	return a.AudienceTargeting
}

func (a *AdGroupWorkflow) GetRoiGoal() AdGroupROIGoal {
	if a == nil {
		return AdGroupROIGoal{}
	}
	return a.RoiGoal
}

func (a *AdGroupWorkflow) GetCreativeIds() []string {
	if a == nil {
		return nil
	}
	return a.CreativeIds
}

func (a *AdGroupWorkflow) GetAssociatedBidLists() []AdGroupAssociateBidList {
	if a == nil {
		return nil
	}
	return a.AssociatedBidLists
}

func (a *AdGroupWorkflow) GetFlights() []AdGroupFlight {
	if a == nil {
		return nil
	}
	return a.Flights
}

func (a *AdGroupWorkflow) GetKoaOptimizationSettings() *AdGroupKoaOptimizationSettings {
	if a == nil {
		return nil
	}
	return a.KoaOptimizationSettings
}

func (a *AdGroupWorkflow) GetComscoreSettings() AdGroupComscoreSettings {
	if a == nil {
		return AdGroupComscoreSettings{}
	}
	return a.ComscoreSettings
}

func (a *AdGroupWorkflow) GetContractTargeting() AdGroupContractTargeting {
	if a == nil {
		return AdGroupContractTargeting{}
	}
	return a.ContractTargeting
}

func (a *AdGroupWorkflow) GetDimensionalBiddingAutoOptimizationSettings() [][]DimensionalBiddingDimensions {
	if a == nil {
		return nil
	}
	return a.DimensionalBiddingAutoOptimizationSettings
}

func (a *AdGroupWorkflow) GetIsUseClicksAsConversionsEnabled() bool {
	if a == nil {
		return false
	}
	return a.IsUseClicksAsConversionsEnabled
}

func (a *AdGroupWorkflow) GetIsUseSecondaryConversionsEnabled() bool {
	if a == nil {
		return false
	}
	return a.IsUseSecondaryConversionsEnabled
}

func (a *AdGroupWorkflow) GetNielsenTrackingAttributes() *AdGroupNielsenTrackingAttributes {
	if a == nil {
		return nil
	}
	return a.NielsenTrackingAttributes
}
