// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupKoaOptimizationSettings struct {
	AreFutureKoaFeaturesEnabled *bool `json:"areFutureKoaFeaturesEnabled,omitempty"`
	PredictiveClearingEnabled   *bool `json:"predictiveClearingEnabled,omitempty"`
}

func (o *AdGroupKoaOptimizationSettings) GetAreFutureKoaFeaturesEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.AreFutureKoaFeaturesEnabled
}

func (o *AdGroupKoaOptimizationSettings) GetPredictiveClearingEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.PredictiveClearingEnabled
}
