// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowKoaOptimizationSettingsInput struct {
	AreFutureKoaFeaturesEnabled *bool `json:"areFutureKoaFeaturesEnabled,omitempty"`
	PredictiveClearingEnabled   *bool `json:"predictiveClearingEnabled,omitempty"`
}

func (o *AdGroupWorkflowKoaOptimizationSettingsInput) GetAreFutureKoaFeaturesEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.AreFutureKoaFeaturesEnabled
}

func (o *AdGroupWorkflowKoaOptimizationSettingsInput) GetPredictiveClearingEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.PredictiveClearingEnabled
}
