// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowAdvancedInput struct {
	KoaOptimizationSettings                    *AdGroupWorkflowKoaOptimizationSettingsInput   `json:"koaOptimizationSettings,omitempty"`
	ComscoreSettings                           *AdGroupWorkflowComscoreSettingsInput          `json:"comscoreSettings,omitempty"`
	ContractTargeting                          *AdGroupWorkflowContractTargetingInput         `json:"contractTargeting,omitempty"`
	DimensionalBiddingAutoOptimizationSettings [][]DimensionalBiddingDimensions               `json:"dimensionalBiddingAutoOptimizationSettings,omitempty"`
	IsUseClicksAsConversionsEnabled            *bool                                          `json:"isUseClicksAsConversionsEnabled,omitempty"`
	IsUseSecondaryConversionsEnabled           *bool                                          `json:"isUseSecondaryConversionsEnabled,omitempty"`
	NielsenTrackingAttributes                  *AdGroupWorkflowNielsenTrackingAttributesInput `json:"nielsenTrackingAttributes,omitempty"`
	NewFrequencyConfigs                        []AdGroupWorkflowNewFrequencyConfigInput       `json:"newFrequencyConfigs,omitempty"`
	InventoryTargeting                         *AdGroupWorkflowInventoryTargetingInput        `json:"inventoryTargeting,omitempty"`
	IsNonDecisioned                            *bool                                          `json:"isNonDecisioned,omitempty"`
	Flights                                    []AdGroupWorkflowFlightInput                   `json:"flights,omitempty"`
	CallerSource                               *string                                        `json:"callerSource,omitempty"`
}

func (a *AdGroupWorkflowAdvancedInput) GetKoaOptimizationSettings() *AdGroupWorkflowKoaOptimizationSettingsInput {
	if a == nil {
		return nil
	}
	return a.KoaOptimizationSettings
}

func (a *AdGroupWorkflowAdvancedInput) GetComscoreSettings() *AdGroupWorkflowComscoreSettingsInput {
	if a == nil {
		return nil
	}
	return a.ComscoreSettings
}

func (a *AdGroupWorkflowAdvancedInput) GetContractTargeting() *AdGroupWorkflowContractTargetingInput {
	if a == nil {
		return nil
	}
	return a.ContractTargeting
}

func (a *AdGroupWorkflowAdvancedInput) GetDimensionalBiddingAutoOptimizationSettings() [][]DimensionalBiddingDimensions {
	if a == nil {
		return nil
	}
	return a.DimensionalBiddingAutoOptimizationSettings
}

func (a *AdGroupWorkflowAdvancedInput) GetIsUseClicksAsConversionsEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.IsUseClicksAsConversionsEnabled
}

func (a *AdGroupWorkflowAdvancedInput) GetIsUseSecondaryConversionsEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.IsUseSecondaryConversionsEnabled
}

func (a *AdGroupWorkflowAdvancedInput) GetNielsenTrackingAttributes() *AdGroupWorkflowNielsenTrackingAttributesInput {
	if a == nil {
		return nil
	}
	return a.NielsenTrackingAttributes
}

func (a *AdGroupWorkflowAdvancedInput) GetNewFrequencyConfigs() []AdGroupWorkflowNewFrequencyConfigInput {
	if a == nil {
		return nil
	}
	return a.NewFrequencyConfigs
}

func (a *AdGroupWorkflowAdvancedInput) GetInventoryTargeting() *AdGroupWorkflowInventoryTargetingInput {
	if a == nil {
		return nil
	}
	return a.InventoryTargeting
}

func (a *AdGroupWorkflowAdvancedInput) GetIsNonDecisioned() *bool {
	if a == nil {
		return nil
	}
	return a.IsNonDecisioned
}

func (a *AdGroupWorkflowAdvancedInput) GetFlights() []AdGroupWorkflowFlightInput {
	if a == nil {
		return nil
	}
	return a.Flights
}

func (a *AdGroupWorkflowAdvancedInput) GetCallerSource() *string {
	if a == nil {
		return nil
	}
	return a.CallerSource
}
