// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupKoaOptimizationSettings struct {
	AreFutureKoaFeaturesEnabled *bool `json:"areFutureKoaFeaturesEnabled,omitempty"`
	PredictiveClearingEnabled   *bool `json:"predictiveClearingEnabled,omitempty"`
}

func (a *AdGroupKoaOptimizationSettings) GetAreFutureKoaFeaturesEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.AreFutureKoaFeaturesEnabled
}

func (a *AdGroupKoaOptimizationSettings) GetPredictiveClearingEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.PredictiveClearingEnabled
}
