// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowContractTargetingInput struct {
	AllowOpenMarketBiddingWhenTargetingContracts *bool `json:"allowOpenMarketBiddingWhenTargetingContracts,omitempty"`
}

func (o *AdGroupWorkflowContractTargetingInput) GetAllowOpenMarketBiddingWhenTargetingContracts() *bool {
	if o == nil {
		return nil
	}
	return o.AllowOpenMarketBiddingWhenTargetingContracts
}
