// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowAudienceTargetingInput struct {
	AudienceID                           *string `json:"audienceId,omitempty"`
	AudienceAcceleratorExclusionsEnabled *bool   `json:"audienceAcceleratorExclusionsEnabled,omitempty"`
	AudienceBoosterEnabled               *bool   `json:"audienceBoosterEnabled,omitempty"`
	AudienceExcluderEnabled              *bool   `json:"audienceExcluderEnabled,omitempty"`
	AudiencePredictorEnabled             *bool   `json:"audiencePredictorEnabled,omitempty"`
	CrossDeviceVendorListForAudience     []int   `json:"crossDeviceVendorListForAudience,omitempty"`
	RecencyExclusionWindowInMinutes      *int    `json:"recencyExclusionWindowInMinutes,omitempty"`
	TargetTrackableUsersEnabled          *bool   `json:"targetTrackableUsersEnabled,omitempty"`
	UseMcIDAsPrimary                     *bool   `json:"useMcIdAsPrimary,omitempty"`
}

func (o *AdGroupWorkflowAudienceTargetingInput) GetAudienceID() *string {
	if o == nil {
		return nil
	}
	return o.AudienceID
}

func (o *AdGroupWorkflowAudienceTargetingInput) GetAudienceAcceleratorExclusionsEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.AudienceAcceleratorExclusionsEnabled
}

func (o *AdGroupWorkflowAudienceTargetingInput) GetAudienceBoosterEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.AudienceBoosterEnabled
}

func (o *AdGroupWorkflowAudienceTargetingInput) GetAudienceExcluderEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.AudienceExcluderEnabled
}

func (o *AdGroupWorkflowAudienceTargetingInput) GetAudiencePredictorEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.AudiencePredictorEnabled
}

func (o *AdGroupWorkflowAudienceTargetingInput) GetCrossDeviceVendorListForAudience() []int {
	if o == nil {
		return nil
	}
	return o.CrossDeviceVendorListForAudience
}

func (o *AdGroupWorkflowAudienceTargetingInput) GetRecencyExclusionWindowInMinutes() *int {
	if o == nil {
		return nil
	}
	return o.RecencyExclusionWindowInMinutes
}

func (o *AdGroupWorkflowAudienceTargetingInput) GetTargetTrackableUsersEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.TargetTrackableUsersEnabled
}

func (o *AdGroupWorkflowAudienceTargetingInput) GetUseMcIDAsPrimary() *bool {
	if o == nil {
		return nil
	}
	return o.UseMcIDAsPrimary
}
