// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupBudget struct {
	AllocationType                  AllocationType `json:"allocationType"`
	BudgetInAdvertiserCurrency      float64        `json:"budgetInAdvertiserCurrency"`
	BudgetInImpressions             *int64         `json:"budgetInImpressions,omitempty"`
	DailyTargetInAdvertiserCurrency *float64       `json:"dailyTargetInAdvertiserCurrency,omitempty"`
	DailyTargetInImpressions        *int64         `json:"dailyTargetInImpressions,omitempty"`
}

func (o *AdGroupBudget) GetAllocationType() AllocationType {
	if o == nil {
		return AllocationType("")
	}
	return o.AllocationType
}

func (o *AdGroupBudget) GetBudgetInAdvertiserCurrency() float64 {
	if o == nil {
		return 0.0
	}
	return o.BudgetInAdvertiserCurrency
}

func (o *AdGroupBudget) GetBudgetInImpressions() *int64 {
	if o == nil {
		return nil
	}
	return o.BudgetInImpressions
}

func (o *AdGroupBudget) GetDailyTargetInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.DailyTargetInAdvertiserCurrency
}

func (o *AdGroupBudget) GetDailyTargetInImpressions() *int64 {
	if o == nil {
		return nil
	}
	return o.DailyTargetInImpressions
}
