// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type AdGroupFunnelLocation string

const (
	AdGroupFunnelLocationNone          AdGroupFunnelLocation = "None"
	AdGroupFunnelLocationAwareness     AdGroupFunnelLocation = "Awareness"
	AdGroupFunnelLocationConsideration AdGroupFunnelLocation = "Consideration"
	AdGroupFunnelLocationConversion    AdGroupFunnelLocation = "Conversion"
)

func (e AdGroupFunnelLocation) ToPointer() *AdGroupFunnelLocation {
	return &e
}
func (e *AdGroupFunnelLocation) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "None":
		fallthrough
	case "Awareness":
		fallthrough
	case "Consideration":
		fallthrough
	case "Conversion":
		*e = AdGroupFunnelLocation(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AdGroupFunnelLocation: %v", v)
	}
}
