// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowComscoreSettingsInput struct {
	IsEnabled                  bool  `json:"isEnabled"`
	PopulationID               *int  `json:"populationId,omitempty"`
	DemographicMemberIds       []int `json:"demographicMemberIds,omitempty"`
	MobileDemographicMemberIds []int `json:"mobileDemographicMemberIds,omitempty"`
}

func (a *AdGroupWorkflowComscoreSettingsInput) GetIsEnabled() bool {
	if a == nil {
		return false
	}
	return a.IsEnabled
}

func (a *AdGroupWorkflowComscoreSettingsInput) GetPopulationID() *int {
	if a == nil {
		return nil
	}
	return a.PopulationID
}

func (a *AdGroupWorkflowComscoreSettingsInput) GetDemographicMemberIds() []int {
	if a == nil {
		return nil
	}
	return a.DemographicMemberIds
}

func (a *AdGroupWorkflowComscoreSettingsInput) GetMobileDemographicMemberIds() []int {
	if a == nil {
		return nil
	}
	return a.MobileDemographicMemberIds
}
