// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowFlightInput struct {
	AllocationType                  *AllocationType `json:"allocationType,omitempty"`
	BudgetInAdvertiserCurrency      *float64        `json:"budgetInAdvertiserCurrency,omitempty"`
	BudgetInImpressions             *int64          `json:"budgetInImpressions,omitempty"`
	DailyTargetInAdvertiserCurrency *float64        `json:"dailyTargetInAdvertiserCurrency,omitempty"`
	DailyTargetInImpressions        *int64          `json:"dailyTargetInImpressions,omitempty"`
	CampaignFlightID                int64           `json:"campaignFlightId"`
}

func (a *AdGroupWorkflowFlightInput) GetAllocationType() *AllocationType {
	if a == nil {
		return nil
	}
	return a.AllocationType
}

func (a *AdGroupWorkflowFlightInput) GetBudgetInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.BudgetInAdvertiserCurrency
}

func (a *AdGroupWorkflowFlightInput) GetBudgetInImpressions() *int64 {
	if a == nil {
		return nil
	}
	return a.BudgetInImpressions
}

func (a *AdGroupWorkflowFlightInput) GetDailyTargetInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.DailyTargetInAdvertiserCurrency
}

func (a *AdGroupWorkflowFlightInput) GetDailyTargetInImpressions() *int64 {
	if a == nil {
		return nil
	}
	return a.DailyTargetInImpressions
}

func (a *AdGroupWorkflowFlightInput) GetCampaignFlightID() int64 {
	if a == nil {
		return 0
	}
	return a.CampaignFlightID
}
