// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowKoaOptimizationSettingsInput struct {
	AreFutureKoaFeaturesEnabled *bool `json:"areFutureKoaFeaturesEnabled,omitempty"`
	PredictiveClearingEnabled   *bool `json:"predictiveClearingEnabled,omitempty"`
}

func (a *AdGroupWorkflowKoaOptimizationSettingsInput) GetAreFutureKoaFeaturesEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.AreFutureKoaFeaturesEnabled
}

func (a *AdGroupWorkflowKoaOptimizationSettingsInput) GetPredictiveClearingEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.PredictiveClearingEnabled
}
