// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdGroupWorkflowBudgetInput struct {
	AllocationType                  *AllocationType `json:"allocationType,omitempty"`
	BudgetInAdvertiserCurrency      *float64        `json:"budgetInAdvertiserCurrency,omitempty"`
	BudgetInImpressions             *int64          `json:"budgetInImpressions,omitempty"`
	DailyTargetInAdvertiserCurrency *float64        `json:"dailyTargetInAdvertiserCurrency,omitempty"`
	DailyTargetInImpressions        *int64          `json:"dailyTargetInImpressions,omitempty"`
}

func (a *AdGroupWorkflowBudgetInput) GetAllocationType() *AllocationType {
	if a == nil {
		return nil
	}
	return a.AllocationType
}

func (a *AdGroupWorkflowBudgetInput) GetBudgetInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.BudgetInAdvertiserCurrency
}

func (a *AdGroupWorkflowBudgetInput) GetBudgetInImpressions() *int64 {
	if a == nil {
		return nil
	}
	return a.BudgetInImpressions
}

func (a *AdGroupWorkflowBudgetInput) GetDailyTargetInAdvertiserCurrency() *float64 {
	if a == nil {
		return nil
	}
	return a.DailyTargetInAdvertiserCurrency
}

func (a *AdGroupWorkflowBudgetInput) GetDailyTargetInImpressions() *int64 {
	if a == nil {
		return nil
	}
	return a.DailyTargetInImpressions
}
