// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type AdsTxtSellerType string

const (
	AdsTxtSellerTypeUnknown      AdsTxtSellerType = "Unknown"
	AdsTxtSellerTypeDirect       AdsTxtSellerType = "Direct"
	AdsTxtSellerTypeReseller     AdsTxtSellerType = "Reseller"
	AdsTxtSellerTypeUnauthorized AdsTxtSellerType = "Unauthorized"
)

func (e AdsTxtSellerType) ToPointer() *AdsTxtSellerType {
	return &e
}
func (e *AdsTxtSellerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Direct":
		fallthrough
	case "Reseller":
		fallthrough
	case "Unauthorized":
		*e = AdsTxtSellerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AdsTxtSellerType: %v", v)
	}
}
