// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type AllocationType string

const (
	AllocationTypeMinimum AllocationType = "Minimum"
	AllocationTypeFixed   AllocationType = "Fixed"
	AllocationTypeMaximum AllocationType = "Maximum"
)

func (e AllocationType) ToPointer() *AllocationType {
	return &e
}
func (e *AllocationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Minimum":
		fallthrough
	case "Fixed":
		fallthrough
	case "Maximum":
		*e = AllocationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AllocationType: %v", v)
	}
}
