// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type AtmosphericCondition string

const (
	AtmosphericConditionUnknown          AtmosphericCondition = "Unknown"
	AtmosphericConditionLow              AtmosphericCondition = "Low"
	AtmosphericConditionMedium           AtmosphericCondition = "Medium"
	AtmosphericConditionHigh             AtmosphericCondition = "High"
	AtmosphericConditionVeryHigh         AtmosphericCondition = "VeryHigh"
	AtmosphericConditionLowForecast      AtmosphericCondition = "LowForecast"
	AtmosphericConditionMediumForecast   AtmosphericCondition = "MediumForecast"
	AtmosphericConditionHighForecast     AtmosphericCondition = "HighForecast"
	AtmosphericConditionVeryHighForecast AtmosphericCondition = "VeryHighForecast"
)

func (e AtmosphericCondition) ToPointer() *AtmosphericCondition {
	return &e
}
func (e *AtmosphericCondition) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Low":
		fallthrough
	case "Medium":
		fallthrough
	case "High":
		fallthrough
	case "VeryHigh":
		fallthrough
	case "LowForecast":
		fallthrough
	case "MediumForecast":
		fallthrough
	case "HighForecast":
		fallthrough
	case "VeryHighForecast":
		*e = AtmosphericCondition(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AtmosphericCondition: %v", v)
	}
}
