// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type AudienceReachPercentageTier string

const (
	AudienceReachPercentageTierUnknown AudienceReachPercentageTier = "Unknown"
	AudienceReachPercentageTierTier1   AudienceReachPercentageTier = "Tier1"
	AudienceReachPercentageTierTier2   AudienceReachPercentageTier = "Tier2"
	AudienceReachPercentageTierTier3   AudienceReachPercentageTier = "Tier3"
	AudienceReachPercentageTierTier4   AudienceReachPercentageTier = "Tier4"
)

func (e AudienceReachPercentageTier) ToPointer() *AudienceReachPercentageTier {
	return &e
}
func (e *AudienceReachPercentageTier) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Tier1":
		fallthrough
	case "Tier2":
		fallthrough
	case "Tier3":
		fallthrough
	case "Tier4":
		*e = AudienceReachPercentageTier(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AudienceReachPercentageTier: %v", v)
	}
}
