// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type BidListDimension string

const (
	BidListDimensionHasAdFormatID                                  BidListDimension = "HasAdFormatId"
	BidListDimensionHasDomainFragmentID                            BidListDimension = "HasDomainFragmentId"
	BidListDimensionHasUniversalCategoryTaxonomyID                 BidListDimension = "HasUniversalCategoryTaxonomyId"
	BidListDimensionHasPlacementPositionRelativeToFoldID           BidListDimension = "HasPlacementPositionRelativeToFoldId"
	BidListDimensionHasAdvertiserTargetingDataID                   BidListDimension = "HasAdvertiserTargetingDataId"
	BidListDimensionHasBrowserID                                   BidListDimension = "HasBrowserId"
	BidListDimensionHasCarrierID                                   BidListDimension = "HasCarrierId"
	BidListDimensionHasMiaozhenPageQualityCategoryID               BidListDimension = "HasMiaozhenPageQualityCategoryId"
	BidListDimensionHasDeviceModelID                               BidListDimension = "HasDeviceModelId"
	BidListDimensionHasDeviceTypeID                                BidListDimension = "HasDeviceTypeId"
	BidListDimensionHasGeoSegmentID                                BidListDimension = "HasGeoSegmentId"
	BidListDimensionHasHourOfWeek                                  BidListDimension = "HasHourOfWeek"
	BidListDimensionHasLanguageID                                  BidListDimension = "HasLanguageId"
	BidListDimensionHasOsID                                        BidListDimension = "HasOsId"
	BidListDimensionHasMiaozhenVideoPageQualityCategoryID          BidListDimension = "HasMiaozhenVideoPageQualityCategoryId"
	BidListDimensionHasPrivateContractID                           BidListDimension = "HasPrivateContractId"
	BidListDimensionHasGrapeshotPredictsCategoryID                 BidListDimension = "HasGrapeshotPredictsCategoryId"
	BidListDimensionHasRecencyWindowInMinutes                      BidListDimension = "HasRecencyWindowInMinutes"
	BidListDimensionHasRenderingContextID                          BidListDimension = "HasRenderingContextId"
	BidListDimensionHasSupplyVendorID                              BidListDimension = "HasSupplyVendorId"
	BidListDimensionHasTemperatureBucketInCelsius                  BidListDimension = "HasTemperatureBucketInCelsius"
	BidListDimensionHasThirdPartyDataID                            BidListDimension = "HasThirdPartyDataId"
	BidListDimensionHasAdsTxtSellerTypeID                          BidListDimension = "HasAdsTxtSellerTypeId"
	BidListDimensionHasVideoMutedStateID                           BidListDimension = "HasVideoMutedStateId"
	BidListDimensionHasVideoPlaybackTypeID                         BidListDimension = "HasVideoPlaybackTypeId"
	BidListDimensionHasVideoPlayerSizeID                           BidListDimension = "HasVideoPlayerSizeId"
	BidListDimensionHasVideoQualityID                              BidListDimension = "HasVideoQualityId"
	BidListDimensionHasVideoSkippabilityID                         BidListDimension = "HasVideoSkippabilityId"
	BidListDimensionHasFactualProximityDataID                      BidListDimension = "HasFactualProximityDataId"
	BidListDimensionHasGrapeshotDisplayPageQualityCategoryID       BidListDimension = "HasGrapeshotDisplayPageQualityCategoryId"
	BidListDimensionHasImpressionPlacementID                       BidListDimension = "HasImpressionPlacementId"
	BidListDimensionHasVideoTruthScoreRange                        BidListDimension = "HasVideoTruthScoreRange"
	BidListDimensionHasVideoViewabilityScoreRange                  BidListDimension = "HasVideoViewabilityScoreRange"
	BidListDimensionHasDisplayViewabilityScoreRange                BidListDimension = "HasDisplayViewabilityScoreRange"
	BidListDimensionHasPeer39LanguageID                            BidListDimension = "HasPeer39LanguageId"
	BidListDimensionHasGrapeshotLanguageID                         BidListDimension = "HasGrapeshotLanguageId"
	BidListDimensionHasIntegralContextualCategoryID                BidListDimension = "HasIntegralContextualCategoryId"
	BidListDimensionHasPeer39ContextualCategoryID                  BidListDimension = "HasPeer39ContextualCategoryId"
	BidListDimensionHasGrapeshotContextualCategoryID               BidListDimension = "HasGrapeshotContextualCategoryId"
	BidListDimensionHasDoubleVerifyContextualCategoryID            BidListDimension = "HasDoubleVerifyContextualCategoryId"
	BidListDimensionHasGrapeshotVideoPageQualityCategoryID         BidListDimension = "HasGrapeshotVideoPageQualityCategoryId"
	BidListDimensionHasIntegralBrandSafetyCategoryID               BidListDimension = "HasIntegralBrandSafetyCategoryId"
	BidListDimensionHasIntegralVideoBrandSafetyCategoryID          BidListDimension = "HasIntegralVideoBrandSafetyCategoryId"
	BidListDimensionHasPeer39BrandSafetyCategoryID                 BidListDimension = "HasPeer39BrandSafetyCategoryId"
	BidListDimensionHasGrapeshotBrandSafetyCategoryID              BidListDimension = "HasGrapeshotBrandSafetyCategoryId"
	BidListDimensionHasDoubleVerifyBrandSafetyCategoryID           BidListDimension = "HasDoubleVerifyBrandSafetyCategoryId"
	BidListDimensionHasIntegralPageQualityCategoryID               BidListDimension = "HasIntegralPageQualityCategoryId"
	BidListDimensionHasIntegralVideoPageQualityCategoryID          BidListDimension = "HasIntegralVideoPageQualityCategoryId"
	BidListDimensionHasPeer39PageQualityCategoryID                 BidListDimension = "HasPeer39PageQualityCategoryId"
	BidListDimensionHasDoubleVerifyBotAvoidanceCategoryID          BidListDimension = "HasDoubleVerifyBotAvoidanceCategoryId"
	BidListDimensionHasContextualAppCategoryID                     BidListDimension = "HasContextualAppCategoryId"
	BidListDimensionHasPublisherID                                 BidListDimension = "HasPublisherId"
	BidListDimensionHasIntegralViewabilityCategoryID               BidListDimension = "HasIntegralViewabilityCategoryId"
	BidListDimensionHasIntegralVideoViewabilityCategoryID          BidListDimension = "HasIntegralVideoViewabilityCategoryId"
	BidListDimensionHasDoubleVerifyViewabilityCategoryID           BidListDimension = "HasDoubleVerifyViewabilityCategoryId"
	BidListDimensionHasDoubleVerifyVideoViewabilityCategoryID      BidListDimension = "HasDoubleVerifyVideoViewabilityCategoryId"
	BidListDimensionHasLegacyFrequencyAdjustmentID                 BidListDimension = "HasLegacyFrequencyAdjustmentId"
	BidListDimensionHasDoubleVerifyAuthenticBrandSafetyCategoryID  BidListDimension = "HasDoubleVerifyAuthenticBrandSafetyCategoryId"
	BidListDimensionHasPeer39ViewabilityCategoryID                 BidListDimension = "HasPeer39ViewabilityCategoryId"
	BidListDimensionHasVideoCompletionRateScoreRange               BidListDimension = "HasVideoCompletionRateScoreRange"
	BidListDimensionHasInternetConnectionTypeID                    BidListDimension = "HasInternetConnectionTypeId"
	BidListDimensionHasAdBugPageQualityCategoryID                  BidListDimension = "HasAdBugPageQualityCategoryId"
	BidListDimensionHasAdBugVideoPageQualityCategoryID             BidListDimension = "HasAdBugVideoPageQualityCategoryId"
	BidListDimensionHasRtbAsiaPageQualityCategoryID                BidListDimension = "HasRTBAsiaPageQualityCategoryId"
	BidListDimensionHasRtbAsiaVideoPageQualityCategoryID           BidListDimension = "HasRTBAsiaVideoPageQualityCategoryId"
	BidListDimensionHasTtdContextualCategoryID                     BidListDimension = "HasTTDContextualCategoryId"
	BidListDimensionHasSupplyPathOptimizationListID                BidListDimension = "HasSupplyPathOptimizationListId"
	BidListDimensionHasIntegralKeywordBlacklistCategoryID          BidListDimension = "HasIntegralKeywordBlacklistCategoryId"
	BidListDimensionHasMarketTypeID                                BidListDimension = "HasMarketTypeId"
	BidListDimensionHasContextualSupplyVendorGenreID               BidListDimension = "HasContextualSupplyVendorGenreId"
	BidListDimensionHasContextualSupplyVendorCategoryID            BidListDimension = "HasContextualSupplyVendorCategoryId"
	BidListDimensionHasGrapeshotViewabilityCategoryID              BidListDimension = "HasGrapeshotViewabilityCategoryId"
	BidListDimensionHasGrapeshotVideoViewabilityCategoryID         BidListDimension = "HasGrapeshotVideoViewabilityCategoryId"
	BidListDimensionHasWeatherConditionID                          BidListDimension = "HasWeatherConditionId"
	BidListDimensionHasFrequencyAdjustmentID                       BidListDimension = "HasFrequencyAdjustmentId"
	BidListDimensionHasSemasioContextualCategoryID                 BidListDimension = "HasSemasioContextualCategoryId"
	BidListDimensionHasSellerID                                    BidListDimension = "HasSellerId"
	BidListDimensionHasDigitalOutOfHomeVenueTypeID                 BidListDimension = "HasDigitalOutOfHomeVenueTypeId"
	BidListDimensionHasNativePlacementTypeID                       BidListDimension = "HasNativePlacementTypeId"
	BidListDimensionHasTtdNativeContextTypeID                      BidListDimension = "HasTTDNativeContextTypeId"
	BidListDimensionHasIdiosyncraticSegmentID                      BidListDimension = "HasIdiosyncraticSegmentId"
	BidListDimensionHasTencentPageQualityCategoryID                BidListDimension = "HasTencentPageQualityCategoryId"
	BidListDimensionHasDomainClassID                               BidListDimension = "HasDomainClassId"
	BidListDimensionHasGeofenceThirdPartyDataAndBrand              BidListDimension = "HasGeofenceThirdPartyDataAndBrand"
	BidListDimensionHasGenreID                                     BidListDimension = "HasGenreId"
	BidListDimensionHasLivestreamID                                BidListDimension = "HasLivestreamId"
	BidListDimensionHasProductionQualityID                         BidListDimension = "HasProductionQualityId"
	BidListDimensionHasContentRatingID                             BidListDimension = "HasContentRatingId"
	BidListDimensionHasContentDurationID                           BidListDimension = "HasContentDurationId"
	BidListDimensionHasPreBidContextualCategoryID                  BidListDimension = "HasPreBidContextualCategoryId"
	BidListDimensionHasQualityScoreRange                           BidListDimension = "HasQualityScoreRange"
	BidListDimensionHasAtmosphericConditionID                      BidListDimension = "HasAtmosphericConditionId"
	BidListDimensionHasMarketplaceID                               BidListDimension = "HasMarketplaceId"
	BidListDimensionHasAudienceReachPercentageTierID               BidListDimension = "HasAudienceReachPercentageTierId"
	BidListDimensionHasContentTransparencyID                       BidListDimension = "HasContentTransparencyId"
	BidListDimensionHasAdLoadCategoryID                            BidListDimension = "HasAdLoadCategoryId"
	BidListDimensionHasFullReferrerURLID                           BidListDimension = "HasFullReferrerUrlId"
	BidListDimensionHasLikelyRefreshRateID                         BidListDimension = "HasLikelyRefreshRateId"
	BidListDimensionHasTargetableContentSeriesID                   BidListDimension = "HasTargetableContentSeriesId"
	BidListDimensionHasFeedID                                      BidListDimension = "HasFeedId"
	BidListDimensionHasRewardedID                                  BidListDimension = "HasRewardedId"
	BidListDimensionHasLiveEventID                                 BidListDimension = "HasLiveEventId"
	BidListDimensionHasLiveEventTypeID                             BidListDimension = "HasLiveEventTypeId"
	BidListDimensionHasSellerRelationshipTypeID                    BidListDimension = "HasSellerRelationshipTypeId"
	BidListDimensionHasAdToContentRatioRange                       BidListDimension = "HasAdToContentRatioRange"
	BidListDimensionHasAdsInViewRange                              BidListDimension = "HasAdsInViewRange"
	BidListDimensionHasExtendedZipCodeGroupSegmentThirdPartyDataID BidListDimension = "HasExtendedZipCodeGroupSegmentThirdPartyDataId"
	BidListDimensionHasContentLanguage                             BidListDimension = "HasContentLanguage"
)

func (e BidListDimension) ToPointer() *BidListDimension {
	return &e
}
func (e *BidListDimension) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "HasAdFormatId":
		fallthrough
	case "HasDomainFragmentId":
		fallthrough
	case "HasUniversalCategoryTaxonomyId":
		fallthrough
	case "HasPlacementPositionRelativeToFoldId":
		fallthrough
	case "HasAdvertiserTargetingDataId":
		fallthrough
	case "HasBrowserId":
		fallthrough
	case "HasCarrierId":
		fallthrough
	case "HasMiaozhenPageQualityCategoryId":
		fallthrough
	case "HasDeviceModelId":
		fallthrough
	case "HasDeviceTypeId":
		fallthrough
	case "HasGeoSegmentId":
		fallthrough
	case "HasHourOfWeek":
		fallthrough
	case "HasLanguageId":
		fallthrough
	case "HasOsId":
		fallthrough
	case "HasMiaozhenVideoPageQualityCategoryId":
		fallthrough
	case "HasPrivateContractId":
		fallthrough
	case "HasGrapeshotPredictsCategoryId":
		fallthrough
	case "HasRecencyWindowInMinutes":
		fallthrough
	case "HasRenderingContextId":
		fallthrough
	case "HasSupplyVendorId":
		fallthrough
	case "HasTemperatureBucketInCelsius":
		fallthrough
	case "HasThirdPartyDataId":
		fallthrough
	case "HasAdsTxtSellerTypeId":
		fallthrough
	case "HasVideoMutedStateId":
		fallthrough
	case "HasVideoPlaybackTypeId":
		fallthrough
	case "HasVideoPlayerSizeId":
		fallthrough
	case "HasVideoQualityId":
		fallthrough
	case "HasVideoSkippabilityId":
		fallthrough
	case "HasFactualProximityDataId":
		fallthrough
	case "HasGrapeshotDisplayPageQualityCategoryId":
		fallthrough
	case "HasImpressionPlacementId":
		fallthrough
	case "HasVideoTruthScoreRange":
		fallthrough
	case "HasVideoViewabilityScoreRange":
		fallthrough
	case "HasDisplayViewabilityScoreRange":
		fallthrough
	case "HasPeer39LanguageId":
		fallthrough
	case "HasGrapeshotLanguageId":
		fallthrough
	case "HasIntegralContextualCategoryId":
		fallthrough
	case "HasPeer39ContextualCategoryId":
		fallthrough
	case "HasGrapeshotContextualCategoryId":
		fallthrough
	case "HasDoubleVerifyContextualCategoryId":
		fallthrough
	case "HasGrapeshotVideoPageQualityCategoryId":
		fallthrough
	case "HasIntegralBrandSafetyCategoryId":
		fallthrough
	case "HasIntegralVideoBrandSafetyCategoryId":
		fallthrough
	case "HasPeer39BrandSafetyCategoryId":
		fallthrough
	case "HasGrapeshotBrandSafetyCategoryId":
		fallthrough
	case "HasDoubleVerifyBrandSafetyCategoryId":
		fallthrough
	case "HasIntegralPageQualityCategoryId":
		fallthrough
	case "HasIntegralVideoPageQualityCategoryId":
		fallthrough
	case "HasPeer39PageQualityCategoryId":
		fallthrough
	case "HasDoubleVerifyBotAvoidanceCategoryId":
		fallthrough
	case "HasContextualAppCategoryId":
		fallthrough
	case "HasPublisherId":
		fallthrough
	case "HasIntegralViewabilityCategoryId":
		fallthrough
	case "HasIntegralVideoViewabilityCategoryId":
		fallthrough
	case "HasDoubleVerifyViewabilityCategoryId":
		fallthrough
	case "HasDoubleVerifyVideoViewabilityCategoryId":
		fallthrough
	case "HasLegacyFrequencyAdjustmentId":
		fallthrough
	case "HasDoubleVerifyAuthenticBrandSafetyCategoryId":
		fallthrough
	case "HasPeer39ViewabilityCategoryId":
		fallthrough
	case "HasVideoCompletionRateScoreRange":
		fallthrough
	case "HasInternetConnectionTypeId":
		fallthrough
	case "HasAdBugPageQualityCategoryId":
		fallthrough
	case "HasAdBugVideoPageQualityCategoryId":
		fallthrough
	case "HasRTBAsiaPageQualityCategoryId":
		fallthrough
	case "HasRTBAsiaVideoPageQualityCategoryId":
		fallthrough
	case "HasTTDContextualCategoryId":
		fallthrough
	case "HasSupplyPathOptimizationListId":
		fallthrough
	case "HasIntegralKeywordBlacklistCategoryId":
		fallthrough
	case "HasMarketTypeId":
		fallthrough
	case "HasContextualSupplyVendorGenreId":
		fallthrough
	case "HasContextualSupplyVendorCategoryId":
		fallthrough
	case "HasGrapeshotViewabilityCategoryId":
		fallthrough
	case "HasGrapeshotVideoViewabilityCategoryId":
		fallthrough
	case "HasWeatherConditionId":
		fallthrough
	case "HasFrequencyAdjustmentId":
		fallthrough
	case "HasSemasioContextualCategoryId":
		fallthrough
	case "HasSellerId":
		fallthrough
	case "HasDigitalOutOfHomeVenueTypeId":
		fallthrough
	case "HasNativePlacementTypeId":
		fallthrough
	case "HasTTDNativeContextTypeId":
		fallthrough
	case "HasIdiosyncraticSegmentId":
		fallthrough
	case "HasTencentPageQualityCategoryId":
		fallthrough
	case "HasDomainClassId":
		fallthrough
	case "HasGeofenceThirdPartyDataAndBrand":
		fallthrough
	case "HasGenreId":
		fallthrough
	case "HasLivestreamId":
		fallthrough
	case "HasProductionQualityId":
		fallthrough
	case "HasContentRatingId":
		fallthrough
	case "HasContentDurationId":
		fallthrough
	case "HasPreBidContextualCategoryId":
		fallthrough
	case "HasQualityScoreRange":
		fallthrough
	case "HasAtmosphericConditionId":
		fallthrough
	case "HasMarketplaceId":
		fallthrough
	case "HasAudienceReachPercentageTierId":
		fallthrough
	case "HasContentTransparencyId":
		fallthrough
	case "HasAdLoadCategoryId":
		fallthrough
	case "HasFullReferrerUrlId":
		fallthrough
	case "HasLikelyRefreshRateId":
		fallthrough
	case "HasTargetableContentSeriesId":
		fallthrough
	case "HasFeedId":
		fallthrough
	case "HasRewardedId":
		fallthrough
	case "HasLiveEventId":
		fallthrough
	case "HasLiveEventTypeId":
		fallthrough
	case "HasSellerRelationshipTypeId":
		fallthrough
	case "HasAdToContentRatioRange":
		fallthrough
	case "HasAdsInViewRange":
		fallthrough
	case "HasExtendedZipCodeGroupSegmentThirdPartyDataId":
		fallthrough
	case "HasContentLanguage":
		*e = BidListDimension(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BidListDimension: %v", v)
	}
}
