// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type BidListSource string

const (
	BidListSourceUser                                  BidListSource = "User"
	BidListSourceSystemManual                          BidListSource = "SystemManual"
	BidListSourceSystemAuto                            BidListSource = "SystemAuto"
	BidListSourceUserBulkEdit                          BidListSource = "UserBulkEdit"
	BidListSourceSystemAutoForCookieLess               BidListSource = "SystemAutoForCookieLess"
	BidListSourceFrequencyMigration                    BidListSource = "FrequencyMigration"
	BidListSourceSystemAutoForCommitmentPrioritization BidListSource = "SystemAutoForCommitmentPrioritization"
	BidListSourceSystemAutoForWinRateExclusion         BidListSource = "SystemAutoForWinRateExclusion"
	BidListSourceSystemAutoForAlwaysOnDeals            BidListSource = "SystemAutoForAlwaysOnDeals"
	BidListSourceSystemAutoForMarketplace              BidListSource = "SystemAutoForMarketplace"
	BidListSourceSystemAutoForEndeavorTargeting        BidListSource = "SystemAutoForEndeavorTargeting"
	BidListSourceSystemAutoForCommitmentTargeting      BidListSource = "SystemAutoForCommitmentTargeting"
)

func (e BidListSource) ToPointer() *BidListSource {
	return &e
}
func (e *BidListSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "User":
		fallthrough
	case "SystemManual":
		fallthrough
	case "SystemAuto":
		fallthrough
	case "UserBulkEdit":
		fallthrough
	case "SystemAutoForCookieLess":
		fallthrough
	case "FrequencyMigration":
		fallthrough
	case "SystemAutoForCommitmentPrioritization":
		fallthrough
	case "SystemAutoForWinRateExclusion":
		fallthrough
	case "SystemAutoForAlwaysOnDeals":
		fallthrough
	case "SystemAutoForMarketplace":
		fallthrough
	case "SystemAutoForEndeavorTargeting":
		fallthrough
	case "SystemAutoForCommitmentTargeting":
		*e = BidListSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BidListSource: %v", v)
	}
}
