// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type BidListAssociateBehavior string

const (
	BidListAssociateBehaviorDoNotAssociate     BidListAssociateBehavior = "DoNotAssociate"
	BidListAssociateBehaviorAssociate          BidListAssociateBehavior = "Associate"
	BidListAssociateBehaviorAssociateAndEnable BidListAssociateBehavior = "AssociateAndEnable"
)

func (e BidListAssociateBehavior) ToPointer() *BidListAssociateBehavior {
	return &e
}
func (e *BidListAssociateBehavior) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DoNotAssociate":
		fallthrough
	case "Associate":
		fallthrough
	case "AssociateAndEnable":
		*e = BidListAssociateBehavior(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BidListAssociateBehavior: %v", v)
	}
}
