// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BidLineCreateInput struct {
	AdFormatID                                  *string                              `json:"adFormatId,omitempty"`
	DomainFragment                              *string                              `json:"domainFragment,omitempty"`
	UniversalCategoryTaxonomyID                 *string                              `json:"universalCategoryTaxonomyId,omitempty"`
	Browser                                     *Browser                             `json:"browser,omitempty"`
	BrowserID                                   *BrowserInput                        `json:"browserId,omitempty"`
	CarrierID                                   *string                              `json:"carrierId,omitempty"`
	DeviceModelID                               *int                                 `json:"deviceModelId,omitempty"`
	DeviceType                                  *DeviceType                          `json:"deviceType,omitempty"`
	GeoSegmentID                                *string                              `json:"geoSegmentId,omitempty"`
	HourOfWeek                                  *int                                 `json:"hourOfWeek,omitempty"`
	LanguageID                                  *string                              `json:"languageId,omitempty"`
	OsName                                      *string                              `json:"osName,omitempty"`
	PrivateContractID                           *string                              `json:"privateContractId,omitempty"`
	RecencyWindowInMinutes                      *Int32Range                          `json:"recencyWindowInMinutes,omitempty"`
	RenderingContext                            *RenderingContext                    `json:"renderingContext,omitempty"`
	SupplyVendorID                              *string                              `json:"supplyVendorId,omitempty"`
	TemperatureBucketInCelsius                  *DecimalRange                        `json:"temperatureBucketInCelsius,omitempty"`
	AdsTxtSellerType                            *AdsTxtSellerType                    `json:"adsTxtSellerType,omitempty"`
	VideoMutedState                             *VideoMutedState                     `json:"videoMutedState,omitempty"`
	VideoPlaybackType                           *VideoPlaybackType                   `json:"videoPlaybackType,omitempty"`
	VideoPlayerSize                             *VideoPlayerSize                     `json:"videoPlayerSize,omitempty"`
	VideoQuality                                *VideoQuality                        `json:"videoQuality,omitempty"`
	VideoSkippability                           *VideoSkippability                   `json:"videoSkippability,omitempty"`
	FactualProximityTarget                      *FactualProximityTargetInput         `json:"factualProximityTarget,omitempty"`
	ImpressionPlacementValue                    *string                              `json:"impressionPlacementValue,omitempty"`
	VideoTruthScoreRange                        *DecimalRange                        `json:"videoTruthScoreRange,omitempty"`
	VideoViewabilityScoreRange                  *DecimalRange                        `json:"videoViewabilityScoreRange,omitempty"`
	DisplayViewabilityScoreRange                *DecimalRange                        `json:"displayViewabilityScoreRange,omitempty"`
	Peer39LanguageID                            *string                              `json:"peer39LanguageId,omitempty"`
	DoubleVerifyBotAvoidanceCategory            *DoubleVerifyBotAvoidance            `json:"doubleVerifyBotAvoidanceCategory,omitempty"`
	ContextualAppCategoryID                     *string                              `json:"contextualAppCategoryId,omitempty"`
	PublisherID                                 *string                              `json:"publisherId,omitempty"`
	IntegralViewabilityCategoryID               *string                              `json:"integralViewabilityCategoryId,omitempty"`
	IntegralViewabilityCategory                 *IntegralViewabilityInput            `json:"integralViewabilityCategory,omitempty"`
	IntegralVideoViewabilityCategoryID          *string                              `json:"integralVideoViewabilityCategoryId,omitempty"`
	IntegralVideoViewabilityCategory            *IntegralVideoViewabilityInput       `json:"integralVideoViewabilityCategory,omitempty"`
	DoubleVerifyViewabilityCategory             *DoubleVerifyDisplayViewability      `json:"doubleVerifyViewabilityCategory,omitempty"`
	DoubleVerifyVideoViewabilityCategory        *DoubleVerifyVideoViewability        `json:"doubleVerifyVideoViewabilityCategory,omitempty"`
	Peer39ViewabilityCategoryID                 *string                              `json:"peer39ViewabilityCategoryId,omitempty"`
	Peer39ViewabilityCategory                   *Peer39ViewabilityInput              `json:"peer39ViewabilityCategory,omitempty"`
	VideoCompletionRateScoreRange               *DecimalRange                        `json:"videoCompletionRateScoreRange,omitempty"`
	InternetConnectionInput                     *InternetConnectionTypeInput         `json:"internetConnectionInput,omitempty"`
	InternetConnectionTypeID                    *InternetConnectionTypeInput         `json:"internetConnectionTypeId,omitempty"`
	InternetConnection                          *InternetConnectionType              `json:"internetConnection,omitempty"`
	RtbAsiaPageQualityCategory                  *RTBAsiaViewability                  `json:"rtbAsiaPageQualityCategory,omitempty"`
	RtbAsiaVideoPageQualityCategory             *RTBAsiaViewability                  `json:"rtbAsiaVideoPageQualityCategory,omitempty"`
	SupplyPathOptimizationListID                *int                                 `json:"supplyPathOptimizationListId,omitempty"`
	MarketType                                  *MarketTypeBidList                   `json:"marketType,omitempty"`
	WeatherCondition                            *WeatherCondition                    `json:"weatherCondition,omitempty"`
	FrequencyAdjustment                         *FrequencyAdjustmentInput            `json:"frequencyAdjustment,omitempty"`
	SellerDomain                                *string                              `json:"sellerDomain,omitempty"`
	DigitalOutOfHomeVenueTypeID                 *string                              `json:"digitalOutOfHomeVenueTypeId,omitempty"`
	NativePlacementType                         *NativePlacementType                 `json:"nativePlacementType,omitempty"`
	NativeContextType                           *NativeContextType                   `json:"nativeContextType,omitempty"`
	IdiosyncraticSegment                        *IdiosyncraticSegment                `json:"idiosyncraticSegment,omitempty"`
	TencentPageQualityCategory                  *TencentPageQualityInput             `json:"tencentPageQualityCategory,omitempty"`
	DomainClassID                               *int                                 `json:"domainClassId,omitempty"`
	GeofenceThirdPartyDataAndBrand              *GeofenceThirdPartyDataAndBrandInput `json:"geofenceThirdPartyDataAndBrand,omitempty"`
	GenreID                                     *string                              `json:"genreId,omitempty"`
	Livestream                                  *Livestream                          `json:"livestream,omitempty"`
	ProductionQuality                           *ProductionQuality                   `json:"productionQuality,omitempty"`
	ProductionQualityID                         *ProductionQualityInput              `json:"productionQualityId,omitempty"`
	ContentRatingID                             *string                              `json:"contentRatingId,omitempty"`
	ContentDuration                             *ContentDuration                     `json:"contentDuration,omitempty"`
	QualityScoreRange                           *DecimalRange                        `json:"qualityScoreRange,omitempty"`
	AtmosphericCondition                        *AtmosphericCondition                `json:"atmosphericCondition,omitempty"`
	MarketplaceID                               *string                              `json:"marketplaceId,omitempty"`
	AudienceReachPercentageTier                 *AudienceReachPercentageTier         `json:"audienceReachPercentageTier,omitempty"`
	ContentTransparency                         *ContentTransparency                 `json:"contentTransparency,omitempty"`
	FullReferrerURL                             *FullReferrerURL                     `json:"fullReferrerUrl,omitempty"`
	LikelyRefreshRate                           *LikelyRefreshRate                   `json:"likelyRefreshRate,omitempty"`
	Rewarded                                    *Rewarded                            `json:"rewarded,omitempty"`
	FeedID                                      *int                                 `json:"feedId,omitempty"`
	LiveEventID                                 *string                              `json:"liveEventId,omitempty"`
	LiveEventTypeID                             *string                              `json:"liveEventTypeId,omitempty"`
	ExtendedZipCodeGroupSegmentThirdPartyDataID *int64                               `json:"extendedZipCodeGroupSegmentThirdPartyDataId,omitempty"`
	ContentLanguageID                           *string                              `json:"contentLanguageId,omitempty"`
	AdToContentRatioRange                       *DecimalRange                        `json:"adToContentRatioRange,omitempty"`
	AdsInViewRange                              *DecimalRange                        `json:"adsInViewRange,omitempty"`
	BidAdjustment                               *float64                             `json:"bidAdjustment,omitempty"`
	VolumeControlPriority                       *VolumeControlPriority               `json:"volumeControlPriority,omitempty"`
	MaxBid                                      *float64                             `json:"maxBid,omitempty"`
}

func (b *BidLineCreateInput) GetAdFormatID() *string {
	if b == nil {
		return nil
	}
	return b.AdFormatID
}

func (b *BidLineCreateInput) GetDomainFragment() *string {
	if b == nil {
		return nil
	}
	return b.DomainFragment
}

func (b *BidLineCreateInput) GetUniversalCategoryTaxonomyID() *string {
	if b == nil {
		return nil
	}
	return b.UniversalCategoryTaxonomyID
}

func (b *BidLineCreateInput) GetBrowser() *Browser {
	if b == nil {
		return nil
	}
	return b.Browser
}

func (b *BidLineCreateInput) GetBrowserID() *BrowserInput {
	if b == nil {
		return nil
	}
	return b.BrowserID
}

func (b *BidLineCreateInput) GetCarrierID() *string {
	if b == nil {
		return nil
	}
	return b.CarrierID
}

func (b *BidLineCreateInput) GetDeviceModelID() *int {
	if b == nil {
		return nil
	}
	return b.DeviceModelID
}

func (b *BidLineCreateInput) GetDeviceType() *DeviceType {
	if b == nil {
		return nil
	}
	return b.DeviceType
}

func (b *BidLineCreateInput) GetGeoSegmentID() *string {
	if b == nil {
		return nil
	}
	return b.GeoSegmentID
}

func (b *BidLineCreateInput) GetHourOfWeek() *int {
	if b == nil {
		return nil
	}
	return b.HourOfWeek
}

func (b *BidLineCreateInput) GetLanguageID() *string {
	if b == nil {
		return nil
	}
	return b.LanguageID
}

func (b *BidLineCreateInput) GetOsName() *string {
	if b == nil {
		return nil
	}
	return b.OsName
}

func (b *BidLineCreateInput) GetPrivateContractID() *string {
	if b == nil {
		return nil
	}
	return b.PrivateContractID
}

func (b *BidLineCreateInput) GetRecencyWindowInMinutes() *Int32Range {
	if b == nil {
		return nil
	}
	return b.RecencyWindowInMinutes
}

func (b *BidLineCreateInput) GetRenderingContext() *RenderingContext {
	if b == nil {
		return nil
	}
	return b.RenderingContext
}

func (b *BidLineCreateInput) GetSupplyVendorID() *string {
	if b == nil {
		return nil
	}
	return b.SupplyVendorID
}

func (b *BidLineCreateInput) GetTemperatureBucketInCelsius() *DecimalRange {
	if b == nil {
		return nil
	}
	return b.TemperatureBucketInCelsius
}

func (b *BidLineCreateInput) GetAdsTxtSellerType() *AdsTxtSellerType {
	if b == nil {
		return nil
	}
	return b.AdsTxtSellerType
}

func (b *BidLineCreateInput) GetVideoMutedState() *VideoMutedState {
	if b == nil {
		return nil
	}
	return b.VideoMutedState
}

func (b *BidLineCreateInput) GetVideoPlaybackType() *VideoPlaybackType {
	if b == nil {
		return nil
	}
	return b.VideoPlaybackType
}

func (b *BidLineCreateInput) GetVideoPlayerSize() *VideoPlayerSize {
	if b == nil {
		return nil
	}
	return b.VideoPlayerSize
}

func (b *BidLineCreateInput) GetVideoQuality() *VideoQuality {
	if b == nil {
		return nil
	}
	return b.VideoQuality
}

func (b *BidLineCreateInput) GetVideoSkippability() *VideoSkippability {
	if b == nil {
		return nil
	}
	return b.VideoSkippability
}

func (b *BidLineCreateInput) GetFactualProximityTarget() *FactualProximityTargetInput {
	if b == nil {
		return nil
	}
	return b.FactualProximityTarget
}

func (b *BidLineCreateInput) GetImpressionPlacementValue() *string {
	if b == nil {
		return nil
	}
	return b.ImpressionPlacementValue
}

func (b *BidLineCreateInput) GetVideoTruthScoreRange() *DecimalRange {
	if b == nil {
		return nil
	}
	return b.VideoTruthScoreRange
}

func (b *BidLineCreateInput) GetVideoViewabilityScoreRange() *DecimalRange {
	if b == nil {
		return nil
	}
	return b.VideoViewabilityScoreRange
}

func (b *BidLineCreateInput) GetDisplayViewabilityScoreRange() *DecimalRange {
	if b == nil {
		return nil
	}
	return b.DisplayViewabilityScoreRange
}

func (b *BidLineCreateInput) GetPeer39LanguageID() *string {
	if b == nil {
		return nil
	}
	return b.Peer39LanguageID
}

func (b *BidLineCreateInput) GetDoubleVerifyBotAvoidanceCategory() *DoubleVerifyBotAvoidance {
	if b == nil {
		return nil
	}
	return b.DoubleVerifyBotAvoidanceCategory
}

func (b *BidLineCreateInput) GetContextualAppCategoryID() *string {
	if b == nil {
		return nil
	}
	return b.ContextualAppCategoryID
}

func (b *BidLineCreateInput) GetPublisherID() *string {
	if b == nil {
		return nil
	}
	return b.PublisherID
}

func (b *BidLineCreateInput) GetIntegralViewabilityCategoryID() *string {
	if b == nil {
		return nil
	}
	return b.IntegralViewabilityCategoryID
}

func (b *BidLineCreateInput) GetIntegralViewabilityCategory() *IntegralViewabilityInput {
	if b == nil {
		return nil
	}
	return b.IntegralViewabilityCategory
}

func (b *BidLineCreateInput) GetIntegralVideoViewabilityCategoryID() *string {
	if b == nil {
		return nil
	}
	return b.IntegralVideoViewabilityCategoryID
}

func (b *BidLineCreateInput) GetIntegralVideoViewabilityCategory() *IntegralVideoViewabilityInput {
	if b == nil {
		return nil
	}
	return b.IntegralVideoViewabilityCategory
}

func (b *BidLineCreateInput) GetDoubleVerifyViewabilityCategory() *DoubleVerifyDisplayViewability {
	if b == nil {
		return nil
	}
	return b.DoubleVerifyViewabilityCategory
}

func (b *BidLineCreateInput) GetDoubleVerifyVideoViewabilityCategory() *DoubleVerifyVideoViewability {
	if b == nil {
		return nil
	}
	return b.DoubleVerifyVideoViewabilityCategory
}

func (b *BidLineCreateInput) GetPeer39ViewabilityCategoryID() *string {
	if b == nil {
		return nil
	}
	return b.Peer39ViewabilityCategoryID
}

func (b *BidLineCreateInput) GetPeer39ViewabilityCategory() *Peer39ViewabilityInput {
	if b == nil {
		return nil
	}
	return b.Peer39ViewabilityCategory
}

func (b *BidLineCreateInput) GetVideoCompletionRateScoreRange() *DecimalRange {
	if b == nil {
		return nil
	}
	return b.VideoCompletionRateScoreRange
}

func (b *BidLineCreateInput) GetInternetConnectionInput() *InternetConnectionTypeInput {
	if b == nil {
		return nil
	}
	return b.InternetConnectionInput
}

func (b *BidLineCreateInput) GetInternetConnectionTypeID() *InternetConnectionTypeInput {
	if b == nil {
		return nil
	}
	return b.InternetConnectionTypeID
}

func (b *BidLineCreateInput) GetInternetConnection() *InternetConnectionType {
	if b == nil {
		return nil
	}
	return b.InternetConnection
}

func (b *BidLineCreateInput) GetRtbAsiaPageQualityCategory() *RTBAsiaViewability {
	if b == nil {
		return nil
	}
	return b.RtbAsiaPageQualityCategory
}

func (b *BidLineCreateInput) GetRtbAsiaVideoPageQualityCategory() *RTBAsiaViewability {
	if b == nil {
		return nil
	}
	return b.RtbAsiaVideoPageQualityCategory
}

func (b *BidLineCreateInput) GetSupplyPathOptimizationListID() *int {
	if b == nil {
		return nil
	}
	return b.SupplyPathOptimizationListID
}

func (b *BidLineCreateInput) GetMarketType() *MarketTypeBidList {
	if b == nil {
		return nil
	}
	return b.MarketType
}

func (b *BidLineCreateInput) GetWeatherCondition() *WeatherCondition {
	if b == nil {
		return nil
	}
	return b.WeatherCondition
}

func (b *BidLineCreateInput) GetFrequencyAdjustment() *FrequencyAdjustmentInput {
	if b == nil {
		return nil
	}
	return b.FrequencyAdjustment
}

func (b *BidLineCreateInput) GetSellerDomain() *string {
	if b == nil {
		return nil
	}
	return b.SellerDomain
}

func (b *BidLineCreateInput) GetDigitalOutOfHomeVenueTypeID() *string {
	if b == nil {
		return nil
	}
	return b.DigitalOutOfHomeVenueTypeID
}

func (b *BidLineCreateInput) GetNativePlacementType() *NativePlacementType {
	if b == nil {
		return nil
	}
	return b.NativePlacementType
}

func (b *BidLineCreateInput) GetNativeContextType() *NativeContextType {
	if b == nil {
		return nil
	}
	return b.NativeContextType
}

func (b *BidLineCreateInput) GetIdiosyncraticSegment() *IdiosyncraticSegment {
	if b == nil {
		return nil
	}
	return b.IdiosyncraticSegment
}

func (b *BidLineCreateInput) GetTencentPageQualityCategory() *TencentPageQualityInput {
	if b == nil {
		return nil
	}
	return b.TencentPageQualityCategory
}

func (b *BidLineCreateInput) GetDomainClassID() *int {
	if b == nil {
		return nil
	}
	return b.DomainClassID
}

func (b *BidLineCreateInput) GetGeofenceThirdPartyDataAndBrand() *GeofenceThirdPartyDataAndBrandInput {
	if b == nil {
		return nil
	}
	return b.GeofenceThirdPartyDataAndBrand
}

func (b *BidLineCreateInput) GetGenreID() *string {
	if b == nil {
		return nil
	}
	return b.GenreID
}

func (b *BidLineCreateInput) GetLivestream() *Livestream {
	if b == nil {
		return nil
	}
	return b.Livestream
}

func (b *BidLineCreateInput) GetProductionQuality() *ProductionQuality {
	if b == nil {
		return nil
	}
	return b.ProductionQuality
}

func (b *BidLineCreateInput) GetProductionQualityID() *ProductionQualityInput {
	if b == nil {
		return nil
	}
	return b.ProductionQualityID
}

func (b *BidLineCreateInput) GetContentRatingID() *string {
	if b == nil {
		return nil
	}
	return b.ContentRatingID
}

func (b *BidLineCreateInput) GetContentDuration() *ContentDuration {
	if b == nil {
		return nil
	}
	return b.ContentDuration
}

func (b *BidLineCreateInput) GetQualityScoreRange() *DecimalRange {
	if b == nil {
		return nil
	}
	return b.QualityScoreRange
}

func (b *BidLineCreateInput) GetAtmosphericCondition() *AtmosphericCondition {
	if b == nil {
		return nil
	}
	return b.AtmosphericCondition
}

func (b *BidLineCreateInput) GetMarketplaceID() *string {
	if b == nil {
		return nil
	}
	return b.MarketplaceID
}

func (b *BidLineCreateInput) GetAudienceReachPercentageTier() *AudienceReachPercentageTier {
	if b == nil {
		return nil
	}
	return b.AudienceReachPercentageTier
}

func (b *BidLineCreateInput) GetContentTransparency() *ContentTransparency {
	if b == nil {
		return nil
	}
	return b.ContentTransparency
}

func (b *BidLineCreateInput) GetFullReferrerURL() *FullReferrerURL {
	if b == nil {
		return nil
	}
	return b.FullReferrerURL
}

func (b *BidLineCreateInput) GetLikelyRefreshRate() *LikelyRefreshRate {
	if b == nil {
		return nil
	}
	return b.LikelyRefreshRate
}

func (b *BidLineCreateInput) GetRewarded() *Rewarded {
	if b == nil {
		return nil
	}
	return b.Rewarded
}

func (b *BidLineCreateInput) GetFeedID() *int {
	if b == nil {
		return nil
	}
	return b.FeedID
}

func (b *BidLineCreateInput) GetLiveEventID() *string {
	if b == nil {
		return nil
	}
	return b.LiveEventID
}

func (b *BidLineCreateInput) GetLiveEventTypeID() *string {
	if b == nil {
		return nil
	}
	return b.LiveEventTypeID
}

func (b *BidLineCreateInput) GetExtendedZipCodeGroupSegmentThirdPartyDataID() *int64 {
	if b == nil {
		return nil
	}
	return b.ExtendedZipCodeGroupSegmentThirdPartyDataID
}

func (b *BidLineCreateInput) GetContentLanguageID() *string {
	if b == nil {
		return nil
	}
	return b.ContentLanguageID
}

func (b *BidLineCreateInput) GetAdToContentRatioRange() *DecimalRange {
	if b == nil {
		return nil
	}
	return b.AdToContentRatioRange
}

func (b *BidLineCreateInput) GetAdsInViewRange() *DecimalRange {
	if b == nil {
		return nil
	}
	return b.AdsInViewRange
}

func (b *BidLineCreateInput) GetBidAdjustment() *float64 {
	if b == nil {
		return nil
	}
	return b.BidAdjustment
}

func (b *BidLineCreateInput) GetVolumeControlPriority() *VolumeControlPriority {
	if b == nil {
		return nil
	}
	return b.VolumeControlPriority
}

func (b *BidLineCreateInput) GetMaxBid() *float64 {
	if b == nil {
		return nil
	}
	return b.MaxBid
}
