// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type BidListAdjustmentType string

const (
	BidListAdjustmentTypeExclusion           BidListAdjustmentType = "Exclusion"
	BidListAdjustmentTypeInclusion           BidListAdjustmentType = "Inclusion"
	BidListAdjustmentTypeOptimized           BidListAdjustmentType = "Optimized"
	BidListAdjustmentTypeVcPromotion         BidListAdjustmentType = "VCPromotion"
	BidListAdjustmentTypeFractionalExclusion BidListAdjustmentType = "FractionalExclusion"
)

func (e BidListAdjustmentType) ToPointer() *BidListAdjustmentType {
	return &e
}
func (e *BidListAdjustmentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Exclusion":
		fallthrough
	case "Inclusion":
		fallthrough
	case "Optimized":
		fallthrough
	case "VCPromotion":
		fallthrough
	case "FractionalExclusion":
		*e = BidListAdjustmentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BidListAdjustmentType: %v", v)
	}
}
