// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BidListDimensionOptionsInput struct {
	Geo *GeoBidListOptionsInput `json:"geo,omitempty"`
}

func (b *BidListDimensionOptionsInput) GetGeo() *GeoBidListOptionsInput {
	if b == nil {
		return nil
	}
	return b.Geo
}
