// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Browser string

const (
	BrowserOther              Browser = "Other"
	BrowserInternetExplorer7  Browser = "InternetExplorer7"
	BrowserInternetExplorer8  Browser = "InternetExplorer8"
	BrowserInternetExplorer9  Browser = "InternetExplorer9"
	BrowserFirefox            Browser = "Firefox"
	BrowserChrome             Browser = "Chrome"
	BrowserSafari             Browser = "Safari"
	BrowserOpera              Browser = "Opera"
	BrowserInternetExplorer10 Browser = "InternetExplorer10"
	BrowserInternetExplorer11 Browser = "InternetExplorer11"
	BrowserInApp              Browser = "InApp"
	BrowserEdge               Browser = "Edge"
	BrowserBaidu              Browser = "Baidu"
	BrowserYandex             Browser = "Yandex"
	BrowserWebView            Browser = "WebView"
)

func (e Browser) ToPointer() *Browser {
	return &e
}
func (e *Browser) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Other":
		fallthrough
	case "InternetExplorer7":
		fallthrough
	case "InternetExplorer8":
		fallthrough
	case "InternetExplorer9":
		fallthrough
	case "Firefox":
		fallthrough
	case "Chrome":
		fallthrough
	case "Safari":
		fallthrough
	case "Opera":
		fallthrough
	case "InternetExplorer10":
		fallthrough
	case "InternetExplorer11":
		fallthrough
	case "InApp":
		fallthrough
	case "Edge":
		fallthrough
	case "Baidu":
		fallthrough
	case "Yandex":
		fallthrough
	case "WebView":
		*e = Browser(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Browser: %v", v)
	}
}
