// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type BrowserInput string

const (
	BrowserInputOther              BrowserInput = "Other"
	BrowserInputInternetExplorer7  BrowserInput = "InternetExplorer7"
	BrowserInputInternetExplorer8  BrowserInput = "InternetExplorer8"
	BrowserInputInternetExplorer9  BrowserInput = "InternetExplorer9"
	BrowserInputFirefox            BrowserInput = "Firefox"
	BrowserInputChrome             BrowserInput = "Chrome"
	BrowserInputSafari             BrowserInput = "Safari"
	BrowserInputOpera              BrowserInput = "Opera"
	BrowserInputInternetExplorer10 BrowserInput = "InternetExplorer10"
	BrowserInputInternetExplorer11 BrowserInput = "InternetExplorer11"
	BrowserInputInApp              BrowserInput = "InApp"
	BrowserInputEdge               BrowserInput = "Edge"
	BrowserInputBaidu              BrowserInput = "Baidu"
	BrowserInputYandex             BrowserInput = "Yandex"
	BrowserInputWebView            BrowserInput = "WebView"
)

func (e BrowserInput) ToPointer() *BrowserInput {
	return &e
}
func (e *BrowserInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Other":
		fallthrough
	case "InternetExplorer7":
		fallthrough
	case "InternetExplorer8":
		fallthrough
	case "InternetExplorer9":
		fallthrough
	case "Firefox":
		fallthrough
	case "Chrome":
		fallthrough
	case "Safari":
		fallthrough
	case "Opera":
		fallthrough
	case "InternetExplorer10":
		fallthrough
	case "InternetExplorer11":
		fallthrough
	case "InApp":
		fallthrough
	case "Edge":
		fallthrough
	case "Baidu":
		fallthrough
	case "Yandex":
		fallthrough
	case "WebView":
		*e = BrowserInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BrowserInput: %v", v)
	}
}
