// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type BulkJobStatus string

const (
	BulkJobStatusQueued         BulkJobStatus = "Queued"
	BulkJobStatusInProgress     BulkJobStatus = "InProgress"
	BulkJobStatusPartialSuccess BulkJobStatus = "PartialSuccess"
	BulkJobStatusFailure        BulkJobStatus = "Failure"
	BulkJobStatusSuccess        BulkJobStatus = "Success"
	BulkJobStatusCancelled      BulkJobStatus = "Cancelled"
)

func (e BulkJobStatus) ToPointer() *BulkJobStatus {
	return &e
}
func (e *BulkJobStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Queued":
		fallthrough
	case "InProgress":
		fallthrough
	case "PartialSuccess":
		fallthrough
	case "Failure":
		fallthrough
	case "Success":
		fallthrough
	case "Cancelled":
		*e = BulkJobStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BulkJobStatus: %v", v)
	}
}
