// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CallRestAPIWorkflowInput struct {
	MethodType RestAPIMethodType `json:"methodType"`
	Endpoint   *string           `json:"endpoint"`
	DataBody   *string           `json:"dataBody,omitempty"`
}

func (o *CallRestAPIWorkflowInput) GetMethodType() RestAPIMethodType {
	if o == nil {
		return RestAPIMethodType("")
	}
	return o.MethodType
}

func (o *CallRestAPIWorkflowInput) GetEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.Endpoint
}

func (o *CallRestAPIWorkflowInput) GetDataBody() *string {
	if o == nil {
		return nil
	}
	return o.DataBody
}
