// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CallRestAPIWorkflowInput struct {
	MethodType RestAPIMethodType `json:"methodType"`
	Endpoint   *string           `json:"endpoint"`
	DataBody   *string           `json:"dataBody,omitempty"`
}

func (c *CallRestAPIWorkflowInput) GetMethodType() RestAPIMethodType {
	if c == nil {
		return RestAPIMethodType("")
	}
	return c.MethodType
}

func (c *CallRestAPIWorkflowInput) GetEndpoint() *string {
	if c == nil {
		return nil
	}
	return c.Endpoint
}

func (c *CallRestAPIWorkflowInput) GetDataBody() *string {
	if c == nil {
		return nil
	}
	return c.DataBody
}
