// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignCreateWorkflowAdGroupAdvancedInput struct {
	KoaOptimizationSettings                    *AdGroupWorkflowKoaOptimizationSettingsInput   `json:"koaOptimizationSettings,omitempty"`
	ComscoreSettings                           *AdGroupWorkflowComscoreSettingsInput          `json:"comscoreSettings,omitempty"`
	ContractTargeting                          *AdGroupWorkflowContractTargetingInput         `json:"contractTargeting,omitempty"`
	DimensionalBiddingAutoOptimizationSettings [][]DimensionalBiddingDimensions               `json:"dimensionalBiddingAutoOptimizationSettings,omitempty"`
	IsUseClicksAsConversionsEnabled            *bool                                          `json:"isUseClicksAsConversionsEnabled,omitempty"`
	IsUseSecondaryConversionsEnabled           *bool                                          `json:"isUseSecondaryConversionsEnabled,omitempty"`
	NielsenTrackingAttributes                  *AdGroupWorkflowNielsenTrackingAttributesInput `json:"nielsenTrackingAttributes,omitempty"`
	NewFrequencyConfigs                        []AdGroupWorkflowNewFrequencyConfigInput       `json:"newFrequencyConfigs,omitempty"`
	IncludeDefaultsFromCampaign                *bool                                          `json:"includeDefaultsFromCampaign,omitempty"`
	Flights                                    []CampaignCreateWorkflowAdGroupFlightInput     `json:"flights,omitempty"`
}

func (c *CampaignCreateWorkflowAdGroupAdvancedInput) GetKoaOptimizationSettings() *AdGroupWorkflowKoaOptimizationSettingsInput {
	if c == nil {
		return nil
	}
	return c.KoaOptimizationSettings
}

func (c *CampaignCreateWorkflowAdGroupAdvancedInput) GetComscoreSettings() *AdGroupWorkflowComscoreSettingsInput {
	if c == nil {
		return nil
	}
	return c.ComscoreSettings
}

func (c *CampaignCreateWorkflowAdGroupAdvancedInput) GetContractTargeting() *AdGroupWorkflowContractTargetingInput {
	if c == nil {
		return nil
	}
	return c.ContractTargeting
}

func (c *CampaignCreateWorkflowAdGroupAdvancedInput) GetDimensionalBiddingAutoOptimizationSettings() [][]DimensionalBiddingDimensions {
	if c == nil {
		return nil
	}
	return c.DimensionalBiddingAutoOptimizationSettings
}

func (c *CampaignCreateWorkflowAdGroupAdvancedInput) GetIsUseClicksAsConversionsEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.IsUseClicksAsConversionsEnabled
}

func (c *CampaignCreateWorkflowAdGroupAdvancedInput) GetIsUseSecondaryConversionsEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.IsUseSecondaryConversionsEnabled
}

func (c *CampaignCreateWorkflowAdGroupAdvancedInput) GetNielsenTrackingAttributes() *AdGroupWorkflowNielsenTrackingAttributesInput {
	if c == nil {
		return nil
	}
	return c.NielsenTrackingAttributes
}

func (c *CampaignCreateWorkflowAdGroupAdvancedInput) GetNewFrequencyConfigs() []AdGroupWorkflowNewFrequencyConfigInput {
	if c == nil {
		return nil
	}
	return c.NewFrequencyConfigs
}

func (c *CampaignCreateWorkflowAdGroupAdvancedInput) GetIncludeDefaultsFromCampaign() *bool {
	if c == nil {
		return nil
	}
	return c.IncludeDefaultsFromCampaign
}

func (c *CampaignCreateWorkflowAdGroupAdvancedInput) GetFlights() []CampaignCreateWorkflowAdGroupFlightInput {
	if c == nil {
		return nil
	}
	return c.Flights
}
