// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/thetradedesk/ttd-workflows-go/internal/utils"
	"time"
)

type CampaignCreateWorkflowPassThroughFeeCardInput struct {
	StartDateUtc    *time.Time                           `json:"startDateUtc,omitempty"`
	PassThroughFees []CampaignCreatePassThroughFeesInput `json:"passThroughFees"`
}

func (c CampaignCreateWorkflowPassThroughFeeCardInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CampaignCreateWorkflowPassThroughFeeCardInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CampaignCreateWorkflowPassThroughFeeCardInput) GetStartDateUtc() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartDateUtc
}

func (c *CampaignCreateWorkflowPassThroughFeeCardInput) GetPassThroughFees() []CampaignCreatePassThroughFeesInput {
	if c == nil {
		return []CampaignCreatePassThroughFeesInput{}
	}
	return c.PassThroughFees
}
