// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignCreateWorkflowInputWithValidation struct {
	PrimaryInput      CampaignCreateWorkflowPrimaryInput   `json:"primaryInput"`
	AdvancedInput     *CampaignCreateWorkflowAdvancedInput `json:"advancedInput,omitempty"`
	AdGroups          []CampaignCreateWorkflowAdGroupInput `json:"adGroups,omitempty"`
	ValidateInputOnly *bool                                `json:"validateInputOnly,omitempty"`
}

func (c *CampaignCreateWorkflowInputWithValidation) GetPrimaryInput() CampaignCreateWorkflowPrimaryInput {
	if c == nil {
		return CampaignCreateWorkflowPrimaryInput{}
	}
	return c.PrimaryInput
}

func (c *CampaignCreateWorkflowInputWithValidation) GetAdvancedInput() *CampaignCreateWorkflowAdvancedInput {
	if c == nil {
		return nil
	}
	return c.AdvancedInput
}

func (c *CampaignCreateWorkflowInputWithValidation) GetAdGroups() []CampaignCreateWorkflowAdGroupInput {
	if c == nil {
		return nil
	}
	return c.AdGroups
}

func (c *CampaignCreateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if c == nil {
		return nil
	}
	return c.ValidateInputOnly
}
