// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/thetradedesk/ttd-workflows-go/internal/utils"
	"time"
)

type CampaignWorkflow struct {
	ID                              *string                  `json:"id"`
	Name                            *string                  `json:"name,omitempty"`
	CampaignGroupID                 *int64                   `json:"campaignGroupId,omitempty"`
	Description                     *string                  `json:"description,omitempty"`
	StartDate                       *time.Time               `json:"startDate,omitempty"`
	EndDate                         *time.Time               `json:"endDate,omitempty"`
	TimeZone                        *string                  `json:"timeZone,omitempty"`
	CustomCPAClickWeight            *float64                 `json:"customCPAClickWeight,omitempty"`
	CustomCPAViewthroughWeight      *float64                 `json:"customCPAViewthroughWeight,omitempty"`
	CustomCPAType                   *CustomCPAType           `json:"customCPAType,omitempty"`
	ImpressionsOnlyBudgetingCpm     *float64                 `json:"impressionsOnlyBudgetingCpm,omitempty"`
	PrimaryChannel                  *CampaignChannelType     `json:"primaryChannel,omitempty"`
	PrimaryGoal                     *string                  `json:"primaryGoal,omitempty"`
	SeedID                          *string                  `json:"seedId,omitempty"`
	ConversionReportingColumnsCount *int                     `json:"conversionReportingColumnsCount,omitempty"`
	Flights                         []CampaignFlightWorkflow `json:"flights,omitempty"`
	SecondaryGoal                   *string                  `json:"secondaryGoal,omitempty"`
	TertiaryGoal                    *string                  `json:"tertiaryGoal,omitempty"`
}

func (c CampaignWorkflow) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CampaignWorkflow) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CampaignWorkflow) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CampaignWorkflow) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CampaignWorkflow) GetCampaignGroupID() *int64 {
	if c == nil {
		return nil
	}
	return c.CampaignGroupID
}

func (c *CampaignWorkflow) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CampaignWorkflow) GetStartDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartDate
}

func (c *CampaignWorkflow) GetEndDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndDate
}

func (c *CampaignWorkflow) GetTimeZone() *string {
	if c == nil {
		return nil
	}
	return c.TimeZone
}

func (c *CampaignWorkflow) GetCustomCPAClickWeight() *float64 {
	if c == nil {
		return nil
	}
	return c.CustomCPAClickWeight
}

func (c *CampaignWorkflow) GetCustomCPAViewthroughWeight() *float64 {
	if c == nil {
		return nil
	}
	return c.CustomCPAViewthroughWeight
}

func (c *CampaignWorkflow) GetCustomCPAType() *CustomCPAType {
	if c == nil {
		return nil
	}
	return c.CustomCPAType
}

func (c *CampaignWorkflow) GetImpressionsOnlyBudgetingCpm() *float64 {
	if c == nil {
		return nil
	}
	return c.ImpressionsOnlyBudgetingCpm
}

func (c *CampaignWorkflow) GetPrimaryChannel() *CampaignChannelType {
	if c == nil {
		return nil
	}
	return c.PrimaryChannel
}

func (c *CampaignWorkflow) GetPrimaryGoal() *string {
	if c == nil {
		return nil
	}
	return c.PrimaryGoal
}

func (c *CampaignWorkflow) GetSeedID() *string {
	if c == nil {
		return nil
	}
	return c.SeedID
}

func (c *CampaignWorkflow) GetConversionReportingColumnsCount() *int {
	if c == nil {
		return nil
	}
	return c.ConversionReportingColumnsCount
}

func (c *CampaignWorkflow) GetFlights() []CampaignFlightWorkflow {
	if c == nil {
		return nil
	}
	return c.Flights
}

func (c *CampaignWorkflow) GetSecondaryGoal() *string {
	if c == nil {
		return nil
	}
	return c.SecondaryGoal
}

func (c *CampaignWorkflow) GetTertiaryGoal() *string {
	if c == nil {
		return nil
	}
	return c.TertiaryGoal
}
