// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/thetradedesk/ttd-workflows-go/internal/utils"
	"time"
)

type CampaignUpdateWorkflowPrimaryInput struct {
	Description                        *string                                                  `json:"description,omitempty"`
	CampaignGroupID                    *int64                                                   `json:"campaignGroupId,omitempty"`
	TimeZone                           *string                                                  `json:"timeZone,omitempty"`
	CustomCPAClickWeight               *float64                                                 `json:"customCPAClickWeight,omitempty"`
	CustomCPAViewthroughWeight         *float64                                                 `json:"customCPAViewthroughWeight,omitempty"`
	CustomCPAType                      *CustomCPAType                                           `json:"customCPAType,omitempty"`
	CustomRoasType                     *CustomROASType                                          `json:"customRoasType,omitempty"`
	ImpressionsOnlyBudgetingCpm        *float64                                                 `json:"impressionsOnlyBudgetingCpm,omitempty"`
	Budget                             *CampaignWorkflowBudgetInput                             `json:"budget,omitempty"`
	EndDateInUtc                       *time.Time                                               `json:"endDateInUtc,omitempty"`
	SeedID                             *string                                                  `json:"seedId,omitempty"`
	CampaignConversionReportingColumns []CampaignWorkflowCampaignConversionReportingColumnInput `json:"campaignConversionReportingColumns,omitempty"`
	IsManagedByTTD                     *bool                                                    `json:"isManagedByTTD,omitempty"`
	SecondaryGoal                      *CampaignWorkflowROIGoalInput                            `json:"secondaryGoal,omitempty"`
	TertiaryGoal                       *CampaignWorkflowROIGoalInput                            `json:"tertiaryGoal,omitempty"`
	Name                               *string                                                  `json:"name,omitempty"`
	PrimaryChannel                     *CampaignChannelType                                     `json:"primaryChannel,omitempty"`
	PrimaryGoal                        *CampaignWorkflowROIGoalInput                            `json:"primaryGoal,omitempty"`
	StartDateInUtc                     *time.Time                                               `json:"startDateInUtc,omitempty"`
}

func (c CampaignUpdateWorkflowPrimaryInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CampaignUpdateWorkflowPrimaryInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetCampaignGroupID() *int64 {
	if c == nil {
		return nil
	}
	return c.CampaignGroupID
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetTimeZone() *string {
	if c == nil {
		return nil
	}
	return c.TimeZone
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetCustomCPAClickWeight() *float64 {
	if c == nil {
		return nil
	}
	return c.CustomCPAClickWeight
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetCustomCPAViewthroughWeight() *float64 {
	if c == nil {
		return nil
	}
	return c.CustomCPAViewthroughWeight
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetCustomCPAType() *CustomCPAType {
	if c == nil {
		return nil
	}
	return c.CustomCPAType
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetCustomRoasType() *CustomROASType {
	if c == nil {
		return nil
	}
	return c.CustomRoasType
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetImpressionsOnlyBudgetingCpm() *float64 {
	if c == nil {
		return nil
	}
	return c.ImpressionsOnlyBudgetingCpm
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetBudget() *CampaignWorkflowBudgetInput {
	if c == nil {
		return nil
	}
	return c.Budget
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetEndDateInUtc() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndDateInUtc
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetSeedID() *string {
	if c == nil {
		return nil
	}
	return c.SeedID
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetCampaignConversionReportingColumns() []CampaignWorkflowCampaignConversionReportingColumnInput {
	if c == nil {
		return nil
	}
	return c.CampaignConversionReportingColumns
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetIsManagedByTTD() *bool {
	if c == nil {
		return nil
	}
	return c.IsManagedByTTD
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetSecondaryGoal() *CampaignWorkflowROIGoalInput {
	if c == nil {
		return nil
	}
	return c.SecondaryGoal
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetTertiaryGoal() *CampaignWorkflowROIGoalInput {
	if c == nil {
		return nil
	}
	return c.TertiaryGoal
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetPrimaryChannel() *CampaignChannelType {
	if c == nil {
		return nil
	}
	return c.PrimaryChannel
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetPrimaryGoal() *CampaignWorkflowROIGoalInput {
	if c == nil {
		return nil
	}
	return c.PrimaryGoal
}

func (c *CampaignUpdateWorkflowPrimaryInput) GetStartDateInUtc() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartDateInUtc
}
