// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/thetradedesk/ttd-workflows-go/internal/utils"
	"time"
)

type CampaignFlightWorkflow struct {
	ID                              *string    `json:"id"`
	StartDateInclusiveUTC           time.Time  `json:"startDateInclusiveUTC"`
	EndDateExclusiveUTC             *time.Time `json:"endDateExclusiveUTC,omitempty"`
	BudgetInAdvertiserCurrency      float64    `json:"budgetInAdvertiserCurrency"`
	BudgetInImpressions             *int64     `json:"budgetInImpressions,omitempty"`
	DailyTargetInAdvertiserCurrency *float64   `json:"dailyTargetInAdvertiserCurrency,omitempty"`
	DailyTargetInImpressions        *int64     `json:"dailyTargetInImpressions,omitempty"`
}

func (c CampaignFlightWorkflow) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CampaignFlightWorkflow) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"startDateInclusiveUTC", "budgetInAdvertiserCurrency"}); err != nil {
		return err
	}
	return nil
}

func (c *CampaignFlightWorkflow) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CampaignFlightWorkflow) GetStartDateInclusiveUTC() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.StartDateInclusiveUTC
}

func (c *CampaignFlightWorkflow) GetEndDateExclusiveUTC() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndDateExclusiveUTC
}

func (c *CampaignFlightWorkflow) GetBudgetInAdvertiserCurrency() float64 {
	if c == nil {
		return 0.0
	}
	return c.BudgetInAdvertiserCurrency
}

func (c *CampaignFlightWorkflow) GetBudgetInImpressions() *int64 {
	if c == nil {
		return nil
	}
	return c.BudgetInImpressions
}

func (c *CampaignFlightWorkflow) GetDailyTargetInAdvertiserCurrency() *float64 {
	if c == nil {
		return nil
	}
	return c.DailyTargetInAdvertiserCurrency
}

func (c *CampaignFlightWorkflow) GetDailyTargetInImpressions() *int64 {
	if c == nil {
		return nil
	}
	return c.DailyTargetInImpressions
}
