// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignBulkCreateWorkflowInputWithValidation struct {
	Input             []CampaignCreateWorkflowInput `json:"input"`
	ValidateInputOnly *bool                         `json:"validateInputOnly,omitempty"`
	CallbackInput     *WorkflowCallbackInput        `json:"callbackInput,omitempty"`
}

func (c *CampaignBulkCreateWorkflowInputWithValidation) GetInput() []CampaignCreateWorkflowInput {
	if c == nil {
		return nil
	}
	return c.Input
}

func (c *CampaignBulkCreateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if c == nil {
		return nil
	}
	return c.ValidateInputOnly
}

func (c *CampaignBulkCreateWorkflowInputWithValidation) GetCallbackInput() *WorkflowCallbackInput {
	if c == nil {
		return nil
	}
	return c.CallbackInput
}
