// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignWorkflowAdvancedInput struct {
	Flights             []CampaignWorkflowFlightInput `json:"flights,omitempty"`
	PurchaseOrderNumber *string                       `json:"purchaseOrderNumber,omitempty"`
}

func (o *CampaignWorkflowAdvancedInput) GetFlights() []CampaignWorkflowFlightInput {
	if o == nil {
		return nil
	}
	return o.Flights
}

func (o *CampaignWorkflowAdvancedInput) GetPurchaseOrderNumber() *string {
	if o == nil {
		return nil
	}
	return o.PurchaseOrderNumber
}
