// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"time"
	"ttd-workflows/internal/utils"
)

type CampaignFlightWorkflow struct {
	ID                              *string    `json:"id"`
	StartDateInclusiveUTC           time.Time  `json:"startDateInclusiveUTC"`
	EndDateExclusiveUTC             *time.Time `json:"endDateExclusiveUTC,omitempty"`
	BudgetInAdvertiserCurrency      float64    `json:"budgetInAdvertiserCurrency"`
	BudgetInImpressions             *int64     `json:"budgetInImpressions,omitempty"`
	DailyTargetInAdvertiserCurrency *float64   `json:"dailyTargetInAdvertiserCurrency,omitempty"`
	DailyTargetInImpressions        *int64     `json:"dailyTargetInImpressions,omitempty"`
}

func (c CampaignFlightWorkflow) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CampaignFlightWorkflow) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CampaignFlightWorkflow) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CampaignFlightWorkflow) GetStartDateInclusiveUTC() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.StartDateInclusiveUTC
}

func (o *CampaignFlightWorkflow) GetEndDateExclusiveUTC() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndDateExclusiveUTC
}

func (o *CampaignFlightWorkflow) GetBudgetInAdvertiserCurrency() float64 {
	if o == nil {
		return 0.0
	}
	return o.BudgetInAdvertiserCurrency
}

func (o *CampaignFlightWorkflow) GetBudgetInImpressions() *int64 {
	if o == nil {
		return nil
	}
	return o.BudgetInImpressions
}

func (o *CampaignFlightWorkflow) GetDailyTargetInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.DailyTargetInAdvertiserCurrency
}

func (o *CampaignFlightWorkflow) GetDailyTargetInImpressions() *int64 {
	if o == nil {
		return nil
	}
	return o.DailyTargetInImpressions
}
