// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignBulkUpdateWorkflowInputWithValidation struct {
	Input             []CampaignUpdateWorkflowInput `json:"input"`
	ValidateInputOnly *bool                         `json:"validateInputOnly,omitempty"`
	CallbackInput     *WorkflowCallbackInput        `json:"callbackInput,omitempty"`
}

func (c *CampaignBulkUpdateWorkflowInputWithValidation) GetInput() []CampaignUpdateWorkflowInput {
	if c == nil {
		return nil
	}
	return c.Input
}

func (c *CampaignBulkUpdateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if c == nil {
		return nil
	}
	return c.ValidateInputOnly
}

func (c *CampaignBulkUpdateWorkflowInputWithValidation) GetCallbackInput() *WorkflowCallbackInput {
	if c == nil {
		return nil
	}
	return c.CallbackInput
}
