// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignCreateWorkflowAdGroupInput struct {
	PrimaryInput  AdGroupCreateWorkflowPrimaryInput           `json:"primaryInput"`
	AdvancedInput *CampaignCreateWorkflowAdGroupAdvancedInput `json:"advancedInput,omitempty"`
}

func (o *CampaignCreateWorkflowAdGroupInput) GetPrimaryInput() AdGroupCreateWorkflowPrimaryInput {
	if o == nil {
		return AdGroupCreateWorkflowPrimaryInput{}
	}
	return o.PrimaryInput
}

func (o *CampaignCreateWorkflowAdGroupInput) GetAdvancedInput() *CampaignCreateWorkflowAdGroupAdvancedInput {
	if o == nil {
		return nil
	}
	return o.AdvancedInput
}
