// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignCreateWorkflowInput struct {
	PrimaryInput  CampaignCreateWorkflowPrimaryInput   `json:"primaryInput"`
	AdvancedInput *CampaignCreateWorkflowAdvancedInput `json:"advancedInput,omitempty"`
	AdGroups      []CampaignCreateWorkflowAdGroupInput `json:"adGroups,omitempty"`
}

func (c *CampaignCreateWorkflowInput) GetPrimaryInput() CampaignCreateWorkflowPrimaryInput {
	if c == nil {
		return CampaignCreateWorkflowPrimaryInput{}
	}
	return c.PrimaryInput
}

func (c *CampaignCreateWorkflowInput) GetAdvancedInput() *CampaignCreateWorkflowAdvancedInput {
	if c == nil {
		return nil
	}
	return c.AdvancedInput
}

func (c *CampaignCreateWorkflowInput) GetAdGroups() []CampaignCreateWorkflowAdGroupInput {
	if c == nil {
		return nil
	}
	return c.AdGroups
}
