// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignUpdateWorkflowAdvancedInput struct {
	PurchaseOrderNumber *string `json:"purchaseOrderNumber,omitempty"`
}

func (c *CampaignUpdateWorkflowAdvancedInput) GetPurchaseOrderNumber() *string {
	if c == nil {
		return nil
	}
	return c.PurchaseOrderNumber
}
