// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignCreateWorkflowIncrementalReachCampaignSetting struct {
	ISpotReachSetting     *IncrementalReachBrandInput `json:"iSpotReachSetting,omitempty"`
	RealyticsReachSetting *RealyticsReachSettingInput `json:"realyticsReachSetting,omitempty"`
	TvSquaredReachSetting *IncrementalReachBrandInput `json:"tvSquaredReachSetting,omitempty"`
	SambaAuReachSetting   *IncrementalReachBrandInput `json:"sambaAuReachSetting,omitempty"`
}

func (c *CampaignCreateWorkflowIncrementalReachCampaignSetting) GetISpotReachSetting() *IncrementalReachBrandInput {
	if c == nil {
		return nil
	}
	return c.ISpotReachSetting
}

func (c *CampaignCreateWorkflowIncrementalReachCampaignSetting) GetRealyticsReachSetting() *RealyticsReachSettingInput {
	if c == nil {
		return nil
	}
	return c.RealyticsReachSetting
}

func (c *CampaignCreateWorkflowIncrementalReachCampaignSetting) GetTvSquaredReachSetting() *IncrementalReachBrandInput {
	if c == nil {
		return nil
	}
	return c.TvSquaredReachSetting
}

func (c *CampaignCreateWorkflowIncrementalReachCampaignSetting) GetSambaAuReachSetting() *IncrementalReachBrandInput {
	if c == nil {
		return nil
	}
	return c.SambaAuReachSetting
}
