// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignCreateWorkflowAdGroupAdvancedInput struct {
	KoaOptimizationSettings                    *AdGroupWorkflowKoaOptimizationSettingsInput   `json:"koaOptimizationSettings,omitempty"`
	ComscoreSettings                           *AdGroupWorkflowComscoreSettingsInput          `json:"comscoreSettings,omitempty"`
	ContractTargeting                          *AdGroupWorkflowContractTargetingInput         `json:"contractTargeting,omitempty"`
	DimensionalBiddingAutoOptimizationSettings [][]DimensionalBiddingDimensions               `json:"dimensionalBiddingAutoOptimizationSettings,omitempty"`
	IsUseClicksAsConversionsEnabled            *bool                                          `json:"isUseClicksAsConversionsEnabled,omitempty"`
	IsUseSecondaryConversionsEnabled           *bool                                          `json:"isUseSecondaryConversionsEnabled,omitempty"`
	NielsenTrackingAttributes                  *AdGroupWorkflowNielsenTrackingAttributesInput `json:"nielsenTrackingAttributes,omitempty"`
	NewFrequencyConfigs                        []AdGroupWorkflowNewFrequencyConfigInput       `json:"newFrequencyConfigs,omitempty"`
	Flights                                    []CampaignCreateWorkflowAdGroupFlightInput     `json:"flights,omitempty"`
}

func (o *CampaignCreateWorkflowAdGroupAdvancedInput) GetKoaOptimizationSettings() *AdGroupWorkflowKoaOptimizationSettingsInput {
	if o == nil {
		return nil
	}
	return o.KoaOptimizationSettings
}

func (o *CampaignCreateWorkflowAdGroupAdvancedInput) GetComscoreSettings() *AdGroupWorkflowComscoreSettingsInput {
	if o == nil {
		return nil
	}
	return o.ComscoreSettings
}

func (o *CampaignCreateWorkflowAdGroupAdvancedInput) GetContractTargeting() *AdGroupWorkflowContractTargetingInput {
	if o == nil {
		return nil
	}
	return o.ContractTargeting
}

func (o *CampaignCreateWorkflowAdGroupAdvancedInput) GetDimensionalBiddingAutoOptimizationSettings() [][]DimensionalBiddingDimensions {
	if o == nil {
		return nil
	}
	return o.DimensionalBiddingAutoOptimizationSettings
}

func (o *CampaignCreateWorkflowAdGroupAdvancedInput) GetIsUseClicksAsConversionsEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.IsUseClicksAsConversionsEnabled
}

func (o *CampaignCreateWorkflowAdGroupAdvancedInput) GetIsUseSecondaryConversionsEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.IsUseSecondaryConversionsEnabled
}

func (o *CampaignCreateWorkflowAdGroupAdvancedInput) GetNielsenTrackingAttributes() *AdGroupWorkflowNielsenTrackingAttributesInput {
	if o == nil {
		return nil
	}
	return o.NielsenTrackingAttributes
}

func (o *CampaignCreateWorkflowAdGroupAdvancedInput) GetNewFrequencyConfigs() []AdGroupWorkflowNewFrequencyConfigInput {
	if o == nil {
		return nil
	}
	return o.NewFrequencyConfigs
}

func (o *CampaignCreateWorkflowAdGroupAdvancedInput) GetFlights() []CampaignCreateWorkflowAdGroupFlightInput {
	if o == nil {
		return nil
	}
	return o.Flights
}
