// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignCreateWorkflowAdGroupFlightInput struct {
	AllocationType                  *AllocationType `json:"allocationType,omitempty"`
	BudgetInAdvertiserCurrency      *float64        `json:"budgetInAdvertiserCurrency,omitempty"`
	BudgetInImpressions             *int64          `json:"budgetInImpressions,omitempty"`
	DailyTargetInAdvertiserCurrency *float64        `json:"dailyTargetInAdvertiserCurrency,omitempty"`
	DailyTargetInImpressions        *int64          `json:"dailyTargetInImpressions,omitempty"`
}

func (c *CampaignCreateWorkflowAdGroupFlightInput) GetAllocationType() *AllocationType {
	if c == nil {
		return nil
	}
	return c.AllocationType
}

func (c *CampaignCreateWorkflowAdGroupFlightInput) GetBudgetInAdvertiserCurrency() *float64 {
	if c == nil {
		return nil
	}
	return c.BudgetInAdvertiserCurrency
}

func (c *CampaignCreateWorkflowAdGroupFlightInput) GetBudgetInImpressions() *int64 {
	if c == nil {
		return nil
	}
	return c.BudgetInImpressions
}

func (c *CampaignCreateWorkflowAdGroupFlightInput) GetDailyTargetInAdvertiserCurrency() *float64 {
	if c == nil {
		return nil
	}
	return c.DailyTargetInAdvertiserCurrency
}

func (c *CampaignCreateWorkflowAdGroupFlightInput) GetDailyTargetInImpressions() *int64 {
	if c == nil {
		return nil
	}
	return c.DailyTargetInImpressions
}
