// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignPayload struct {
	Campaign *CampaignWorkflow `json:"campaign,omitempty"`
	AdGroups []AdGroupWorkflow `json:"adGroups,omitempty"`
}

func (c *CampaignPayload) GetCampaign() *CampaignWorkflow {
	if c == nil {
		return nil
	}
	return c.Campaign
}

func (c *CampaignPayload) GetAdGroups() []AdGroupWorkflow {
	if c == nil {
		return nil
	}
	return c.AdGroups
}
