// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignPayload struct {
	Campaign *CampaignWorkflow `json:"campaign,omitempty"`
	AdGroups []AdGroupWorkflow `json:"adGroups,omitempty"`
}

func (o *CampaignPayload) GetCampaign() *CampaignWorkflow {
	if o == nil {
		return nil
	}
	return o.Campaign
}

func (o *CampaignPayload) GetAdGroups() []AdGroupWorkflow {
	if o == nil {
		return nil
	}
	return o.AdGroups
}
