// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignVersionWorkflow struct {
	ID               *string `json:"Id"`
	Version          *string `json:"version,omitempty"`
	BudgetingVersion *string `json:"budgetingVersion,omitempty"`
}

func (c *CampaignVersionWorkflow) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CampaignVersionWorkflow) GetVersion() *string {
	if c == nil {
		return nil
	}
	return c.Version
}

func (c *CampaignVersionWorkflow) GetBudgetingVersion() *string {
	if c == nil {
		return nil
	}
	return c.BudgetingVersion
}
