// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignUpdateWorkflowAdvancedInput struct {
	Flights             []CampaignWorkflowFlightInput `json:"flights,omitempty"`
	PurchaseOrderNumber *string                       `json:"purchaseOrderNumber,omitempty"`
}

func (c *CampaignUpdateWorkflowAdvancedInput) GetFlights() []CampaignWorkflowFlightInput {
	if c == nil {
		return nil
	}
	return c.Flights
}

func (c *CampaignUpdateWorkflowAdvancedInput) GetPurchaseOrderNumber() *string {
	if c == nil {
		return nil
	}
	return c.PurchaseOrderNumber
}
