// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignWorkflowROIGoalInput struct {
	MaximizeReach                             *bool    `json:"maximizeReach,omitempty"`
	MaximizeLtvIncrementalReach               *bool    `json:"maximizeLtvIncrementalReach,omitempty"`
	CpcInAdvertiserCurrency                   *float64 `json:"cpcInAdvertiserCurrency,omitempty"`
	CtrInPercent                              *float64 `json:"ctrInPercent,omitempty"`
	NielsenOTPInPercent                       *float64 `json:"nielsenOTPInPercent,omitempty"`
	CpaInAdvertiserCurrency                   *float64 `json:"cpaInAdvertiserCurrency,omitempty"`
	ReturnOnAdSpendPercent                    *float64 `json:"returnOnAdSpendPercent,omitempty"`
	VcrInPercent                              *float64 `json:"vcrInPercent,omitempty"`
	ViewabilityInPercent                      *float64 `json:"viewabilityInPercent,omitempty"`
	VcpmInAdvertiserCurrency                  *float64 `json:"vcpmInAdvertiserCurrency,omitempty"`
	CpcvInAdvertiserCurrency                  *float64 `json:"cpcvInAdvertiserCurrency,omitempty"`
	MiaozhenOTPInPercent                      *float64 `json:"miaozhenOTPInPercent,omitempty"`
	IqviaAudienceQualityIndex                 *bool    `json:"iqviaAudienceQualityIndex,omitempty"`
	CrossixAudienceQualityIndex               *bool    `json:"crossixAudienceQualityIndex,omitempty"`
	IqviaAudienceQualityIndexAndCostPerTarget *bool    `json:"iqviaAudienceQualityIndexAndCostPerTarget,omitempty"`
	CrossixCostPerTarget                      *bool    `json:"crossixCostPerTarget,omitempty"`
}

func (c *CampaignWorkflowROIGoalInput) GetMaximizeReach() *bool {
	if c == nil {
		return nil
	}
	return c.MaximizeReach
}

func (c *CampaignWorkflowROIGoalInput) GetMaximizeLtvIncrementalReach() *bool {
	if c == nil {
		return nil
	}
	return c.MaximizeLtvIncrementalReach
}

func (c *CampaignWorkflowROIGoalInput) GetCpcInAdvertiserCurrency() *float64 {
	if c == nil {
		return nil
	}
	return c.CpcInAdvertiserCurrency
}

func (c *CampaignWorkflowROIGoalInput) GetCtrInPercent() *float64 {
	if c == nil {
		return nil
	}
	return c.CtrInPercent
}

func (c *CampaignWorkflowROIGoalInput) GetNielsenOTPInPercent() *float64 {
	if c == nil {
		return nil
	}
	return c.NielsenOTPInPercent
}

func (c *CampaignWorkflowROIGoalInput) GetCpaInAdvertiserCurrency() *float64 {
	if c == nil {
		return nil
	}
	return c.CpaInAdvertiserCurrency
}

func (c *CampaignWorkflowROIGoalInput) GetReturnOnAdSpendPercent() *float64 {
	if c == nil {
		return nil
	}
	return c.ReturnOnAdSpendPercent
}

func (c *CampaignWorkflowROIGoalInput) GetVcrInPercent() *float64 {
	if c == nil {
		return nil
	}
	return c.VcrInPercent
}

func (c *CampaignWorkflowROIGoalInput) GetViewabilityInPercent() *float64 {
	if c == nil {
		return nil
	}
	return c.ViewabilityInPercent
}

func (c *CampaignWorkflowROIGoalInput) GetVcpmInAdvertiserCurrency() *float64 {
	if c == nil {
		return nil
	}
	return c.VcpmInAdvertiserCurrency
}

func (c *CampaignWorkflowROIGoalInput) GetCpcvInAdvertiserCurrency() *float64 {
	if c == nil {
		return nil
	}
	return c.CpcvInAdvertiserCurrency
}

func (c *CampaignWorkflowROIGoalInput) GetMiaozhenOTPInPercent() *float64 {
	if c == nil {
		return nil
	}
	return c.MiaozhenOTPInPercent
}

func (c *CampaignWorkflowROIGoalInput) GetIqviaAudienceQualityIndex() *bool {
	if c == nil {
		return nil
	}
	return c.IqviaAudienceQualityIndex
}

func (c *CampaignWorkflowROIGoalInput) GetCrossixAudienceQualityIndex() *bool {
	if c == nil {
		return nil
	}
	return c.CrossixAudienceQualityIndex
}

func (c *CampaignWorkflowROIGoalInput) GetIqviaAudienceQualityIndexAndCostPerTarget() *bool {
	if c == nil {
		return nil
	}
	return c.IqviaAudienceQualityIndexAndCostPerTarget
}

func (c *CampaignWorkflowROIGoalInput) GetCrossixCostPerTarget() *bool {
	if c == nil {
		return nil
	}
	return c.CrossixCostPerTarget
}
