// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignWorkflowCampaignConversionReportingColumnInput struct {
	TrackingTagID                 string            `json:"trackingTagId"`
	IncludeInCustomCPA            bool              `json:"includeInCustomCPA"`
	ReportingColumnID             int               `json:"reportingColumnId"`
	ROASConfig                    *CustomROASConfig `json:"ROASConfig,omitempty"`
	Weight                        *float64          `json:"weight,omitempty"`
	CrossDeviceAttributionModelID *string           `json:"crossDeviceAttributionModelId,omitempty"`
}

func (c *CampaignWorkflowCampaignConversionReportingColumnInput) GetTrackingTagID() string {
	if c == nil {
		return ""
	}
	return c.TrackingTagID
}

func (c *CampaignWorkflowCampaignConversionReportingColumnInput) GetIncludeInCustomCPA() bool {
	if c == nil {
		return false
	}
	return c.IncludeInCustomCPA
}

func (c *CampaignWorkflowCampaignConversionReportingColumnInput) GetReportingColumnID() int {
	if c == nil {
		return 0
	}
	return c.ReportingColumnID
}

func (c *CampaignWorkflowCampaignConversionReportingColumnInput) GetROASConfig() *CustomROASConfig {
	if c == nil {
		return nil
	}
	return c.ROASConfig
}

func (c *CampaignWorkflowCampaignConversionReportingColumnInput) GetWeight() *float64 {
	if c == nil {
		return nil
	}
	return c.Weight
}

func (c *CampaignWorkflowCampaignConversionReportingColumnInput) GetCrossDeviceAttributionModelID() *string {
	if c == nil {
		return nil
	}
	return c.CrossDeviceAttributionModelID
}
