// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/thetradedesk/ttd-workflows-go/internal/utils"
	"time"
)

type CampaignWorkflowFlightInput struct {
	StartDateInclusiveUTC           time.Time  `json:"startDateInclusiveUTC"`
	EndDateExclusiveUTC             *time.Time `json:"endDateExclusiveUTC,omitempty"`
	BudgetInAdvertiserCurrency      float64    `json:"budgetInAdvertiserCurrency"`
	BudgetInImpressions             *int64     `json:"budgetInImpressions,omitempty"`
	DailyTargetInAdvertiserCurrency *float64   `json:"dailyTargetInAdvertiserCurrency,omitempty"`
	DailyTargetInImpressions        *int64     `json:"dailyTargetInImpressions,omitempty"`
}

func (c CampaignWorkflowFlightInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CampaignWorkflowFlightInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CampaignWorkflowFlightInput) GetStartDateInclusiveUTC() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.StartDateInclusiveUTC
}

func (c *CampaignWorkflowFlightInput) GetEndDateExclusiveUTC() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndDateExclusiveUTC
}

func (c *CampaignWorkflowFlightInput) GetBudgetInAdvertiserCurrency() float64 {
	if c == nil {
		return 0.0
	}
	return c.BudgetInAdvertiserCurrency
}

func (c *CampaignWorkflowFlightInput) GetBudgetInImpressions() *int64 {
	if c == nil {
		return nil
	}
	return c.BudgetInImpressions
}

func (c *CampaignWorkflowFlightInput) GetDailyTargetInAdvertiserCurrency() *float64 {
	if c == nil {
		return nil
	}
	return c.DailyTargetInAdvertiserCurrency
}

func (c *CampaignWorkflowFlightInput) GetDailyTargetInImpressions() *int64 {
	if c == nil {
		return nil
	}
	return c.DailyTargetInImpressions
}
