// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignBulkUpdateWorkflowInputWithValidation struct {
	Input             []CampaignUpdateWorkflowInput `json:"input"`
	ValidateInputOnly *bool                         `json:"validateInputOnly,omitempty"`
	CallbackInput     *WorkflowCallbackInput        `json:"callbackInput,omitempty"`
}

func (o *CampaignBulkUpdateWorkflowInputWithValidation) GetInput() []CampaignUpdateWorkflowInput {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *CampaignBulkUpdateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if o == nil {
		return nil
	}
	return o.ValidateInputOnly
}

func (o *CampaignBulkUpdateWorkflowInputWithValidation) GetCallbackInput() *WorkflowCallbackInput {
	if o == nil {
		return nil
	}
	return o.CallbackInput
}
