// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignCreateWorkflowInputWithValidation struct {
	PrimaryInput      CampaignCreateWorkflowPrimaryInput   `json:"primaryInput"`
	AdvancedInput     *CampaignWorkflowAdvancedInput       `json:"advancedInput,omitempty"`
	AdGroups          []CampaignCreateWorkflowAdGroupInput `json:"adGroups,omitempty"`
	ValidateInputOnly *bool                                `json:"validateInputOnly,omitempty"`
}

func (o *CampaignCreateWorkflowInputWithValidation) GetPrimaryInput() CampaignCreateWorkflowPrimaryInput {
	if o == nil {
		return CampaignCreateWorkflowPrimaryInput{}
	}
	return o.PrimaryInput
}

func (o *CampaignCreateWorkflowInputWithValidation) GetAdvancedInput() *CampaignWorkflowAdvancedInput {
	if o == nil {
		return nil
	}
	return o.AdvancedInput
}

func (o *CampaignCreateWorkflowInputWithValidation) GetAdGroups() []CampaignCreateWorkflowAdGroupInput {
	if o == nil {
		return nil
	}
	return o.AdGroups
}

func (o *CampaignCreateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if o == nil {
		return nil
	}
	return o.ValidateInputOnly
}
