// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignCreateWorkflowAdvancedInput struct {
	Flights                       []CampaignWorkflowFlightInput                  `json:"flights,omitempty"`
	PurchaseOrderNumber           *string                                        `json:"purchaseOrderNumber,omitempty"`
	IncludeDefaultsFromAdvertiser *bool                                          `json:"includeDefaultsFromAdvertiser,omitempty"`
	PassThroughFeeCard            *CampaignCreateWorkflowPassThroughFeeCardInput `json:"passThroughFeeCard,omitempty"`
}

func (c *CampaignCreateWorkflowAdvancedInput) GetFlights() []CampaignWorkflowFlightInput {
	if c == nil {
		return nil
	}
	return c.Flights
}

func (c *CampaignCreateWorkflowAdvancedInput) GetPurchaseOrderNumber() *string {
	if c == nil {
		return nil
	}
	return c.PurchaseOrderNumber
}

func (c *CampaignCreateWorkflowAdvancedInput) GetIncludeDefaultsFromAdvertiser() *bool {
	if c == nil {
		return nil
	}
	return c.IncludeDefaultsFromAdvertiser
}

func (c *CampaignCreateWorkflowAdvancedInput) GetPassThroughFeeCard() *CampaignCreateWorkflowPassThroughFeeCardInput {
	if c == nil {
		return nil
	}
	return c.PassThroughFeeCard
}
