// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignUpdateWorkflowInputWithValidation struct {
	ID                *string                             `json:"id"`
	PrimaryInput      *CampaignUpdateWorkflowPrimaryInput `json:"primaryInput,omitempty"`
	AdvancedInput     *CampaignWorkflowAdvancedInput      `json:"advancedInput,omitempty"`
	ValidateInputOnly *bool                               `json:"validateInputOnly,omitempty"`
}

func (o *CampaignUpdateWorkflowInputWithValidation) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CampaignUpdateWorkflowInputWithValidation) GetPrimaryInput() *CampaignUpdateWorkflowPrimaryInput {
	if o == nil {
		return nil
	}
	return o.PrimaryInput
}

func (o *CampaignUpdateWorkflowInputWithValidation) GetAdvancedInput() *CampaignWorkflowAdvancedInput {
	if o == nil {
		return nil
	}
	return o.AdvancedInput
}

func (o *CampaignUpdateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if o == nil {
		return nil
	}
	return o.ValidateInputOnly
}
