// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignUpdateWorkflowInput struct {
	ID            *string                             `json:"id"`
	PrimaryInput  *CampaignUpdateWorkflowPrimaryInput `json:"primaryInput,omitempty"`
	AdvancedInput *CampaignWorkflowAdvancedInput      `json:"advancedInput,omitempty"`
}

func (o *CampaignUpdateWorkflowInput) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CampaignUpdateWorkflowInput) GetPrimaryInput() *CampaignUpdateWorkflowPrimaryInput {
	if o == nil {
		return nil
	}
	return o.PrimaryInput
}

func (o *CampaignUpdateWorkflowInput) GetAdvancedInput() *CampaignWorkflowAdvancedInput {
	if o == nil {
		return nil
	}
	return o.AdvancedInput
}
