// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type CampaignPacingMode string

const (
	CampaignPacingModePaceAhead            CampaignPacingMode = "PaceAhead"
	CampaignPacingModePaceEvenly           CampaignPacingMode = "PaceEvenly"
	CampaignPacingModePaceToDailyCap       CampaignPacingMode = "PaceToDailyCap"
	CampaignPacingModePaceAsSoonAsPossible CampaignPacingMode = "PaceAsSoonAsPossible"
)

func (e CampaignPacingMode) ToPointer() *CampaignPacingMode {
	return &e
}
func (e *CampaignPacingMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PaceAhead":
		fallthrough
	case "PaceEvenly":
		fallthrough
	case "PaceToDailyCap":
		fallthrough
	case "PaceAsSoonAsPossible":
		*e = CampaignPacingMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CampaignPacingMode: %v", v)
	}
}
