// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type CampaignChannelType string

const (
	CampaignChannelTypeNone          CampaignChannelType = "None"
	CampaignChannelTypeDisplay       CampaignChannelType = "Display"
	CampaignChannelTypeVideo         CampaignChannelType = "Video"
	CampaignChannelTypeAudio         CampaignChannelType = "Audio"
	CampaignChannelTypeTv            CampaignChannelType = "TV"
	CampaignChannelTypeNativeDisplay CampaignChannelType = "NativeDisplay"
	CampaignChannelTypeNativeVideo   CampaignChannelType = "NativeVideo"
	CampaignChannelTypeDooh          CampaignChannelType = "DOOH"
)

func (e CampaignChannelType) ToPointer() *CampaignChannelType {
	return &e
}
func (e *CampaignChannelType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "None":
		fallthrough
	case "Display":
		fallthrough
	case "Video":
		fallthrough
	case "Audio":
		fallthrough
	case "TV":
		fallthrough
	case "NativeDisplay":
		fallthrough
	case "NativeVideo":
		fallthrough
	case "DOOH":
		*e = CampaignChannelType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CampaignChannelType: %v", v)
	}
}
