// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignCreateWorkflowAdvancedInput struct {
	PurchaseOrderNumber           *string                                        `json:"purchaseOrderNumber,omitempty"`
	Flights                       []CampaignWorkflowFlightInput                  `json:"flights,omitempty"`
	IncludeDefaultsFromAdvertiser *bool                                          `json:"includeDefaultsFromAdvertiser,omitempty"`
	PassThroughFeeCard            *CampaignCreateWorkflowPassThroughFeeCardInput `json:"passThroughFeeCard,omitempty"`
	CallerSource                  *string                                        `json:"callerSource,omitempty"`
	FrequencyConfigs              []FrequencyConfig                              `json:"frequencyConfigs,omitempty"`
}

func (c *CampaignCreateWorkflowAdvancedInput) GetPurchaseOrderNumber() *string {
	if c == nil {
		return nil
	}
	return c.PurchaseOrderNumber
}

func (c *CampaignCreateWorkflowAdvancedInput) GetFlights() []CampaignWorkflowFlightInput {
	if c == nil {
		return nil
	}
	return c.Flights
}

func (c *CampaignCreateWorkflowAdvancedInput) GetIncludeDefaultsFromAdvertiser() *bool {
	if c == nil {
		return nil
	}
	return c.IncludeDefaultsFromAdvertiser
}

func (c *CampaignCreateWorkflowAdvancedInput) GetPassThroughFeeCard() *CampaignCreateWorkflowPassThroughFeeCardInput {
	if c == nil {
		return nil
	}
	return c.PassThroughFeeCard
}

func (c *CampaignCreateWorkflowAdvancedInput) GetCallerSource() *string {
	if c == nil {
		return nil
	}
	return c.CallerSource
}

func (c *CampaignCreateWorkflowAdvancedInput) GetFrequencyConfigs() []FrequencyConfig {
	if c == nil {
		return nil
	}
	return c.FrequencyConfigs
}
