// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignUpdateWorkflowInput struct {
	ID            *string                              `json:"id"`
	PrimaryInput  *CampaignUpdateWorkflowPrimaryInput  `json:"primaryInput,omitempty"`
	AdvancedInput *CampaignUpdateWorkflowAdvancedInput `json:"advancedInput,omitempty"`
}

func (c *CampaignUpdateWorkflowInput) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CampaignUpdateWorkflowInput) GetPrimaryInput() *CampaignUpdateWorkflowPrimaryInput {
	if c == nil {
		return nil
	}
	return c.PrimaryInput
}

func (c *CampaignUpdateWorkflowInput) GetAdvancedInput() *CampaignUpdateWorkflowAdvancedInput {
	if c == nil {
		return nil
	}
	return c.AdvancedInput
}
