// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignCreateWorkflowInput struct {
	PrimaryInput  CampaignCreateWorkflowPrimaryInput   `json:"primaryInput"`
	AdvancedInput *CampaignWorkflowAdvancedInput       `json:"advancedInput,omitempty"`
	AdGroups      []CampaignCreateWorkflowAdGroupInput `json:"adGroups,omitempty"`
}

func (o *CampaignCreateWorkflowInput) GetPrimaryInput() CampaignCreateWorkflowPrimaryInput {
	if o == nil {
		return CampaignCreateWorkflowPrimaryInput{}
	}
	return o.PrimaryInput
}

func (o *CampaignCreateWorkflowInput) GetAdvancedInput() *CampaignWorkflowAdvancedInput {
	if o == nil {
		return nil
	}
	return o.AdvancedInput
}

func (o *CampaignCreateWorkflowInput) GetAdGroups() []CampaignCreateWorkflowAdGroupInput {
	if o == nil {
		return nil
	}
	return o.AdGroups
}
