// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignBulkCreateWorkflowInputWithValidation struct {
	Input             []CampaignCreateWorkflowInput `json:"input"`
	ValidateInputOnly *bool                         `json:"validateInputOnly,omitempty"`
	CallbackInput     *WorkflowCallbackInput        `json:"callbackInput,omitempty"`
}

func (o *CampaignBulkCreateWorkflowInputWithValidation) GetInput() []CampaignCreateWorkflowInput {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *CampaignBulkCreateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if o == nil {
		return nil
	}
	return o.ValidateInputOnly
}

func (o *CampaignBulkCreateWorkflowInputWithValidation) GetCallbackInput() *WorkflowCallbackInput {
	if o == nil {
		return nil
	}
	return o.CallbackInput
}
