// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/thetradedesk/ttd-workflows-go/internal/utils"
	"time"
)

type CampaignUpdateWorkflowPrimaryInput struct {
	Description                        *string                                                  `json:"description,omitempty"`
	CampaignGroupID                    *int64                                                   `json:"campaignGroupId,omitempty"`
	TimeZone                           *string                                                  `json:"timeZone,omitempty"`
	CustomCPAClickWeight               *float64                                                 `json:"customCPAClickWeight,omitempty"`
	CustomCPAViewthroughWeight         *float64                                                 `json:"customCPAViewthroughWeight,omitempty"`
	CustomCPAType                      *CustomCPAType                                           `json:"customCPAType,omitempty"`
	ImpressionsOnlyBudgetingCpm        *float64                                                 `json:"impressionsOnlyBudgetingCpm,omitempty"`
	Budget                             *CampaignWorkflowBudgetInput                             `json:"budget,omitempty"`
	EndDateInUtc                       *time.Time                                               `json:"endDateInUtc,omitempty"`
	SeedID                             *string                                                  `json:"seedId,omitempty"`
	CampaignConversionReportingColumns []CampaignWorkflowCampaignConversionReportingColumnInput `json:"campaignConversionReportingColumns,omitempty"`
	Name                               *string                                                  `json:"name,omitempty"`
	PrimaryChannel                     *CampaignChannelType                                     `json:"primaryChannel,omitempty"`
	PrimaryGoal                        *CampaignWorkflowROIGoalInput                            `json:"primaryGoal,omitempty"`
	StartDateInUtc                     *time.Time                                               `json:"startDateInUtc,omitempty"`
}

func (c CampaignUpdateWorkflowPrimaryInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CampaignUpdateWorkflowPrimaryInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetCampaignGroupID() *int64 {
	if o == nil {
		return nil
	}
	return o.CampaignGroupID
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetTimeZone() *string {
	if o == nil {
		return nil
	}
	return o.TimeZone
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetCustomCPAClickWeight() *float64 {
	if o == nil {
		return nil
	}
	return o.CustomCPAClickWeight
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetCustomCPAViewthroughWeight() *float64 {
	if o == nil {
		return nil
	}
	return o.CustomCPAViewthroughWeight
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetCustomCPAType() *CustomCPAType {
	if o == nil {
		return nil
	}
	return o.CustomCPAType
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetImpressionsOnlyBudgetingCpm() *float64 {
	if o == nil {
		return nil
	}
	return o.ImpressionsOnlyBudgetingCpm
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetBudget() *CampaignWorkflowBudgetInput {
	if o == nil {
		return nil
	}
	return o.Budget
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetEndDateInUtc() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndDateInUtc
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetSeedID() *string {
	if o == nil {
		return nil
	}
	return o.SeedID
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetCampaignConversionReportingColumns() []CampaignWorkflowCampaignConversionReportingColumnInput {
	if o == nil {
		return nil
	}
	return o.CampaignConversionReportingColumns
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetPrimaryChannel() *CampaignChannelType {
	if o == nil {
		return nil
	}
	return o.PrimaryChannel
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetPrimaryGoal() *CampaignWorkflowROIGoalInput {
	if o == nil {
		return nil
	}
	return o.PrimaryGoal
}

func (o *CampaignUpdateWorkflowPrimaryInput) GetStartDateInUtc() *time.Time {
	if o == nil {
		return nil
	}
	return o.StartDateInUtc
}
