// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignCreateWorkflowAdGroupInput struct {
	PrimaryInput  AdGroupCreateWorkflowPrimaryInput           `json:"primaryInput"`
	AdvancedInput *CampaignCreateWorkflowAdGroupAdvancedInput `json:"advancedInput,omitempty"`
}

func (c *CampaignCreateWorkflowAdGroupInput) GetPrimaryInput() AdGroupCreateWorkflowPrimaryInput {
	if c == nil {
		return AdGroupCreateWorkflowPrimaryInput{}
	}
	return c.PrimaryInput
}

func (c *CampaignCreateWorkflowAdGroupInput) GetAdvancedInput() *CampaignCreateWorkflowAdGroupAdvancedInput {
	if c == nil {
		return nil
	}
	return c.AdvancedInput
}
