// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignWorkflowBudgetInput struct {
	PacingMode                      CampaignPacingMode `json:"pacingMode"`
	BudgetInAdvertiserCurrency      float64            `json:"budgetInAdvertiserCurrency"`
	BudgetInImpressions             *int64             `json:"budgetInImpressions,omitempty"`
	DailyTargetInAdvertiserCurrency *float64           `json:"dailyTargetInAdvertiserCurrency,omitempty"`
	DailyTargetInImpressions        *int64             `json:"dailyTargetInImpressions,omitempty"`
}

func (c *CampaignWorkflowBudgetInput) GetPacingMode() CampaignPacingMode {
	if c == nil {
		return CampaignPacingMode("")
	}
	return c.PacingMode
}

func (c *CampaignWorkflowBudgetInput) GetBudgetInAdvertiserCurrency() float64 {
	if c == nil {
		return 0.0
	}
	return c.BudgetInAdvertiserCurrency
}

func (c *CampaignWorkflowBudgetInput) GetBudgetInImpressions() *int64 {
	if c == nil {
		return nil
	}
	return c.BudgetInImpressions
}

func (c *CampaignWorkflowBudgetInput) GetDailyTargetInAdvertiserCurrency() *float64 {
	if c == nil {
		return nil
	}
	return c.DailyTargetInAdvertiserCurrency
}

func (c *CampaignWorkflowBudgetInput) GetDailyTargetInImpressions() *int64 {
	if c == nil {
		return nil
	}
	return c.DailyTargetInImpressions
}
