// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/thetradedesk/ttd-workflows-go/internal/utils"
	"time"
)

type CampaignCreateWorkflowPrimaryInput struct {
	Description                        *string                                                  `json:"description,omitempty"`
	CampaignGroupID                    *int64                                                   `json:"campaignGroupId,omitempty"`
	TimeZone                           *string                                                  `json:"timeZone,omitempty"`
	CustomCPAClickWeight               *float64                                                 `json:"customCPAClickWeight,omitempty"`
	CustomCPAViewthroughWeight         *float64                                                 `json:"customCPAViewthroughWeight,omitempty"`
	CustomCPAType                      *CustomCPAType                                           `json:"customCPAType,omitempty"`
	CustomRoasType                     *CustomROASType                                          `json:"customRoasType,omitempty"`
	ImpressionsOnlyBudgetingCpm        *float64                                                 `json:"impressionsOnlyBudgetingCpm,omitempty"`
	Budget                             *CampaignWorkflowBudgetInput                             `json:"budget,omitempty"`
	EndDateInUtc                       *time.Time                                               `json:"endDateInUtc,omitempty"`
	SeedID                             *string                                                  `json:"seedId,omitempty"`
	CampaignConversionReportingColumns []CampaignWorkflowCampaignConversionReportingColumnInput `json:"campaignConversionReportingColumns,omitempty"`
	IsManagedByTTD                     *bool                                                    `json:"isManagedByTTD,omitempty"`
	SecondaryGoal                      *CampaignWorkflowROIGoalInput                            `json:"secondaryGoal,omitempty"`
	TertiaryGoal                       *CampaignWorkflowROIGoalInput                            `json:"tertiaryGoal,omitempty"`
	AdvertiserID                       string                                                   `json:"advertiserId"`
	Name                               string                                                   `json:"name"`
	PrimaryChannel                     CampaignChannelType                                      `json:"primaryChannel"`
	PrimaryGoal                        CampaignWorkflowROIGoalInput                             `json:"primaryGoal"`
	StartDateInUtc                     *time.Time                                               `json:"startDateInUtc,omitempty"`
	CampaignIncrementalReachSetting    *CampaignCreateWorkflowIncrementalReachCampaignSetting   `json:"campaignIncrementalReachSetting,omitempty"`
}

func (c CampaignCreateWorkflowPrimaryInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CampaignCreateWorkflowPrimaryInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"advertiserId", "name", "primaryChannel", "primaryGoal"}); err != nil {
		return err
	}
	return nil
}

func (c *CampaignCreateWorkflowPrimaryInput) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CampaignCreateWorkflowPrimaryInput) GetCampaignGroupID() *int64 {
	if c == nil {
		return nil
	}
	return c.CampaignGroupID
}

func (c *CampaignCreateWorkflowPrimaryInput) GetTimeZone() *string {
	if c == nil {
		return nil
	}
	return c.TimeZone
}

func (c *CampaignCreateWorkflowPrimaryInput) GetCustomCPAClickWeight() *float64 {
	if c == nil {
		return nil
	}
	return c.CustomCPAClickWeight
}

func (c *CampaignCreateWorkflowPrimaryInput) GetCustomCPAViewthroughWeight() *float64 {
	if c == nil {
		return nil
	}
	return c.CustomCPAViewthroughWeight
}

func (c *CampaignCreateWorkflowPrimaryInput) GetCustomCPAType() *CustomCPAType {
	if c == nil {
		return nil
	}
	return c.CustomCPAType
}

func (c *CampaignCreateWorkflowPrimaryInput) GetCustomRoasType() *CustomROASType {
	if c == nil {
		return nil
	}
	return c.CustomRoasType
}

func (c *CampaignCreateWorkflowPrimaryInput) GetImpressionsOnlyBudgetingCpm() *float64 {
	if c == nil {
		return nil
	}
	return c.ImpressionsOnlyBudgetingCpm
}

func (c *CampaignCreateWorkflowPrimaryInput) GetBudget() *CampaignWorkflowBudgetInput {
	if c == nil {
		return nil
	}
	return c.Budget
}

func (c *CampaignCreateWorkflowPrimaryInput) GetEndDateInUtc() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndDateInUtc
}

func (c *CampaignCreateWorkflowPrimaryInput) GetSeedID() *string {
	if c == nil {
		return nil
	}
	return c.SeedID
}

func (c *CampaignCreateWorkflowPrimaryInput) GetCampaignConversionReportingColumns() []CampaignWorkflowCampaignConversionReportingColumnInput {
	if c == nil {
		return nil
	}
	return c.CampaignConversionReportingColumns
}

func (c *CampaignCreateWorkflowPrimaryInput) GetIsManagedByTTD() *bool {
	if c == nil {
		return nil
	}
	return c.IsManagedByTTD
}

func (c *CampaignCreateWorkflowPrimaryInput) GetSecondaryGoal() *CampaignWorkflowROIGoalInput {
	if c == nil {
		return nil
	}
	return c.SecondaryGoal
}

func (c *CampaignCreateWorkflowPrimaryInput) GetTertiaryGoal() *CampaignWorkflowROIGoalInput {
	if c == nil {
		return nil
	}
	return c.TertiaryGoal
}

func (c *CampaignCreateWorkflowPrimaryInput) GetAdvertiserID() string {
	if c == nil {
		return ""
	}
	return c.AdvertiserID
}

func (c *CampaignCreateWorkflowPrimaryInput) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CampaignCreateWorkflowPrimaryInput) GetPrimaryChannel() CampaignChannelType {
	if c == nil {
		return CampaignChannelType("")
	}
	return c.PrimaryChannel
}

func (c *CampaignCreateWorkflowPrimaryInput) GetPrimaryGoal() CampaignWorkflowROIGoalInput {
	if c == nil {
		return CampaignWorkflowROIGoalInput{}
	}
	return c.PrimaryGoal
}

func (c *CampaignCreateWorkflowPrimaryInput) GetStartDateInUtc() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartDateInUtc
}

func (c *CampaignCreateWorkflowPrimaryInput) GetCampaignIncrementalReachSetting() *CampaignCreateWorkflowIncrementalReachCampaignSetting {
	if c == nil {
		return nil
	}
	return c.CampaignIncrementalReachSetting
}
