// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignCreateWorkflowAdGroupFlightInput struct {
	AllocationType                  *AllocationType `json:"allocationType,omitempty"`
	BudgetInAdvertiserCurrency      *float64        `json:"budgetInAdvertiserCurrency,omitempty"`
	BudgetInImpressions             *int64          `json:"budgetInImpressions,omitempty"`
	DailyTargetInAdvertiserCurrency *float64        `json:"dailyTargetInAdvertiserCurrency,omitempty"`
	DailyTargetInImpressions        *int64          `json:"dailyTargetInImpressions,omitempty"`
}

func (o *CampaignCreateWorkflowAdGroupFlightInput) GetAllocationType() *AllocationType {
	if o == nil {
		return nil
	}
	return o.AllocationType
}

func (o *CampaignCreateWorkflowAdGroupFlightInput) GetBudgetInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.BudgetInAdvertiserCurrency
}

func (o *CampaignCreateWorkflowAdGroupFlightInput) GetBudgetInImpressions() *int64 {
	if o == nil {
		return nil
	}
	return o.BudgetInImpressions
}

func (o *CampaignCreateWorkflowAdGroupFlightInput) GetDailyTargetInAdvertiserCurrency() *float64 {
	if o == nil {
		return nil
	}
	return o.DailyTargetInAdvertiserCurrency
}

func (o *CampaignCreateWorkflowAdGroupFlightInput) GetDailyTargetInImpressions() *int64 {
	if o == nil {
		return nil
	}
	return o.DailyTargetInImpressions
}
