// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignCreatePassThroughFeesInput struct {
	Type        *PassThroughFeeType `json:"type,omitempty"`
	Description *string             `json:"description,omitempty"`
	Amount      *float64            `json:"amount,omitempty"`
}

func (c *CampaignCreatePassThroughFeesInput) GetType() *PassThroughFeeType {
	if c == nil {
		return nil
	}
	return c.Type
}

func (c *CampaignCreatePassThroughFeesInput) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CampaignCreatePassThroughFeesInput) GetAmount() *float64 {
	if c == nil {
		return nil
	}
	return c.Amount
}
