// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignVersionWorkflow struct {
	ID               *string `json:"Id"`
	Version          *string `json:"version,omitempty"`
	BudgetingVersion *string `json:"budgetingVersion,omitempty"`
}

func (o *CampaignVersionWorkflow) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CampaignVersionWorkflow) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *CampaignVersionWorkflow) GetBudgetingVersion() *string {
	if o == nil {
		return nil
	}
	return o.BudgetingVersion
}
