// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignUpdateWorkflowBudgetInput struct {
	PacingMode CampaignPacingMode `json:"pacingMode"`
}

func (c *CampaignUpdateWorkflowBudgetInput) GetPacingMode() CampaignPacingMode {
	if c == nil {
		return CampaignPacingMode("")
	}
	return c.PacingMode
}
