// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/thetradedesk/ttd-workflows-go/internal/utils"
	"time"
)

type CampaignWorkflow struct {
	ID                              *string                  `json:"id"`
	Name                            *string                  `json:"name,omitempty"`
	Description                     *string                  `json:"description,omitempty"`
	StartDate                       *time.Time               `json:"startDate,omitempty"`
	EndDate                         *time.Time               `json:"endDate,omitempty"`
	TimeZone                        *string                  `json:"timeZone,omitempty"`
	CustomCPAClickWeight            *float64                 `json:"customCPAClickWeight,omitempty"`
	CustomCPAViewthroughWeight      *float64                 `json:"customCPAViewthroughWeight,omitempty"`
	CustomCPAType                   *CustomCPAType           `json:"customCPAType,omitempty"`
	ImpressionsOnlyBudgetingCpm     *float64                 `json:"impressionsOnlyBudgetingCpm,omitempty"`
	PrimaryChannel                  *CampaignChannelType     `json:"primaryChannel,omitempty"`
	PrimaryGoal                     *string                  `json:"primaryGoal,omitempty"`
	SeedID                          *string                  `json:"seedId,omitempty"`
	ConversionReportingColumnsCount *int                     `json:"conversionReportingColumnsCount,omitempty"`
	Flights                         []CampaignFlightWorkflow `json:"flights,omitempty"`
}

func (c CampaignWorkflow) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CampaignWorkflow) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CampaignWorkflow) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CampaignWorkflow) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CampaignWorkflow) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CampaignWorkflow) GetStartDate() *time.Time {
	if o == nil {
		return nil
	}
	return o.StartDate
}

func (o *CampaignWorkflow) GetEndDate() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndDate
}

func (o *CampaignWorkflow) GetTimeZone() *string {
	if o == nil {
		return nil
	}
	return o.TimeZone
}

func (o *CampaignWorkflow) GetCustomCPAClickWeight() *float64 {
	if o == nil {
		return nil
	}
	return o.CustomCPAClickWeight
}

func (o *CampaignWorkflow) GetCustomCPAViewthroughWeight() *float64 {
	if o == nil {
		return nil
	}
	return o.CustomCPAViewthroughWeight
}

func (o *CampaignWorkflow) GetCustomCPAType() *CustomCPAType {
	if o == nil {
		return nil
	}
	return o.CustomCPAType
}

func (o *CampaignWorkflow) GetImpressionsOnlyBudgetingCpm() *float64 {
	if o == nil {
		return nil
	}
	return o.ImpressionsOnlyBudgetingCpm
}

func (o *CampaignWorkflow) GetPrimaryChannel() *CampaignChannelType {
	if o == nil {
		return nil
	}
	return o.PrimaryChannel
}

func (o *CampaignWorkflow) GetPrimaryGoal() *string {
	if o == nil {
		return nil
	}
	return o.PrimaryGoal
}

func (o *CampaignWorkflow) GetSeedID() *string {
	if o == nil {
		return nil
	}
	return o.SeedID
}

func (o *CampaignWorkflow) GetConversionReportingColumnsCount() *int {
	if o == nil {
		return nil
	}
	return o.ConversionReportingColumnsCount
}

func (o *CampaignWorkflow) GetFlights() []CampaignFlightWorkflow {
	if o == nil {
		return nil
	}
	return o.Flights
}
