// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CampaignUpdateWorkflowInputWithValidation struct {
	ID                *string                              `json:"id"`
	PrimaryInput      *CampaignUpdateWorkflowPrimaryInput  `json:"primaryInput,omitempty"`
	AdvancedInput     *CampaignUpdateWorkflowAdvancedInput `json:"advancedInput,omitempty"`
	ValidateInputOnly *bool                                `json:"validateInputOnly,omitempty"`
}

func (c *CampaignUpdateWorkflowInputWithValidation) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CampaignUpdateWorkflowInputWithValidation) GetPrimaryInput() *CampaignUpdateWorkflowPrimaryInput {
	if c == nil {
		return nil
	}
	return c.PrimaryInput
}

func (c *CampaignUpdateWorkflowInputWithValidation) GetAdvancedInput() *CampaignUpdateWorkflowAdvancedInput {
	if c == nil {
		return nil
	}
	return c.AdvancedInput
}

func (c *CampaignUpdateWorkflowInputWithValidation) GetValidateInputOnly() *bool {
	if c == nil {
		return nil
	}
	return c.ValidateInputOnly
}
