// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ContentTransparency string

const (
	ContentTransparencyNonTransparent ContentTransparency = "NonTransparent"
	ContentTransparencyTransparent    ContentTransparency = "Transparent"
)

func (e ContentTransparency) ToPointer() *ContentTransparency {
	return &e
}
func (e *ContentTransparency) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NonTransparent":
		fallthrough
	case "Transparent":
		*e = ContentTransparency(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContentTransparency: %v", v)
	}
}
