// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ContentDuration string

const (
	ContentDurationUnknown                 ContentDuration = "Unknown"
	ContentDurationLessThan15Minutes       ContentDuration = "LessThan15Minutes"
	ContentDurationBetween15And30Minutes   ContentDuration = "Between15And30Minutes"
	ContentDurationBetween30And45Minutes   ContentDuration = "Between30And45Minutes"
	ContentDurationBetween45And60Minutes   ContentDuration = "Between45And60Minutes"
	ContentDurationBetween60And75Minutes   ContentDuration = "Between60And75Minutes"
	ContentDurationBetween75And90Minutes   ContentDuration = "Between75And90Minutes"
	ContentDurationBetween90And105Minutes  ContentDuration = "Between90And105Minutes"
	ContentDurationBetween105And120Minutes ContentDuration = "Between105And120Minutes"
	ContentDurationMoreThan120Minutes      ContentDuration = "MoreThan120Minutes"
)

func (e ContentDuration) ToPointer() *ContentDuration {
	return &e
}
func (e *ContentDuration) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "LessThan15Minutes":
		fallthrough
	case "Between15And30Minutes":
		fallthrough
	case "Between30And45Minutes":
		fallthrough
	case "Between45And60Minutes":
		fallthrough
	case "Between60And75Minutes":
		fallthrough
	case "Between75And90Minutes":
		fallthrough
	case "Between90And105Minutes":
		fallthrough
	case "Between105And120Minutes":
		fallthrough
	case "MoreThan120Minutes":
		*e = ContentDuration(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContentDuration: %v", v)
	}
}
