// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CustomROASConfig struct {
	IncludeInCustomROAS         bool     `json:"includeInCustomROAS"`
	CustomROASWeight            *float64 `json:"customROASWeight,omitempty"`
	CustomROASClickWeight       *float64 `json:"customROASClickWeight,omitempty"`
	CustomROASViewthroughWeight *float64 `json:"customROASViewthroughWeight,omitempty"`
}

func (o *CustomROASConfig) GetIncludeInCustomROAS() bool {
	if o == nil {
		return false
	}
	return o.IncludeInCustomROAS
}

func (o *CustomROASConfig) GetCustomROASWeight() *float64 {
	if o == nil {
		return nil
	}
	return o.CustomROASWeight
}

func (o *CustomROASConfig) GetCustomROASClickWeight() *float64 {
	if o == nil {
		return nil
	}
	return o.CustomROASClickWeight
}

func (o *CustomROASConfig) GetCustomROASViewthroughWeight() *float64 {
	if o == nil {
		return nil
	}
	return o.CustomROASViewthroughWeight
}
