// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CustomROASConfig struct {
	IncludeInCustomROAS         bool     `json:"includeInCustomROAS"`
	CustomROASWeight            *float64 `json:"customROASWeight,omitempty"`
	CustomROASClickWeight       *float64 `json:"customROASClickWeight,omitempty"`
	CustomROASViewthroughWeight *float64 `json:"customROASViewthroughWeight,omitempty"`
}

func (c *CustomROASConfig) GetIncludeInCustomROAS() bool {
	if c == nil {
		return false
	}
	return c.IncludeInCustomROAS
}

func (c *CustomROASConfig) GetCustomROASWeight() *float64 {
	if c == nil {
		return nil
	}
	return c.CustomROASWeight
}

func (c *CustomROASConfig) GetCustomROASClickWeight() *float64 {
	if c == nil {
		return nil
	}
	return c.CustomROASClickWeight
}

func (c *CustomROASConfig) GetCustomROASViewthroughWeight() *float64 {
	if c == nil {
		return nil
	}
	return c.CustomROASViewthroughWeight
}
