// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type CustomCPAType string

const (
	CustomCPATypeDisabled                  CustomCPAType = "Disabled"
	CustomCPATypePixelWeighting            CustomCPAType = "PixelWeighting"
	CustomCPATypeClickViewthroughWeighting CustomCPAType = "ClickViewthroughWeighting"
)

func (e CustomCPAType) ToPointer() *CustomCPAType {
	return &e
}
func (e *CustomCPAType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Disabled":
		fallthrough
	case "PixelWeighting":
		fallthrough
	case "ClickViewthroughWeighting":
		*e = CustomCPAType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomCPAType: %v", v)
	}
}
