// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type CustomROASType string

const (
	CustomROASTypeDisabled                  CustomROASType = "Disabled"
	CustomROASTypePixelWeighting            CustomROASType = "PixelWeighting"
	CustomROASTypeClickViewthroughWeighting CustomROASType = "ClickViewthroughWeighting"
	CustomROASTypeCompositeWeighting        CustomROASType = "CompositeWeighting"
)

func (e CustomROASType) ToPointer() *CustomROASType {
	return &e
}
func (e *CustomROASType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Disabled":
		fallthrough
	case "PixelWeighting":
		fallthrough
	case "ClickViewthroughWeighting":
		fallthrough
	case "CompositeWeighting":
		*e = CustomROASType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomROASType: %v", v)
	}
}
