// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DecimalRange struct {
	Min *float64 `json:"min,omitempty"`
	Max *float64 `json:"max,omitempty"`
}

func (d *DecimalRange) GetMin() *float64 {
	if d == nil {
		return nil
	}
	return d.Min
}

func (d *DecimalRange) GetMax() *float64 {
	if d == nil {
		return nil
	}
	return d.Max
}
