// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type DeviceType string

const (
	DeviceTypeUnknown       DeviceType = "Unknown"
	DeviceTypeOther         DeviceType = "Other"
	DeviceTypePc            DeviceType = "PC"
	DeviceTypeTablet        DeviceType = "Tablet"
	DeviceTypeMobile        DeviceType = "Mobile"
	DeviceTypeRoku          DeviceType = "Roku"
	DeviceTypeConnectedTv   DeviceType = "ConnectedTV"
	DeviceTypeOutOfHome     DeviceType = "OutOfHome"
	DeviceTypeHomeAssistant DeviceType = "HomeAssistant"
)

func (e DeviceType) ToPointer() *DeviceType {
	return &e
}
func (e *DeviceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Other":
		fallthrough
	case "PC":
		fallthrough
	case "Tablet":
		fallthrough
	case "Mobile":
		fallthrough
	case "Roku":
		fallthrough
	case "ConnectedTV":
		fallthrough
	case "OutOfHome":
		fallthrough
	case "HomeAssistant":
		*e = DeviceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeviceType: %v", v)
	}
}
