// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type DimensionalBiddingDimensions string

const (
	DimensionalBiddingDimensionsUnknownDimension                          DimensionalBiddingDimensions = "UnknownDimension"
	DimensionalBiddingDimensionsHasAdFormatID                             DimensionalBiddingDimensions = "HasAdFormatId"
	DimensionalBiddingDimensionsHasDomainFragmentID                       DimensionalBiddingDimensions = "HasDomainFragmentId"
	DimensionalBiddingDimensionsHasUniversalCategoryTaxonomyID            DimensionalBiddingDimensions = "HasUniversalCategoryTaxonomyId"
	DimensionalBiddingDimensionsHasPlacementPositionRelativeToFoldID      DimensionalBiddingDimensions = "HasPlacementPositionRelativeToFoldId"
	DimensionalBiddingDimensionsHasAdvertiserTargetingDataID              DimensionalBiddingDimensions = "HasAdvertiserTargetingDataId"
	DimensionalBiddingDimensionsHasBrowserID                              DimensionalBiddingDimensions = "HasBrowserId"
	DimensionalBiddingDimensionsHasCarrierID                              DimensionalBiddingDimensions = "HasCarrierId"
	DimensionalBiddingDimensionsHasDeviceModelID                          DimensionalBiddingDimensions = "HasDeviceModelId"
	DimensionalBiddingDimensionsHasDeviceTypeID                           DimensionalBiddingDimensions = "HasDeviceTypeId"
	DimensionalBiddingDimensionsHasGeoSegmentID                           DimensionalBiddingDimensions = "HasGeoSegmentId"
	DimensionalBiddingDimensionsHasHourOfWeek                             DimensionalBiddingDimensions = "HasHourOfWeek"
	DimensionalBiddingDimensionsHasLanguageID                             DimensionalBiddingDimensions = "HasLanguageId"
	DimensionalBiddingDimensionsHasOsID                                   DimensionalBiddingDimensions = "HasOsId"
	DimensionalBiddingDimensionsHasPrivateContractID                      DimensionalBiddingDimensions = "HasPrivateContractId"
	DimensionalBiddingDimensionsHasRecencyWindowInMinutes                 DimensionalBiddingDimensions = "HasRecencyWindowInMinutes"
	DimensionalBiddingDimensionsHasRenderingContextID                     DimensionalBiddingDimensions = "HasRenderingContextId"
	DimensionalBiddingDimensionsHasFactualGeostoreTargetingDataID         DimensionalBiddingDimensions = "HasFactualGeostoreTargetingDataId"
	DimensionalBiddingDimensionsHasSupplyVendorID                         DimensionalBiddingDimensions = "HasSupplyVendorId"
	DimensionalBiddingDimensionsHasTemperatureBucketInCelsius             DimensionalBiddingDimensions = "HasTemperatureBucketInCelsius"
	DimensionalBiddingDimensionsHasThirdPartyData                         DimensionalBiddingDimensions = "HasThirdPartyData"
	DimensionalBiddingDimensionsHasAdsTxtSellerTypeID                     DimensionalBiddingDimensions = "HasAdsTxtSellerTypeId"
	DimensionalBiddingDimensionsHasVideoMutedStateID                      DimensionalBiddingDimensions = "HasVideoMutedStateId"
	DimensionalBiddingDimensionsHasVideoPlaybackTypeID                    DimensionalBiddingDimensions = "HasVideoPlaybackTypeId"
	DimensionalBiddingDimensionsHasVideoPlayerSizeID                      DimensionalBiddingDimensions = "HasVideoPlayerSizeId"
	DimensionalBiddingDimensionsHasVideoQualityID                         DimensionalBiddingDimensions = "HasVideoQualityId"
	DimensionalBiddingDimensionsHasVideoSkippabilityID                    DimensionalBiddingDimensions = "HasVideoSkippabilityId"
	DimensionalBiddingDimensionsHasFactualProximityDataID                 DimensionalBiddingDimensions = "HasFactualProximityDataId"
	DimensionalBiddingDimensionsHasImpressionPlacementID                  DimensionalBiddingDimensions = "HasImpressionPlacementId"
	DimensionalBiddingDimensionsHasVideoTruthScoreRange                   DimensionalBiddingDimensions = "HasVideoTruthScoreRange"
	DimensionalBiddingDimensionsHasVideoViewabilityScoreRange             DimensionalBiddingDimensions = "HasVideoViewabilityScoreRange"
	DimensionalBiddingDimensionsHasDisplayViewabilityScoreRange           DimensionalBiddingDimensions = "HasDisplayViewabilityScoreRange"
	DimensionalBiddingDimensionsHasPeer39LanguageID                       DimensionalBiddingDimensions = "HasPeer39LanguageId"
	DimensionalBiddingDimensionsHasIntegralContextualCategoryID           DimensionalBiddingDimensions = "HasIntegralContextualCategoryId"
	DimensionalBiddingDimensionsHasPeer39ContextualCategoryID             DimensionalBiddingDimensions = "HasPeer39ContextualCategoryId"
	DimensionalBiddingDimensionsHasDoubleVerifyContextualCategoryID       DimensionalBiddingDimensions = "HasDoubleVerifyContextualCategoryId"
	DimensionalBiddingDimensionsHasIntegralBrandSafetyCategoryID          DimensionalBiddingDimensions = "HasIntegralBrandSafetyCategoryId"
	DimensionalBiddingDimensionsHasIntegralVideoBrandSafetyCategoryID     DimensionalBiddingDimensions = "HasIntegralVideoBrandSafetyCategoryId"
	DimensionalBiddingDimensionsHasPeer39BrandSafetyCategoryID            DimensionalBiddingDimensions = "HasPeer39BrandSafetyCategoryId"
	DimensionalBiddingDimensionsHasDoubleVerifyBrandSafetyCategoryID      DimensionalBiddingDimensions = "HasDoubleVerifyBrandSafetyCategoryId"
	DimensionalBiddingDimensionsHasIntegralPageQualityCategoryID          DimensionalBiddingDimensions = "HasIntegralPageQualityCategoryId"
	DimensionalBiddingDimensionsHasIntegralVideoPageQualityCategoryID     DimensionalBiddingDimensions = "HasIntegralVideoPageQualityCategoryId"
	DimensionalBiddingDimensionsHasPeer39PageQualityCategoryID            DimensionalBiddingDimensions = "HasPeer39PageQualityCategoryId"
	DimensionalBiddingDimensionsHasDoubleVerifyBotAvoidanceCategoryID     DimensionalBiddingDimensions = "HasDoubleVerifyBotAvoidanceCategoryId"
	DimensionalBiddingDimensionsHasContextualAppCategoryID                DimensionalBiddingDimensions = "HasContextualAppCategoryId"
	DimensionalBiddingDimensionsHasPublisherID                            DimensionalBiddingDimensions = "HasPublisherId"
	DimensionalBiddingDimensionsHasIntegralViewabilityCategoryID          DimensionalBiddingDimensions = "HasIntegralViewabilityCategoryId"
	DimensionalBiddingDimensionsHasIntegralVideoViewabilityCategoryID     DimensionalBiddingDimensions = "HasIntegralVideoViewabilityCategoryId"
	DimensionalBiddingDimensionsHasDoubleVerifyViewabilityCategoryID      DimensionalBiddingDimensions = "HasDoubleVerifyViewabilityCategoryId"
	DimensionalBiddingDimensionsHasDoubleVerifyVideoViewabilityCategoryID DimensionalBiddingDimensions = "HasDoubleVerifyVideoViewabilityCategoryId"
	DimensionalBiddingDimensionsHasFrequencyAdjustmentID                  DimensionalBiddingDimensions = "HasFrequencyAdjustmentId"
	DimensionalBiddingDimensionsHasPeer39ViewabilityCategoryID            DimensionalBiddingDimensions = "HasPeer39ViewabilityCategoryId"
	DimensionalBiddingDimensionsHasVideoCompletionRateScoreRange          DimensionalBiddingDimensions = "HasVideoCompletionRateScoreRange"
	DimensionalBiddingDimensionsHasInternetConnectionTypeID               DimensionalBiddingDimensions = "HasInternetConnectionTypeId"
	DimensionalBiddingDimensionsHasAdBugPageQualityCategoryID             DimensionalBiddingDimensions = "HasAdBugPageQualityCategoryId"
	DimensionalBiddingDimensionsHasAdBugVideoPageQualityCategoryID        DimensionalBiddingDimensions = "HasAdBugVideoPageQualityCategoryId"
	DimensionalBiddingDimensionsHasRtbAsiaPageQualityCategoryID           DimensionalBiddingDimensions = "HasRTBAsiaPageQualityCategoryId"
	DimensionalBiddingDimensionsHasRtbAsiaVideoPageQualityCategoryID      DimensionalBiddingDimensions = "HasRTBAsiaVideoPageQualityCategoryId"
	DimensionalBiddingDimensionsHasTtdContextualCategoryID                DimensionalBiddingDimensions = "HasTTDContextualCategoryId"
	DimensionalBiddingDimensionsHasSupplyPathOptimizationListID           DimensionalBiddingDimensions = "HasSupplyPathOptimizationListId"
	DimensionalBiddingDimensionsHasMarketTypeID                           DimensionalBiddingDimensions = "HasMarketTypeId"
	DimensionalBiddingDimensionsHasContextualSupplyVendorGenreID          DimensionalBiddingDimensions = "HasContextualSupplyVendorGenreId"
	DimensionalBiddingDimensionsHasContextualSupplyVendorCategoryID       DimensionalBiddingDimensions = "HasContextualSupplyVendorCategoryId"
	DimensionalBiddingDimensionsHasWeatherConditionID                     DimensionalBiddingDimensions = "HasWeatherConditionId"
	DimensionalBiddingDimensionsHasFrequencyV2AdjustmentID                DimensionalBiddingDimensions = "HasFrequencyV2AdjustmentId"
	DimensionalBiddingDimensionsHasSemasioContextualCategoryID            DimensionalBiddingDimensions = "HasSemasioContextualCategoryId"
	DimensionalBiddingDimensionsHasSellerID                               DimensionalBiddingDimensions = "HasSellerId"
	DimensionalBiddingDimensionsHasDigitalOutOfHomeVenueTypeID            DimensionalBiddingDimensions = "HasDigitalOutOfHomeVenueTypeId"
	DimensionalBiddingDimensionsHasNativePlacementTypeID                  DimensionalBiddingDimensions = "HasNativePlacementTypeId"
	DimensionalBiddingDimensionsHasTtdNativeContextTypeID                 DimensionalBiddingDimensions = "HasTTDNativeContextTypeId"
	DimensionalBiddingDimensionsHasDomainClassID                          DimensionalBiddingDimensions = "HasDomainClassId"
	DimensionalBiddingDimensionsHasGeofenceThirdPartyDataAndBrand         DimensionalBiddingDimensions = "HasGeofenceThirdPartyDataAndBrand"
	DimensionalBiddingDimensionsHasPreBidContextualCategoryID             DimensionalBiddingDimensions = "HasPreBidContextualCategoryId"
	DimensionalBiddingDimensionsHasMiaozhenPageQualityCategoryID          DimensionalBiddingDimensions = "HasMiaozhenPageQualityCategoryId"
	DimensionalBiddingDimensionsHasMiaozhenVideoPageQualityCategoryID     DimensionalBiddingDimensions = "HasMiaozhenVideoPageQualityCategoryId"
	DimensionalBiddingDimensionsHasTencentPageQualityCategoryID           DimensionalBiddingDimensions = "HasTencentPageQualityCategoryId"
	DimensionalBiddingDimensionsHasContentGenre                           DimensionalBiddingDimensions = "HasContentGenre"
	DimensionalBiddingDimensionsHasContentLivestream                      DimensionalBiddingDimensions = "HasContentLivestream"
	DimensionalBiddingDimensionsHasContentProductionQuality               DimensionalBiddingDimensions = "HasContentProductionQuality"
	DimensionalBiddingDimensionsHasContentRating                          DimensionalBiddingDimensions = "HasContentRating"
	DimensionalBiddingDimensionsHasContentDuration                        DimensionalBiddingDimensions = "HasContentDuration"
	DimensionalBiddingDimensionsHasTvQualityIndexRange                    DimensionalBiddingDimensions = "HasTVQualityIndexRange"
	DimensionalBiddingDimensionsHasAtmosphericCondition                   DimensionalBiddingDimensions = "HasAtmosphericCondition"
	DimensionalBiddingDimensionsHasMarketplaceID                          DimensionalBiddingDimensions = "HasMarketplaceId"
	DimensionalBiddingDimensionsHasAudienceReachPercentageTierID          DimensionalBiddingDimensions = "HasAudienceReachPercentageTierId"
	DimensionalBiddingDimensionsHasAdLoadCategory                         DimensionalBiddingDimensions = "HasAdLoadCategory"
	DimensionalBiddingDimensionsHasFullReferrerURL                        DimensionalBiddingDimensions = "HasFullReferrerUrl"
	DimensionalBiddingDimensionsHasLikelyRefreshRate                      DimensionalBiddingDimensions = "HasLikelyRefreshRate"
	DimensionalBiddingDimensionsHasContentTransparency                    DimensionalBiddingDimensions = "HasContentTransparency"
	DimensionalBiddingDimensionsHasIdiosyncraticSegmentID                 DimensionalBiddingDimensions = "HasIdiosyncraticSegmentId"
)

func (e DimensionalBiddingDimensions) ToPointer() *DimensionalBiddingDimensions {
	return &e
}
func (e *DimensionalBiddingDimensions) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UnknownDimension":
		fallthrough
	case "HasAdFormatId":
		fallthrough
	case "HasDomainFragmentId":
		fallthrough
	case "HasUniversalCategoryTaxonomyId":
		fallthrough
	case "HasPlacementPositionRelativeToFoldId":
		fallthrough
	case "HasAdvertiserTargetingDataId":
		fallthrough
	case "HasBrowserId":
		fallthrough
	case "HasCarrierId":
		fallthrough
	case "HasDeviceModelId":
		fallthrough
	case "HasDeviceTypeId":
		fallthrough
	case "HasGeoSegmentId":
		fallthrough
	case "HasHourOfWeek":
		fallthrough
	case "HasLanguageId":
		fallthrough
	case "HasOsId":
		fallthrough
	case "HasPrivateContractId":
		fallthrough
	case "HasRecencyWindowInMinutes":
		fallthrough
	case "HasRenderingContextId":
		fallthrough
	case "HasFactualGeostoreTargetingDataId":
		fallthrough
	case "HasSupplyVendorId":
		fallthrough
	case "HasTemperatureBucketInCelsius":
		fallthrough
	case "HasThirdPartyData":
		fallthrough
	case "HasAdsTxtSellerTypeId":
		fallthrough
	case "HasVideoMutedStateId":
		fallthrough
	case "HasVideoPlaybackTypeId":
		fallthrough
	case "HasVideoPlayerSizeId":
		fallthrough
	case "HasVideoQualityId":
		fallthrough
	case "HasVideoSkippabilityId":
		fallthrough
	case "HasFactualProximityDataId":
		fallthrough
	case "HasImpressionPlacementId":
		fallthrough
	case "HasVideoTruthScoreRange":
		fallthrough
	case "HasVideoViewabilityScoreRange":
		fallthrough
	case "HasDisplayViewabilityScoreRange":
		fallthrough
	case "HasPeer39LanguageId":
		fallthrough
	case "HasIntegralContextualCategoryId":
		fallthrough
	case "HasPeer39ContextualCategoryId":
		fallthrough
	case "HasDoubleVerifyContextualCategoryId":
		fallthrough
	case "HasIntegralBrandSafetyCategoryId":
		fallthrough
	case "HasIntegralVideoBrandSafetyCategoryId":
		fallthrough
	case "HasPeer39BrandSafetyCategoryId":
		fallthrough
	case "HasDoubleVerifyBrandSafetyCategoryId":
		fallthrough
	case "HasIntegralPageQualityCategoryId":
		fallthrough
	case "HasIntegralVideoPageQualityCategoryId":
		fallthrough
	case "HasPeer39PageQualityCategoryId":
		fallthrough
	case "HasDoubleVerifyBotAvoidanceCategoryId":
		fallthrough
	case "HasContextualAppCategoryId":
		fallthrough
	case "HasPublisherId":
		fallthrough
	case "HasIntegralViewabilityCategoryId":
		fallthrough
	case "HasIntegralVideoViewabilityCategoryId":
		fallthrough
	case "HasDoubleVerifyViewabilityCategoryId":
		fallthrough
	case "HasDoubleVerifyVideoViewabilityCategoryId":
		fallthrough
	case "HasFrequencyAdjustmentId":
		fallthrough
	case "HasPeer39ViewabilityCategoryId":
		fallthrough
	case "HasVideoCompletionRateScoreRange":
		fallthrough
	case "HasInternetConnectionTypeId":
		fallthrough
	case "HasAdBugPageQualityCategoryId":
		fallthrough
	case "HasAdBugVideoPageQualityCategoryId":
		fallthrough
	case "HasRTBAsiaPageQualityCategoryId":
		fallthrough
	case "HasRTBAsiaVideoPageQualityCategoryId":
		fallthrough
	case "HasTTDContextualCategoryId":
		fallthrough
	case "HasSupplyPathOptimizationListId":
		fallthrough
	case "HasMarketTypeId":
		fallthrough
	case "HasContextualSupplyVendorGenreId":
		fallthrough
	case "HasContextualSupplyVendorCategoryId":
		fallthrough
	case "HasWeatherConditionId":
		fallthrough
	case "HasFrequencyV2AdjustmentId":
		fallthrough
	case "HasSemasioContextualCategoryId":
		fallthrough
	case "HasSellerId":
		fallthrough
	case "HasDigitalOutOfHomeVenueTypeId":
		fallthrough
	case "HasNativePlacementTypeId":
		fallthrough
	case "HasTTDNativeContextTypeId":
		fallthrough
	case "HasDomainClassId":
		fallthrough
	case "HasGeofenceThirdPartyDataAndBrand":
		fallthrough
	case "HasPreBidContextualCategoryId":
		fallthrough
	case "HasMiaozhenPageQualityCategoryId":
		fallthrough
	case "HasMiaozhenVideoPageQualityCategoryId":
		fallthrough
	case "HasTencentPageQualityCategoryId":
		fallthrough
	case "HasContentGenre":
		fallthrough
	case "HasContentLivestream":
		fallthrough
	case "HasContentProductionQuality":
		fallthrough
	case "HasContentRating":
		fallthrough
	case "HasContentDuration":
		fallthrough
	case "HasTVQualityIndexRange":
		fallthrough
	case "HasAtmosphericCondition":
		fallthrough
	case "HasMarketplaceId":
		fallthrough
	case "HasAudienceReachPercentageTierId":
		fallthrough
	case "HasAdLoadCategory":
		fallthrough
	case "HasFullReferrerUrl":
		fallthrough
	case "HasLikelyRefreshRate":
		fallthrough
	case "HasContentTransparency":
		fallthrough
	case "HasIdiosyncraticSegmentId":
		*e = DimensionalBiddingDimensions(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DimensionalBiddingDimensions: %v", v)
	}
}
