// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type DoubleVerifyVideoViewability string

const (
	DoubleVerifyVideoViewabilityDuration10    DoubleVerifyVideoViewability = "Duration10"
	DoubleVerifyVideoViewabilityDuration20    DoubleVerifyVideoViewability = "Duration20"
	DoubleVerifyVideoViewabilityDuration25    DoubleVerifyVideoViewability = "Duration25"
	DoubleVerifyVideoViewabilityDuration30    DoubleVerifyVideoViewability = "Duration30"
	DoubleVerifyVideoViewabilityDuration35    DoubleVerifyVideoViewability = "Duration35"
	DoubleVerifyVideoViewabilityDuration40    DoubleVerifyVideoViewability = "Duration40"
	DoubleVerifyVideoViewabilityViewability30 DoubleVerifyVideoViewability = "Viewability30"
	DoubleVerifyVideoViewabilityViewability40 DoubleVerifyVideoViewability = "Viewability40"
	DoubleVerifyVideoViewabilityViewability50 DoubleVerifyVideoViewability = "Viewability50"
	DoubleVerifyVideoViewabilityViewability55 DoubleVerifyVideoViewability = "Viewability55"
	DoubleVerifyVideoViewabilityViewability60 DoubleVerifyVideoViewability = "Viewability60"
	DoubleVerifyVideoViewabilityViewability65 DoubleVerifyVideoViewability = "Viewability65"
	DoubleVerifyVideoViewabilityViewability70 DoubleVerifyVideoViewability = "Viewability70"
	DoubleVerifyVideoViewabilityViewability75 DoubleVerifyVideoViewability = "Viewability75"
	DoubleVerifyVideoViewabilityViewability80 DoubleVerifyVideoViewability = "Viewability80"
)

func (e DoubleVerifyVideoViewability) ToPointer() *DoubleVerifyVideoViewability {
	return &e
}
func (e *DoubleVerifyVideoViewability) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Duration10":
		fallthrough
	case "Duration20":
		fallthrough
	case "Duration25":
		fallthrough
	case "Duration30":
		fallthrough
	case "Duration35":
		fallthrough
	case "Duration40":
		fallthrough
	case "Viewability30":
		fallthrough
	case "Viewability40":
		fallthrough
	case "Viewability50":
		fallthrough
	case "Viewability55":
		fallthrough
	case "Viewability60":
		fallthrough
	case "Viewability65":
		fallthrough
	case "Viewability70":
		fallthrough
	case "Viewability75":
		fallthrough
	case "Viewability80":
		*e = DoubleVerifyVideoViewability(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DoubleVerifyVideoViewability: %v", v)
	}
}
