// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type DoubleVerifyDisplayViewability string

const (
	DoubleVerifyDisplayViewabilityBrandExposureDuration10 DoubleVerifyDisplayViewability = "BrandExposureDuration10"
	DoubleVerifyDisplayViewabilityBrandExposureDuration15 DoubleVerifyDisplayViewability = "BrandExposureDuration15"
	DoubleVerifyDisplayViewabilityBrandExposureDuration5  DoubleVerifyDisplayViewability = "BrandExposureDuration5"
	DoubleVerifyDisplayViewabilityTop30                   DoubleVerifyDisplayViewability = "Top30"
	DoubleVerifyDisplayViewabilityTop40                   DoubleVerifyDisplayViewability = "Top40"
	DoubleVerifyDisplayViewabilityTop50                   DoubleVerifyDisplayViewability = "Top50"
	DoubleVerifyDisplayViewabilityTop55                   DoubleVerifyDisplayViewability = "Top55"
	DoubleVerifyDisplayViewabilityTop60                   DoubleVerifyDisplayViewability = "Top60"
	DoubleVerifyDisplayViewabilityTop65                   DoubleVerifyDisplayViewability = "Top65"
	DoubleVerifyDisplayViewabilityTop70                   DoubleVerifyDisplayViewability = "Top70"
	DoubleVerifyDisplayViewabilityTop75                   DoubleVerifyDisplayViewability = "Top75"
	DoubleVerifyDisplayViewabilityTop80                   DoubleVerifyDisplayViewability = "Top80"
)

func (e DoubleVerifyDisplayViewability) ToPointer() *DoubleVerifyDisplayViewability {
	return &e
}
func (e *DoubleVerifyDisplayViewability) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "BrandExposureDuration10":
		fallthrough
	case "BrandExposureDuration15":
		fallthrough
	case "BrandExposureDuration5":
		fallthrough
	case "Top30":
		fallthrough
	case "Top40":
		fallthrough
	case "Top50":
		fallthrough
	case "Top55":
		fallthrough
	case "Top60":
		fallthrough
	case "Top65":
		fallthrough
	case "Top70":
		fallthrough
	case "Top75":
		fallthrough
	case "Top80":
		*e = DoubleVerifyDisplayViewability(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DoubleVerifyDisplayViewability: %v", v)
	}
}
