// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type DoubleVerifyBotAvoidance string

const (
	DoubleVerifyBotAvoidanceFraudInvalid DoubleVerifyBotAvoidance = "FraudInvalid"
	DoubleVerifyBotAvoidanceFraudNoAds   DoubleVerifyBotAvoidance = "FraudNoAds"
)

func (e DoubleVerifyBotAvoidance) ToPointer() *DoubleVerifyBotAvoidance {
	return &e
}
func (e *DoubleVerifyBotAvoidance) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FraudInvalid":
		fallthrough
	case "FraudNoAds":
		*e = DoubleVerifyBotAvoidance(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DoubleVerifyBotAvoidance: %v", v)
	}
}
