// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type EnhancedNielsenReportingOptions string

const (
	EnhancedNielsenReportingOptionsNone     EnhancedNielsenReportingOptions = "None"
	EnhancedNielsenReportingOptionsAudience EnhancedNielsenReportingOptions = "Audience"
	EnhancedNielsenReportingOptionsSite     EnhancedNielsenReportingOptions = "Site"
)

func (e EnhancedNielsenReportingOptions) ToPointer() *EnhancedNielsenReportingOptions {
	return &e
}
func (e *EnhancedNielsenReportingOptions) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "None":
		fallthrough
	case "Audience":
		fallthrough
	case "Site":
		*e = EnhancedNielsenReportingOptions(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnhancedNielsenReportingOptions: %v", v)
	}
}
