// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type EnhancedNielsenReportingOptionsInput string

const (
	EnhancedNielsenReportingOptionsInputNone     EnhancedNielsenReportingOptionsInput = "None"
	EnhancedNielsenReportingOptionsInputAudience EnhancedNielsenReportingOptionsInput = "Audience"
	EnhancedNielsenReportingOptionsInputSite     EnhancedNielsenReportingOptionsInput = "Site"
)

func (e EnhancedNielsenReportingOptionsInput) ToPointer() *EnhancedNielsenReportingOptionsInput {
	return &e
}
func (e *EnhancedNielsenReportingOptionsInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "None":
		fallthrough
	case "Audience":
		fallthrough
	case "Site":
		*e = EnhancedNielsenReportingOptionsInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnhancedNielsenReportingOptionsInput: %v", v)
	}
}
