// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FactualProximityTargetInput struct {
	TargetingCodeID *int `json:"targetingCodeId,omitempty"`
	DesignID        *int `json:"designId,omitempty"`
}

func (f *FactualProximityTargetInput) GetTargetingCodeID() *int {
	if f == nil {
		return nil
	}
	return f.TargetingCodeID
}

func (f *FactualProximityTargetInput) GetDesignID() *int {
	if f == nil {
		return nil
	}
	return f.DesignID
}
