// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FirstPartyDataInput - Required fields for submitting a bulk job for first-party data.
type FirstPartyDataInput struct {
	// The advertiser ID to query for.
	AdvertiserID string `json:"advertiserId"`
	// The name to filter by in the query. This filter will be applied to the results for the advertiser.
	// If there are no nodes which match the filter, a response with empty nodes with no first-party data will be returned.
	NameFilter *string `json:"nameFilter,omitempty"`
	//  The shape of the query with the fields being asked for, which is sent downstream.
	//  This determines what the response will look like.
	//
	//  For example, a query shape equal to `"nodes {id name}"` will return the `id` and `name` fields only.
	//
	//  If this is not provided the default query shape will be used:
	//
	//  ```graphql
	//  nodes {
	//     name
	//     id
	//     activeUniques {
	//        householdCount
	//        idsConnectedTvCount
	//        idsCount
	//        idsInAppCount
	//        idsWebCount
	//        personsCount
	//     }
	//  }
	// ```
	QueryShape    *string                `json:"queryShape,omitempty"`
	CallbackInput *WorkflowCallbackInput `json:"callbackInput,omitempty"`
}

func (f *FirstPartyDataInput) GetAdvertiserID() string {
	if f == nil {
		return ""
	}
	return f.AdvertiserID
}

func (f *FirstPartyDataInput) GetNameFilter() *string {
	if f == nil {
		return nil
	}
	return f.NameFilter
}

func (f *FirstPartyDataInput) GetQueryShape() *string {
	if f == nil {
		return nil
	}
	return f.QueryShape
}

func (f *FirstPartyDataInput) GetCallbackInput() *WorkflowCallbackInput {
	if f == nil {
		return nil
	}
	return f.CallbackInput
}
