// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FrequencyConfig struct {
	CounterName            *string `json:"counterName,omitempty"`
	FrequencyCap           *int    `json:"frequencyCap,omitempty"`
	FrequencyGoal          *int    `json:"frequencyGoal,omitempty"`
	ResetIntervalInMinutes *int    `json:"resetIntervalInMinutes,omitempty"`
}

func (f *FrequencyConfig) GetCounterName() *string {
	if f == nil {
		return nil
	}
	return f.CounterName
}

func (f *FrequencyConfig) GetFrequencyCap() *int {
	if f == nil {
		return nil
	}
	return f.FrequencyCap
}

func (f *FrequencyConfig) GetFrequencyGoal() *int {
	if f == nil {
		return nil
	}
	return f.FrequencyGoal
}

func (f *FrequencyConfig) GetResetIntervalInMinutes() *int {
	if f == nil {
		return nil
	}
	return f.ResetIntervalInMinutes
}
