// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FrequencyAdjustmentInput struct {
	CounterID  *string     `json:"counterId,omitempty"`
	TimesShown *Int32Range `json:"timesShown,omitempty"`
}

func (f *FrequencyAdjustmentInput) GetCounterID() *string {
	if f == nil {
		return nil
	}
	return f.CounterID
}

func (f *FrequencyAdjustmentInput) GetTimesShown() *Int32Range {
	if f == nil {
		return nil
	}
	return f.TimesShown
}
