// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type FullReferrerURL string

const (
	FullReferrerURLUnknown    FullReferrerURL = "Unknown"
	FullReferrerURLDomainOnly FullReferrerURL = "DomainOnly"
	FullReferrerURLFullURL    FullReferrerURL = "FullUrl"
)

func (e FullReferrerURL) ToPointer() *FullReferrerURL {
	return &e
}
func (e *FullReferrerURL) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "DomainOnly":
		fallthrough
	case "FullUrl":
		*e = FullReferrerURL(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FullReferrerURL: %v", v)
	}
}
