// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GeoBidListOptionsInput struct {
	LocationContextType *LocationContextTypeInput `json:"locationContextType,omitempty"`
}

func (g *GeoBidListOptionsInput) GetLocationContextType() *LocationContextTypeInput {
	if g == nil {
		return nil
	}
	return g.LocationContextType
}
