// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GeofenceThirdPartyDataAndBrandInput struct {
	DataID  *int64  `json:"dataId,omitempty"`
	BrandID *string `json:"brandId,omitempty"`
}

func (g *GeofenceThirdPartyDataAndBrandInput) GetDataID() *int64 {
	if g == nil {
		return nil
	}
	return g.DataID
}

func (g *GeofenceThirdPartyDataAndBrandInput) GetBrandID() *string {
	if g == nil {
		return nil
	}
	return g.BrandID
}
