// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GraphQlQueryJobInput - Fields for executing a GraphQL query job
type GraphQlQueryJobInput struct {
	// The GraphQL query to execute
	Query string `json:"query"`
	// Input class for providing a callback's url and any headers needed for the callback.
	CallbackInput *GraphQlBulkJobCallbackInput `json:"callbackInput,omitempty"`
	// Beta features to be enabled for this GraphQL query (passed as TTD-GQL-Beta header)
	BetaFeatures *string `json:"betaFeatures,omitempty"`
}

func (g *GraphQlQueryJobInput) GetQuery() string {
	if g == nil {
		return ""
	}
	return g.Query
}

func (g *GraphQlQueryJobInput) GetCallbackInput() *GraphQlBulkJobCallbackInput {
	if g == nil {
		return nil
	}
	return g.CallbackInput
}

func (g *GraphQlQueryJobInput) GetBetaFeatures() *string {
	if g == nil {
		return nil
	}
	return g.BetaFeatures
}
