// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GraphQLBulkJobError - Represents an error type returned by the inner data on a mutation response
type GraphQLBulkJobError struct {
	Message        *string           `json:"message"`
	Field          []string          `json:"field,omitempty"`
	AdditionalData map[string]string `json:"additionalData,omitempty"`
}

func (g *GraphQLBulkJobError) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GraphQLBulkJobError) GetField() []string {
	if g == nil {
		return nil
	}
	return g.Field
}

func (g *GraphQLBulkJobError) GetAdditionalData() map[string]string {
	if g == nil {
		return nil
	}
	return g.AdditionalData
}
