// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GraphQlBulkJobResponse - This is the top-level class returned to a user when a bulk job is created.
type GraphQlBulkJobResponse struct {
	Payload *GraphQlBulkJobPayload `json:"payload,omitempty"`
	Errors  *string                `json:"errors,omitempty"`
}

func (g *GraphQlBulkJobResponse) GetPayload() *GraphQlBulkJobPayload {
	if g == nil {
		return nil
	}
	return g.Payload
}

func (g *GraphQlBulkJobResponse) GetErrors() *string {
	if g == nil {
		return nil
	}
	return g.Errors
}
