// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GraphQlBulkJobPayload struct {
	// The response model that mirrors the GQL bulkjob.
	Data   *GraphQlBulkJob       `json:"data,omitempty"`
	Errors []GraphQLBulkJobError `json:"errors,omitempty"`
}

func (g *GraphQlBulkJobPayload) GetData() *GraphQlBulkJob {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GraphQlBulkJobPayload) GetErrors() []GraphQLBulkJobError {
	if g == nil {
		return nil
	}
	return g.Errors
}
