// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GraphQlQueryJobInput - Required fields for executing a GraphQL query job
type GraphQlQueryJobInput struct {
	// The GraphQL query to execute
	Query string `json:"query"`
	// Input class for providing a callback's url and any headers needed for the callback.
	CallbackInput *GraphQlJobCallbackInput `json:"callbackInput,omitempty"`
}

func (o *GraphQlQueryJobInput) GetQuery() string {
	if o == nil {
		return ""
	}
	return o.Query
}

func (o *GraphQlQueryJobInput) GetCallbackInput() *GraphQlJobCallbackInput {
	if o == nil {
		return nil
	}
	return o.CallbackInput
}
