// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GraphQlQueryJobPayload struct {
	// This is the response model that mirrors the GQL bulkjob
	Data   *GraphQlQueryJob       `json:"data,omitempty"`
	Errors []GraphQLQueryJobError `json:"errors,omitempty"`
}

func (o *GraphQlQueryJobPayload) GetData() *GraphQlQueryJob {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GraphQlQueryJobPayload) GetErrors() []GraphQLQueryJobError {
	if o == nil {
		return nil
	}
	return o.Errors
}
