// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GraphQLBulkJobRetrievalResponse - This is the top level class returned to a user when they retrieve a bulk job
type GraphQLBulkJobRetrievalResponse struct {
	// The response model that mirrors the GQL bulkjob.
	Job    *GraphQlBulkJob `json:"job,omitempty"`
	Errors *string         `json:"errors,omitempty"`
}

func (g *GraphQLBulkJobRetrievalResponse) GetJob() *GraphQlBulkJob {
	if g == nil {
		return nil
	}
	return g.Job
}

func (g *GraphQLBulkJobRetrievalResponse) GetErrors() *string {
	if g == nil {
		return nil
	}
	return g.Errors
}
