// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GraphQLRequestInput - Required fields for executing a GraphQL query
type GraphQLRequestInput struct {
	// The GraphQL query to execute.
	Request string `json:"request"`
	// Variables to substitute into the query.
	Variables map[string]any `json:"variables,omitempty"`
	// Beta features to be enabled for this GraphQL request (passed as TTD-GQL-Beta header)
	BetaFeatures *string `json:"betaFeatures,omitempty"`
}

func (g *GraphQLRequestInput) GetRequest() string {
	if g == nil {
		return ""
	}
	return g.Request
}

func (g *GraphQLRequestInput) GetVariables() map[string]any {
	if g == nil {
		return nil
	}
	return g.Variables
}

func (g *GraphQLRequestInput) GetBetaFeatures() *string {
	if g == nil {
		return nil
	}
	return g.BetaFeatures
}
