// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GraphQlJobCallbackInput - Input class for providing a callback's url and any headers needed for the callback.
type GraphQlJobCallbackInput struct {
	CallbackURL     string                               `json:"callbackUrl"`
	CallbackHeaders []KeyValuePairOfStringAndStringInput `json:"callbackHeaders,omitempty"`
}

func (o *GraphQlJobCallbackInput) GetCallbackURL() string {
	if o == nil {
		return ""
	}
	return o.CallbackURL
}

func (o *GraphQlJobCallbackInput) GetCallbackHeaders() []KeyValuePairOfStringAndStringInput {
	if o == nil {
		return nil
	}
	return o.CallbackHeaders
}
