// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GraphQlQueryJobResponse - This is the top level class returned to a user when a query job is created.
type GraphQlQueryJobResponse struct {
	Payload *GraphQlQueryJobPayload `json:"payload,omitempty"`
	Errors  *string                 `json:"errors,omitempty"`
}

func (o *GraphQlQueryJobResponse) GetPayload() *GraphQlQueryJobPayload {
	if o == nil {
		return nil
	}
	return o.Payload
}

func (o *GraphQlQueryJobResponse) GetErrors() *string {
	if o == nil {
		return nil
	}
	return o.Errors
}
