// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/thetradedesk/ttd-workflows-go/internal/utils"
	"time"
)

// GraphQlBulkJob - The response model that mirrors the GQL bulkjob.
type GraphQlBulkJob struct {
	// The ID of the job.
	ID int64 `json:"id"`
	// The UTC date and time that the job completed.
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	// The job completion percentage.
	CompletionPercentage *float32 `json:"completionPercentage,omitempty"`
	// The UTC date and time that the job was created.
	CreatedAt time.Time     `json:"createdAt"`
	Status    BulkJobStatus `json:"status"`
	// The URL from which the job result can be downloaded.
	URL *string `json:"url,omitempty"`
	// The raw job result if the response is less than or equal to 20MB in size.
	// If the job result is larger than 20MB, then null is returned.
	RawResult *string `json:"rawResult,omitempty"`
	// If the GQL requests within the job hard-failed (such as from an authorization error
	// or an internal server error), the causes encountered during execution.
	QueryGqlErrors []string `json:"queryGqlErrors,omitempty"`
	// Errors encountered while executing the job.
	RuntimeErrors []string `json:"runtimeErrors"`
}

func (g GraphQlBulkJob) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GraphQlBulkJob) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GraphQlBulkJob) GetID() int64 {
	if g == nil {
		return 0
	}
	return g.ID
}

func (g *GraphQlBulkJob) GetCompletedAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.CompletedAt
}

func (g *GraphQlBulkJob) GetCompletionPercentage() *float32 {
	if g == nil {
		return nil
	}
	return g.CompletionPercentage
}

func (g *GraphQlBulkJob) GetCreatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.CreatedAt
}

func (g *GraphQlBulkJob) GetStatus() BulkJobStatus {
	if g == nil {
		return BulkJobStatus("")
	}
	return g.Status
}

func (g *GraphQlBulkJob) GetURL() *string {
	if g == nil {
		return nil
	}
	return g.URL
}

func (g *GraphQlBulkJob) GetRawResult() *string {
	if g == nil {
		return nil
	}
	return g.RawResult
}

func (g *GraphQlBulkJob) GetQueryGqlErrors() []string {
	if g == nil {
		return nil
	}
	return g.QueryGqlErrors
}

func (g *GraphQlBulkJob) GetRuntimeErrors() []string {
	if g == nil {
		return nil
	}
	return g.RuntimeErrors
}
