// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Variables to substitute into the query.
type Variables struct {
}

// GraphQLRequestInput - Required fields for executing a GraphQL query
type GraphQLRequestInput struct {
	// The GraphQL query to execute.
	Request string `json:"request"`
	// Variables to substitute into the query.
	Variables *Variables `json:"variables,omitempty"`
}

func (o *GraphQLRequestInput) GetRequest() string {
	if o == nil {
		return ""
	}
	return o.Request
}

func (o *GraphQLRequestInput) GetVariables() *Variables {
	if o == nil {
		return nil
	}
	return o.Variables
}
