// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GraphQlBulkJobCallbackInput - Input class for providing a callback's url and any headers needed for the callback.
type GraphQlBulkJobCallbackInput struct {
	CallbackURL     string                               `json:"callbackUrl"`
	CallbackHeaders []KeyValuePairOfStringAndStringInput `json:"callbackHeaders,omitempty"`
}

func (g *GraphQlBulkJobCallbackInput) GetCallbackURL() string {
	if g == nil {
		return ""
	}
	return g.CallbackURL
}

func (g *GraphQlBulkJobCallbackInput) GetCallbackHeaders() []KeyValuePairOfStringAndStringInput {
	if g == nil {
		return nil
	}
	return g.CallbackHeaders
}
