// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GraphQLQueryJobRetrievalResponse - This is the top level class returned to a user when they retrieve a query job
type GraphQLQueryJobRetrievalResponse struct {
	// This is the response model that mirrors the GQL bulkjob
	Job    *GraphQlQueryJob `json:"job,omitempty"`
	Errors *string          `json:"errors,omitempty"`
}

func (o *GraphQLQueryJobRetrievalResponse) GetJob() *GraphQlQueryJob {
	if o == nil {
		return nil
	}
	return o.Job
}

func (o *GraphQLQueryJobRetrievalResponse) GetErrors() *string {
	if o == nil {
		return nil
	}
	return o.Errors
}
