// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GraphQLQueryJobError - Represents an error type returned by the inner data on a mutation response
type GraphQLQueryJobError struct {
	Message        *string           `json:"message"`
	Field          []string          `json:"field,omitempty"`
	AdditionalData map[string]string `json:"additionalData,omitempty"`
}

func (o *GraphQLQueryJobError) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GraphQLQueryJobError) GetField() []string {
	if o == nil {
		return nil
	}
	return o.Field
}

func (o *GraphQLQueryJobError) GetAdditionalData() map[string]string {
	if o == nil {
		return nil
	}
	return o.AdditionalData
}
