// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type IdiosyncraticSegment string

const (
	IdiosyncraticSegmentNone               IdiosyncraticSegment = "None"
	IdiosyncraticSegmentAllKnownHouseholds IdiosyncraticSegment = "AllKnownHouseholds"
	IdiosyncraticSegmentLightTvViewers     IdiosyncraticSegment = "LightTvViewers"
	IdiosyncraticSegmentLightTvViewers2    IdiosyncraticSegment = "LightTvViewers2"
)

func (e IdiosyncraticSegment) ToPointer() *IdiosyncraticSegment {
	return &e
}
func (e *IdiosyncraticSegment) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "None":
		fallthrough
	case "AllKnownHouseholds":
		fallthrough
	case "LightTvViewers":
		fallthrough
	case "LightTvViewers2":
		*e = IdiosyncraticSegment(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IdiosyncraticSegment: %v", v)
	}
}
