// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type IncrementalReachBrandInput struct {
	ID       *int    `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	IsActive *bool   `json:"isActive,omitempty"`
}

func (i *IncrementalReachBrandInput) GetID() *int {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IncrementalReachBrandInput) GetName() *string {
	if i == nil {
		return nil
	}
	return i.Name
}

func (i *IncrementalReachBrandInput) GetIsActive() *bool {
	if i == nil {
		return nil
	}
	return i.IsActive
}
