// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type IncrementalReachProductInput struct {
	ID   *int    `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

func (i *IncrementalReachProductInput) GetID() *int {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IncrementalReachProductInput) GetName() *string {
	if i == nil {
		return nil
	}
	return i.Name
}
