// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Int32Range struct {
	Min *int `json:"min,omitempty"`
	Max *int `json:"max,omitempty"`
}

func (i *Int32Range) GetMin() *int {
	if i == nil {
		return nil
	}
	return i.Min
}

func (i *Int32Range) GetMax() *int {
	if i == nil {
		return nil
	}
	return i.Max
}

// #region class-body-int32range
// #endregion class-body-int32range
