// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type IntegralViewabilityInput string

const (
	IntegralViewabilityInputInView40 IntegralViewabilityInput = "InView40"
	IntegralViewabilityInputInView50 IntegralViewabilityInput = "InView50"
	IntegralViewabilityInputInView60 IntegralViewabilityInput = "InView60"
	IntegralViewabilityInputInView70 IntegralViewabilityInput = "InView70"
)

func (e IntegralViewabilityInput) ToPointer() *IntegralViewabilityInput {
	return &e
}
func (e *IntegralViewabilityInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "InView40":
		fallthrough
	case "InView50":
		fallthrough
	case "InView60":
		fallthrough
	case "InView70":
		*e = IntegralViewabilityInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegralViewabilityInput: %v", v)
	}
}
