// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type InternetConnectionTypeInput string

const (
	InternetConnectionTypeInputUnknown                InternetConnectionTypeInput = "Unknown"
	InternetConnectionTypeInputEthernet               InternetConnectionTypeInput = "Ethernet"
	InternetConnectionTypeInputWiFi                   InternetConnectionTypeInput = "WiFi"
	InternetConnectionTypeInputCellularNetworkUnknown InternetConnectionTypeInput = "CellularNetworkUnknown"
	InternetConnectionTypeInputCellularNetwork2G      InternetConnectionTypeInput = "CellularNetwork2G"
	InternetConnectionTypeInputCellularNetwork3G      InternetConnectionTypeInput = "CellularNetwork3G"
	InternetConnectionTypeInputCellularNetwork4G      InternetConnectionTypeInput = "CellularNetwork4G"
	InternetConnectionTypeInputCellularNetwork5G      InternetConnectionTypeInput = "CellularNetwork5G"
)

func (e InternetConnectionTypeInput) ToPointer() *InternetConnectionTypeInput {
	return &e
}
func (e *InternetConnectionTypeInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Ethernet":
		fallthrough
	case "WiFi":
		fallthrough
	case "CellularNetworkUnknown":
		fallthrough
	case "CellularNetwork2G":
		fallthrough
	case "CellularNetwork3G":
		fallthrough
	case "CellularNetwork4G":
		fallthrough
	case "CellularNetwork5G":
		*e = InternetConnectionTypeInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InternetConnectionTypeInput: %v", v)
	}
}
