// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type InternetConnectionType string

const (
	InternetConnectionTypeUnknown                InternetConnectionType = "Unknown"
	InternetConnectionTypeEthernet               InternetConnectionType = "Ethernet"
	InternetConnectionTypeWiFi                   InternetConnectionType = "WiFi"
	InternetConnectionTypeCellularNetworkUnknown InternetConnectionType = "CellularNetworkUnknown"
	InternetConnectionTypeCellularNetwork2G      InternetConnectionType = "CellularNetwork2G"
	InternetConnectionTypeCellularNetwork3G      InternetConnectionType = "CellularNetwork3G"
	InternetConnectionTypeCellularNetwork4G      InternetConnectionType = "CellularNetwork4G"
	InternetConnectionTypeCellularNetwork5G      InternetConnectionType = "CellularNetwork5G"
)

func (e InternetConnectionType) ToPointer() *InternetConnectionType {
	return &e
}
func (e *InternetConnectionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Ethernet":
		fallthrough
	case "WiFi":
		fallthrough
	case "CellularNetworkUnknown":
		fallthrough
	case "CellularNetwork2G":
		fallthrough
	case "CellularNetwork3G":
		fallthrough
	case "CellularNetwork4G":
		fallthrough
	case "CellularNetwork5G":
		*e = InternetConnectionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InternetConnectionType: %v", v)
	}
}
