// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type IntegralVideoViewabilityInput string

const (
	IntegralVideoViewabilityInputInView40 IntegralVideoViewabilityInput = "InView40"
	IntegralVideoViewabilityInputInView50 IntegralVideoViewabilityInput = "InView50"
	IntegralVideoViewabilityInputInView60 IntegralVideoViewabilityInput = "InView60"
	IntegralVideoViewabilityInputInView70 IntegralVideoViewabilityInput = "InView70"
)

func (e IntegralVideoViewabilityInput) ToPointer() *IntegralVideoViewabilityInput {
	return &e
}
func (e *IntegralVideoViewabilityInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "InView40":
		fallthrough
	case "InView50":
		fallthrough
	case "InView60":
		fallthrough
	case "InView70":
		*e = IntegralVideoViewabilityInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegralVideoViewabilityInput: %v", v)
	}
}
