// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// KeyValuePairOfStringAndStringInput - Type that specifies the key value association of a callback header.
type KeyValuePairOfStringAndStringInput struct {
	Key   *string `json:"key"`
	Value *string `json:"value"`
}

func (o *KeyValuePairOfStringAndStringInput) GetKey() *string {
	if o == nil {
		return nil
	}
	return o.Key
}

func (o *KeyValuePairOfStringAndStringInput) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}
