// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// KeyValuePairOfStringAndStringInput - Type that specifies the key value association of a callback header.
type KeyValuePairOfStringAndStringInput struct {
	Key   *string `json:"key"`
	Value *string `json:"value"`
}

func (k *KeyValuePairOfStringAndStringInput) GetKey() *string {
	if k == nil {
		return nil
	}
	return k.Key
}

func (k *KeyValuePairOfStringAndStringInput) GetValue() *string {
	if k == nil {
		return nil
	}
	return k.Value
}
