// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type LikelyRefreshRate string

const (
	LikelyRefreshRateUnknown        LikelyRefreshRate = "Unknown"
	LikelyRefreshRateUnder15        LikelyRefreshRate = "Under15"
	LikelyRefreshRateBetween15And30 LikelyRefreshRate = "Between15And30"
	LikelyRefreshRateBetween30And60 LikelyRefreshRate = "Between30And60"
	LikelyRefreshRateOver60         LikelyRefreshRate = "Over60"
	LikelyRefreshRateDeprecated     LikelyRefreshRate = "Deprecated"
)

func (e LikelyRefreshRate) ToPointer() *LikelyRefreshRate {
	return &e
}
func (e *LikelyRefreshRate) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Under15":
		fallthrough
	case "Between15And30":
		fallthrough
	case "Between30And60":
		fallthrough
	case "Over60":
		fallthrough
	case "Deprecated":
		*e = LikelyRefreshRate(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LikelyRefreshRate: %v", v)
	}
}
