// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Livestream string

const (
	LivestreamUnknown Livestream = "Unknown"
	LivestreamLive    Livestream = "Live"
	LivestreamNotLive Livestream = "NotLive"
)

func (e Livestream) ToPointer() *Livestream {
	return &e
}
func (e *Livestream) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Live":
		fallthrough
	case "NotLive":
		*e = Livestream(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Livestream: %v", v)
	}
}
