// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type LocationContextTypeInput string

const (
	LocationContextTypeInputRealtime LocationContextTypeInput = "Realtime"
	LocationContextTypeInputHome     LocationContextTypeInput = "Home"
)

func (e LocationContextTypeInput) ToPointer() *LocationContextTypeInput {
	return &e
}
func (e *LocationContextTypeInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Realtime":
		fallthrough
	case "Home":
		*e = LocationContextTypeInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LocationContextTypeInput: %v", v)
	}
}
