// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type MarketTypeBidList string

const (
	MarketTypeBidListUnknown         MarketTypeBidList = "Unknown"
	MarketTypeBidListOpenMarket      MarketTypeBidList = "OpenMarket"
	MarketTypeBidListPmpNotSpecified MarketTypeBidList = "PMPNotSpecified"
	MarketTypeBidListPmpFixed        MarketTypeBidList = "PMPFixed"
	MarketTypeBidListPmpVariable     MarketTypeBidList = "PMPVariable"
	MarketTypeBidListNonPmpFixed     MarketTypeBidList = "NonPMPFixed"
)

func (e MarketTypeBidList) ToPointer() *MarketTypeBidList {
	return &e
}
func (e *MarketTypeBidList) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "OpenMarket":
		fallthrough
	case "PMPNotSpecified":
		fallthrough
	case "PMPFixed":
		fallthrough
	case "PMPVariable":
		fallthrough
	case "NonPMPFixed":
		*e = MarketTypeBidList(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MarketTypeBidList: %v", v)
	}
}
