// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type MarketTypeInput string

const (
	MarketTypeInputOpenMarket        MarketTypeInput = "OpenMarket"
	MarketTypeInputPrivateMarketOnly MarketTypeInput = "PrivateMarketOnly"
	MarketTypeInputMarketplace       MarketTypeInput = "Marketplace"
)

func (e MarketTypeInput) ToPointer() *MarketTypeInput {
	return &e
}
func (e *MarketTypeInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OpenMarket":
		fallthrough
	case "PrivateMarketOnly":
		fallthrough
	case "Marketplace":
		*e = MarketTypeInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MarketTypeInput: %v", v)
	}
}
