// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type MarketType string

const (
	MarketTypeOpenMarket        MarketType = "OpenMarket"
	MarketTypePrivateMarketOnly MarketType = "PrivateMarketOnly"
	MarketTypeMarketplace       MarketType = "Marketplace"
)

func (e MarketType) ToPointer() *MarketType {
	return &e
}
func (e *MarketType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OpenMarket":
		fallthrough
	case "PrivateMarketOnly":
		fallthrough
	case "Marketplace":
		*e = MarketType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MarketType: %v", v)
	}
}
