// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type MultipleMatchResolutionType string

const (
	MultipleMatchResolutionTypeSingleMatchOnly         MultipleMatchResolutionType = "SingleMatchOnly"
	MultipleMatchResolutionTypeApplyMinimumAdjustment  MultipleMatchResolutionType = "ApplyMinimumAdjustment"
	MultipleMatchResolutionTypeApplyAverageAdjustment  MultipleMatchResolutionType = "ApplyAverageAdjustment"
	MultipleMatchResolutionTypeApplyMaximumAdjustment  MultipleMatchResolutionType = "ApplyMaximumAdjustment"
	MultipleMatchResolutionTypeApplyMultiplyAdjustment MultipleMatchResolutionType = "ApplyMultiplyAdjustment"
)

func (e MultipleMatchResolutionType) ToPointer() *MultipleMatchResolutionType {
	return &e
}
func (e *MultipleMatchResolutionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SingleMatchOnly":
		fallthrough
	case "ApplyMinimumAdjustment":
		fallthrough
	case "ApplyAverageAdjustment":
		fallthrough
	case "ApplyMaximumAdjustment":
		fallthrough
	case "ApplyMultiplyAdjustment":
		*e = MultipleMatchResolutionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MultipleMatchResolutionType: %v", v)
	}
}
