// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type NativePlacementType string

const (
	NativePlacementTypeUnknown              NativePlacementType = "Unknown"
	NativePlacementTypeInFeed               NativePlacementType = "InFeed"
	NativePlacementTypeInsideContent        NativePlacementType = "InsideContent"
	NativePlacementTypeOutsideContent       NativePlacementType = "OutsideContent"
	NativePlacementTypeRecommendationWidget NativePlacementType = "RecommendationWidget"
)

func (e NativePlacementType) ToPointer() *NativePlacementType {
	return &e
}
func (e *NativePlacementType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "InFeed":
		fallthrough
	case "InsideContent":
		fallthrough
	case "OutsideContent":
		fallthrough
	case "RecommendationWidget":
		*e = NativePlacementType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NativePlacementType: %v", v)
	}
}
