// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type NativeContextType string

const (
	NativeContextTypeUnclassified        NativeContextType = "Unclassified"
	NativeContextTypeContent             NativeContextType = "Content"
	NativeContextTypeSocial              NativeContextType = "Social"
	NativeContextTypeProduct             NativeContextType = "Product"
	NativeContextTypeContentUnclassified NativeContextType = "ContentUnclassified"
	NativeContextTypeSocialUnclassified  NativeContextType = "SocialUnclassified"
	NativeContextTypeProductUnclassified NativeContextType = "ProductUnclassified"
	NativeContextTypeGeneral             NativeContextType = "General"
	NativeContextTypeArticle             NativeContextType = "Article"
	NativeContextTypeVideo               NativeContextType = "Video"
	NativeContextTypeAudio               NativeContextType = "Audio"
	NativeContextTypeImage               NativeContextType = "Image"
	NativeContextTypeUserGenerated       NativeContextType = "UserGenerated"
	NativeContextTypeGeneralSocial       NativeContextType = "GeneralSocial"
	NativeContextTypeEmail               NativeContextType = "Email"
	NativeContextTypeChatOrIm            NativeContextType = "ChatOrIM"
	NativeContextTypeSellingProducts     NativeContextType = "SellingProducts"
	NativeContextTypeApplicationStore    NativeContextType = "ApplicationStore"
	NativeContextTypeProductReview       NativeContextType = "ProductReview"
)

func (e NativeContextType) ToPointer() *NativeContextType {
	return &e
}
func (e *NativeContextType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unclassified":
		fallthrough
	case "Content":
		fallthrough
	case "Social":
		fallthrough
	case "Product":
		fallthrough
	case "ContentUnclassified":
		fallthrough
	case "SocialUnclassified":
		fallthrough
	case "ProductUnclassified":
		fallthrough
	case "General":
		fallthrough
	case "Article":
		fallthrough
	case "Video":
		fallthrough
	case "Audio":
		fallthrough
	case "Image":
		fallthrough
	case "UserGenerated":
		fallthrough
	case "GeneralSocial":
		fallthrough
	case "Email":
		fallthrough
	case "ChatOrIM":
		fallthrough
	case "SellingProducts":
		fallthrough
	case "ApplicationStore":
		fallthrough
	case "ProductReview":
		*e = NativeContextType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NativeContextType: %v", v)
	}
}
