// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type PassThroughFeeType string

const (
	PassThroughFeeTypeNone                               PassThroughFeeType = "None"
	PassThroughFeeTypeMediaCostPercentage                PassThroughFeeType = "MediaCostPercentage"
	PassThroughFeeTypeDataCostPercentage                 PassThroughFeeType = "DataCostPercentage"
	PassThroughFeeTypeMediaPlusDataCostPercentage        PassThroughFeeType = "MediaPlusDataCostPercentage"
	PassThroughFeeTypePartnerDataCostPercentage          PassThroughFeeType = "PartnerDataCostPercentage"
	PassThroughFeeTypeFeeCpm                             PassThroughFeeType = "FeeCPM"
	PassThroughFeeTypeRateCpm                            PassThroughFeeType = "RateCPM"
	PassThroughFeeTypeRateCpc                            PassThroughFeeType = "RateCPC"
	PassThroughFeeTypeCustomPmpPartnerDataCostPercentage PassThroughFeeType = "CustomPmpPartnerDataCostPercentage"
)

func (e PassThroughFeeType) ToPointer() *PassThroughFeeType {
	return &e
}
func (e *PassThroughFeeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "None":
		fallthrough
	case "MediaCostPercentage":
		fallthrough
	case "DataCostPercentage":
		fallthrough
	case "MediaPlusDataCostPercentage":
		fallthrough
	case "PartnerDataCostPercentage":
		fallthrough
	case "FeeCPM":
		fallthrough
	case "RateCPM":
		fallthrough
	case "RateCPC":
		fallthrough
	case "CustomPmpPartnerDataCostPercentage":
		*e = PassThroughFeeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PassThroughFeeType: %v", v)
	}
}
