// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Peer39ViewabilityInput string

const (
	Peer39ViewabilityInputTop60 Peer39ViewabilityInput = "Top60"
	Peer39ViewabilityInputTop80 Peer39ViewabilityInput = "Top80"
)

func (e Peer39ViewabilityInput) ToPointer() *Peer39ViewabilityInput {
	return &e
}
func (e *Peer39ViewabilityInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Top60":
		fallthrough
	case "Top80":
		*e = Peer39ViewabilityInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Peer39ViewabilityInput: %v", v)
	}
}
