// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ProductListReportingTypeInput string

const (
	ProductListReportingTypeInputFeatured ProductListReportingTypeInput = "Featured"
	ProductListReportingTypeInputHalo     ProductListReportingTypeInput = "Halo"
)

func (e ProductListReportingTypeInput) ToPointer() *ProductListReportingTypeInput {
	return &e
}
func (e *ProductListReportingTypeInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Featured":
		fallthrough
	case "Halo":
		*e = ProductListReportingTypeInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProductListReportingTypeInput: %v", v)
	}
}
