// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ProductionQuality string

const (
	ProductionQualityUnknown              ProductionQuality = "Unknown"
	ProductionQualityProfessional         ProductionQuality = "Professional"
	ProductionQualityProsumer             ProductionQuality = "Prosumer"
	ProductionQualityUserGeneratedContent ProductionQuality = "UserGeneratedContent"
)

func (e ProductionQuality) ToPointer() *ProductionQuality {
	return &e
}
func (e *ProductionQuality) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Professional":
		fallthrough
	case "Prosumer":
		fallthrough
	case "UserGeneratedContent":
		*e = ProductionQuality(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProductionQuality: %v", v)
	}
}
