// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ProductionQualityInput string

const (
	ProductionQualityInputUnknown              ProductionQualityInput = "Unknown"
	ProductionQualityInputProfessional         ProductionQualityInput = "Professional"
	ProductionQualityInputProsumer             ProductionQualityInput = "Prosumer"
	ProductionQualityInputUserGeneratedContent ProductionQualityInput = "UserGeneratedContent"
)

func (e ProductionQualityInput) ToPointer() *ProductionQualityInput {
	return &e
}
func (e *ProductionQualityInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Professional":
		fallthrough
	case "Prosumer":
		fallthrough
	case "UserGeneratedContent":
		*e = ProductionQualityInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProductionQualityInput: %v", v)
	}
}
