// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type RealyticsEntertainmentType string

const (
	RealyticsEntertainmentTypeIptv RealyticsEntertainmentType = "IPTV"
	RealyticsEntertainmentTypeCtv  RealyticsEntertainmentType = "CTV"
	RealyticsEntertainmentTypeTvs  RealyticsEntertainmentType = "TVS"
)

func (e RealyticsEntertainmentType) ToPointer() *RealyticsEntertainmentType {
	return &e
}
func (e *RealyticsEntertainmentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "IPTV":
		fallthrough
	case "CTV":
		fallthrough
	case "TVS":
		*e = RealyticsEntertainmentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RealyticsEntertainmentType: %v", v)
	}
}
