// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RealyticsReachSettingInput struct {
	ID                          *int                           `json:"id,omitempty"`
	Name                        *string                        `json:"name,omitempty"`
	IsActive                    *bool                          `json:"isActive,omitempty"`
	Products                    []IncrementalReachProductInput `json:"products,omitempty"`
	RealyticsEntertainmentInput *RealyticsEntertainmentType    `json:"realyticsEntertainmentInput,omitempty"`
}

func (r *RealyticsReachSettingInput) GetID() *int {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *RealyticsReachSettingInput) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *RealyticsReachSettingInput) GetIsActive() *bool {
	if r == nil {
		return nil
	}
	return r.IsActive
}

func (r *RealyticsReachSettingInput) GetProducts() []IncrementalReachProductInput {
	if r == nil {
		return nil
	}
	return r.Products
}

func (r *RealyticsReachSettingInput) GetRealyticsEntertainmentInput() *RealyticsEntertainmentType {
	if r == nil {
		return nil
	}
	return r.RealyticsEntertainmentInput
}
