// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type RenderingContext string

const (
	RenderingContextOther              RenderingContext = "Other"
	RenderingContextInApp              RenderingContext = "InApp"
	RenderingContextMobileOptimizedWeb RenderingContext = "MobileOptimizedWeb"
)

func (e RenderingContext) ToPointer() *RenderingContext {
	return &e
}
func (e *RenderingContext) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Other":
		fallthrough
	case "InApp":
		fallthrough
	case "MobileOptimizedWeb":
		*e = RenderingContext(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RenderingContext: %v", v)
	}
}
