// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type RestAPIMethodType string

const (
	RestAPIMethodTypePost   RestAPIMethodType = "POST"
	RestAPIMethodTypePut    RestAPIMethodType = "PUT"
	RestAPIMethodTypeGet    RestAPIMethodType = "GET"
	RestAPIMethodTypeDelete RestAPIMethodType = "DELETE"
)

func (e RestAPIMethodType) ToPointer() *RestAPIMethodType {
	return &e
}
func (e *RestAPIMethodType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "POST":
		fallthrough
	case "PUT":
		fallthrough
	case "GET":
		fallthrough
	case "DELETE":
		*e = RestAPIMethodType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RestAPIMethodType: %v", v)
	}
}
