// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type RTBAsiaViewability string

const (
	RTBAsiaViewabilityBlockHighRisk            RTBAsiaViewability = "BlockHighRisk"
	RTBAsiaViewabilityBlockModerateAndHighRisk RTBAsiaViewability = "BlockModerateAndHighRisk"
)

func (e RTBAsiaViewability) ToPointer() *RTBAsiaViewability {
	return &e
}
func (e *RTBAsiaViewability) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "BlockHighRisk":
		fallthrough
	case "BlockModerateAndHighRisk":
		*e = RTBAsiaViewability(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RTBAsiaViewability: %v", v)
	}
}
