// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	TTDAuth *string `security:"scheme,type=apiKey,subtype=header,name=TTD-Auth,env=workflows_ttd_auth"`
}

func (s *Security) GetTTDAuth() *string {
	if s == nil {
		return nil
	}
	return s.TTDAuth
}
