// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StandardJobSubmitResponse struct {
	// The ID of the job.
	ID int64 `json:"id"`
}

func (s *StandardJobSubmitResponse) GetID() int64 {
	if s == nil {
		return 0
	}
	return s.ID
}
