// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/thetradedesk/ttd-workflows-go/internal/utils"
	"time"
)

type StandardJobStatusResponse struct {
	// The ID of the job.
	ID int64 `json:"id"`
	// The UTC data and time that the job completed.
	CompletedAtUtc *time.Time `json:"completedAtUtc,omitempty"`
	// The job completion percentage.
	CompletionPercentage *float64 `json:"completionPercentage,omitempty"`
	// The UTC date and time that the job was created.
	CreatedAtUtc time.Time      `json:"createdAtUtc"`
	Status       WorkflowStatus `json:"status"`
	// The URL from which the job result can be downloaded.
	URL *string `json:"url,omitempty"`
	// The raw job result if the response is less than or equal to 20MB in size.
	// If the job result is larger than 20MB, then null is returned.
	RawResult *string `json:"rawResult,omitempty"`
	// A list of errors encountered during workflow processing.
	Errors *string `json:"errors,omitempty"`
}

func (s StandardJobStatusResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StandardJobStatusResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *StandardJobStatusResponse) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *StandardJobStatusResponse) GetCompletedAtUtc() *time.Time {
	if o == nil {
		return nil
	}
	return o.CompletedAtUtc
}

func (o *StandardJobStatusResponse) GetCompletionPercentage() *float64 {
	if o == nil {
		return nil
	}
	return o.CompletionPercentage
}

func (o *StandardJobStatusResponse) GetCreatedAtUtc() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAtUtc
}

func (o *StandardJobStatusResponse) GetStatus() WorkflowStatus {
	if o == nil {
		return WorkflowStatus("")
	}
	return o.Status
}

func (o *StandardJobStatusResponse) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

func (o *StandardJobStatusResponse) GetRawResult() *string {
	if o == nil {
		return nil
	}
	return o.RawResult
}

func (o *StandardJobStatusResponse) GetErrors() *string {
	if o == nil {
		return nil
	}
	return o.Errors
}
