// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StandardJobSubmitResponse struct {
	// The ID of the job.
	ID int64 `json:"id"`
}

func (o *StandardJobSubmitResponse) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}
