// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/thetradedesk/ttd-workflows-go/internal/utils"
	"time"
)

type StandardJobStatusResponse struct {
	// The ID of the job.
	ID int64 `json:"id"`
	// The UTC data and time that the job completed.
	CompletedAtUtc *time.Time `json:"completedAtUtc,omitempty"`
	// The job completion percentage.
	CompletionPercentage *float64 `json:"completionPercentage,omitempty"`
	// The UTC date and time that the job was created.
	CreatedAtUtc time.Time      `json:"createdAtUtc"`
	Status       WorkflowStatus `json:"status"`
	// The URL from which the job result can be downloaded.
	URL *string `json:"url,omitempty"`
	// The raw job result if the response is less than or equal to 20MB in size.
	// If the job result is larger than 20MB, then null is returned.
	RawResult *string `json:"rawResult,omitempty"`
	// A list of errors encountered during workflow processing.
	Errors *string `json:"errors,omitempty"`
}

func (s StandardJobStatusResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StandardJobStatusResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"id", "createdAtUtc", "status"}); err != nil {
		return err
	}
	return nil
}

func (s *StandardJobStatusResponse) GetID() int64 {
	if s == nil {
		return 0
	}
	return s.ID
}

func (s *StandardJobStatusResponse) GetCompletedAtUtc() *time.Time {
	if s == nil {
		return nil
	}
	return s.CompletedAtUtc
}

func (s *StandardJobStatusResponse) GetCompletionPercentage() *float64 {
	if s == nil {
		return nil
	}
	return s.CompletionPercentage
}

func (s *StandardJobStatusResponse) GetCreatedAtUtc() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAtUtc
}

func (s *StandardJobStatusResponse) GetStatus() WorkflowStatus {
	if s == nil {
		return WorkflowStatus("")
	}
	return s.Status
}

func (s *StandardJobStatusResponse) GetURL() *string {
	if s == nil {
		return nil
	}
	return s.URL
}

func (s *StandardJobStatusResponse) GetRawResult() *string {
	if s == nil {
		return nil
	}
	return s.RawResult
}

func (s *StandardJobStatusResponse) GetErrors() *string {
	if s == nil {
		return nil
	}
	return s.Errors
}
