// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StringWorkflowsOptional struct {
	Value *string `json:"value,omitempty"`
}

func (s *StringWorkflowsOptional) GetValue() *string {
	if s == nil {
		return nil
	}
	return s.Value
}
