// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TargetingEndAge string

const (
	TargetingEndAgeSeventeen     TargetingEndAge = "Seventeen"
	TargetingEndAgeTwenty        TargetingEndAge = "Twenty"
	TargetingEndAgeTwentyFour    TargetingEndAge = "TwentyFour"
	TargetingEndAgeTwentyNine    TargetingEndAge = "TwentyNine"
	TargetingEndAgeThirtyFour    TargetingEndAge = "ThirtyFour"
	TargetingEndAgeThirtyNine    TargetingEndAge = "ThirtyNine"
	TargetingEndAgeFortyFour     TargetingEndAge = "FortyFour"
	TargetingEndAgeFortyNine     TargetingEndAge = "FortyNine"
	TargetingEndAgeFiftyFour     TargetingEndAge = "FiftyFour"
	TargetingEndAgeSixtyFour     TargetingEndAge = "SixtyFour"
	TargetingEndAgeSixtyFourPlus TargetingEndAge = "SixtyFourPlus"
)

func (e TargetingEndAge) ToPointer() *TargetingEndAge {
	return &e
}
func (e *TargetingEndAge) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Seventeen":
		fallthrough
	case "Twenty":
		fallthrough
	case "TwentyFour":
		fallthrough
	case "TwentyNine":
		fallthrough
	case "ThirtyFour":
		fallthrough
	case "ThirtyNine":
		fallthrough
	case "FortyFour":
		fallthrough
	case "FortyNine":
		fallthrough
	case "FiftyFour":
		fallthrough
	case "SixtyFour":
		fallthrough
	case "SixtyFourPlus":
		*e = TargetingEndAge(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TargetingEndAge: %v", v)
	}
}
