// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TargetingGender string

const (
	TargetingGenderMale   TargetingGender = "Male"
	TargetingGenderFemale TargetingGender = "Female"
	TargetingGenderBoth   TargetingGender = "Both"
)

func (e TargetingGender) ToPointer() *TargetingGender {
	return &e
}
func (e *TargetingGender) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Male":
		fallthrough
	case "Female":
		fallthrough
	case "Both":
		*e = TargetingGender(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TargetingGender: %v", v)
	}
}
