// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TargetingStartAgeInput string

const (
	TargetingStartAgeInputTwo        TargetingStartAgeInput = "Two"
	TargetingStartAgeInputThirteen   TargetingStartAgeInput = "Thirteen"
	TargetingStartAgeInputEighteen   TargetingStartAgeInput = "Eighteen"
	TargetingStartAgeInputTwentyOne  TargetingStartAgeInput = "TwentyOne"
	TargetingStartAgeInputTwentyFive TargetingStartAgeInput = "TwentyFive"
	TargetingStartAgeInputThirty     TargetingStartAgeInput = "Thirty"
	TargetingStartAgeInputThirtyFive TargetingStartAgeInput = "ThirtyFive"
	TargetingStartAgeInputForty      TargetingStartAgeInput = "Forty"
	TargetingStartAgeInputFortyFive  TargetingStartAgeInput = "FortyFive"
	TargetingStartAgeInputFifty      TargetingStartAgeInput = "Fifty"
	TargetingStartAgeInputFiftyFive  TargetingStartAgeInput = "FiftyFive"
	TargetingStartAgeInputSixtyFive  TargetingStartAgeInput = "SixtyFive"
)

func (e TargetingStartAgeInput) ToPointer() *TargetingStartAgeInput {
	return &e
}
func (e *TargetingStartAgeInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Two":
		fallthrough
	case "Thirteen":
		fallthrough
	case "Eighteen":
		fallthrough
	case "TwentyOne":
		fallthrough
	case "TwentyFive":
		fallthrough
	case "Thirty":
		fallthrough
	case "ThirtyFive":
		fallthrough
	case "Forty":
		fallthrough
	case "FortyFive":
		fallthrough
	case "Fifty":
		fallthrough
	case "FiftyFive":
		fallthrough
	case "SixtyFive":
		*e = TargetingStartAgeInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TargetingStartAgeInput: %v", v)
	}
}
