// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TargetingGenderInput string

const (
	TargetingGenderInputMale   TargetingGenderInput = "Male"
	TargetingGenderInputFemale TargetingGenderInput = "Female"
	TargetingGenderInputBoth   TargetingGenderInput = "Both"
)

func (e TargetingGenderInput) ToPointer() *TargetingGenderInput {
	return &e
}
func (e *TargetingGenderInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Male":
		fallthrough
	case "Female":
		fallthrough
	case "Both":
		*e = TargetingGenderInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TargetingGenderInput: %v", v)
	}
}
