// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TargetingStartAge string

const (
	TargetingStartAgeTwo        TargetingStartAge = "Two"
	TargetingStartAgeThirteen   TargetingStartAge = "Thirteen"
	TargetingStartAgeEighteen   TargetingStartAge = "Eighteen"
	TargetingStartAgeTwentyOne  TargetingStartAge = "TwentyOne"
	TargetingStartAgeTwentyFive TargetingStartAge = "TwentyFive"
	TargetingStartAgeThirty     TargetingStartAge = "Thirty"
	TargetingStartAgeThirtyFive TargetingStartAge = "ThirtyFive"
	TargetingStartAgeForty      TargetingStartAge = "Forty"
	TargetingStartAgeFortyFive  TargetingStartAge = "FortyFive"
	TargetingStartAgeFifty      TargetingStartAge = "Fifty"
	TargetingStartAgeFiftyFive  TargetingStartAge = "FiftyFive"
	TargetingStartAgeSixtyFive  TargetingStartAge = "SixtyFive"
)

func (e TargetingStartAge) ToPointer() *TargetingStartAge {
	return &e
}
func (e *TargetingStartAge) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Two":
		fallthrough
	case "Thirteen":
		fallthrough
	case "Eighteen":
		fallthrough
	case "TwentyOne":
		fallthrough
	case "TwentyFive":
		fallthrough
	case "Thirty":
		fallthrough
	case "ThirtyFive":
		fallthrough
	case "Forty":
		fallthrough
	case "FortyFive":
		fallthrough
	case "Fifty":
		fallthrough
	case "FiftyFive":
		fallthrough
	case "SixtyFive":
		*e = TargetingStartAge(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TargetingStartAge: %v", v)
	}
}
