// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TargetingEndAgeInput string

const (
	TargetingEndAgeInputSeventeen     TargetingEndAgeInput = "Seventeen"
	TargetingEndAgeInputTwenty        TargetingEndAgeInput = "Twenty"
	TargetingEndAgeInputTwentyFour    TargetingEndAgeInput = "TwentyFour"
	TargetingEndAgeInputTwentyNine    TargetingEndAgeInput = "TwentyNine"
	TargetingEndAgeInputThirtyFour    TargetingEndAgeInput = "ThirtyFour"
	TargetingEndAgeInputThirtyNine    TargetingEndAgeInput = "ThirtyNine"
	TargetingEndAgeInputFortyFour     TargetingEndAgeInput = "FortyFour"
	TargetingEndAgeInputFortyNine     TargetingEndAgeInput = "FortyNine"
	TargetingEndAgeInputFiftyFour     TargetingEndAgeInput = "FiftyFour"
	TargetingEndAgeInputSixtyFour     TargetingEndAgeInput = "SixtyFour"
	TargetingEndAgeInputSixtyFourPlus TargetingEndAgeInput = "SixtyFourPlus"
)

func (e TargetingEndAgeInput) ToPointer() *TargetingEndAgeInput {
	return &e
}
func (e *TargetingEndAgeInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Seventeen":
		fallthrough
	case "Twenty":
		fallthrough
	case "TwentyFour":
		fallthrough
	case "TwentyNine":
		fallthrough
	case "ThirtyFour":
		fallthrough
	case "ThirtyNine":
		fallthrough
	case "FortyFour":
		fallthrough
	case "FortyNine":
		fallthrough
	case "FiftyFour":
		fallthrough
	case "SixtyFour":
		fallthrough
	case "SixtyFourPlus":
		*e = TargetingEndAgeInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TargetingEndAgeInput: %v", v)
	}
}
