// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TencentPageQualityInput string

const (
	TencentPageQualityInputBlockHighRisk            TencentPageQualityInput = "BlockHighRisk"
	TencentPageQualityInputBlockModerateAndHighRisk TencentPageQualityInput = "BlockModerateAndHighRisk"
)

func (e TencentPageQualityInput) ToPointer() *TencentPageQualityInput {
	return &e
}
func (e *TencentPageQualityInput) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "BlockHighRisk":
		fallthrough
	case "BlockModerateAndHighRisk":
		*e = TencentPageQualityInput(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TencentPageQualityInput: %v", v)
	}
}
