// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ThirdPartyDataInput - Required fields for submitting a bulk job for third-party data.
type ThirdPartyDataInput struct {
	// The partner ID to query for.
	PartnerID string `json:"partnerId"`
	//  The shape of the query with the fields being asked for, which is sent downstream.
	//  This determines what the response will look like.
	//
	//  For example, a query shape equal to `"nodes {id name}"` will return the `id` and `name` fields only.
	//
	//  If this is not provided the default query shape will be used:
	//
	//  ```graphql
	//  nodes {
	//      id
	//      name
	//      providerId
	//      providerElementId
	//      description
	//      buyable
	//      fullPath
	//      activeUniques {
	//          householdCount
	//          idsConnectedTvCount
	//          idsInAppCount
	//          idsWebCount
	//          personsCount
	//          thirdPartyDataOverlapCount
	//          lastUpdated
	//      }
	//  }
	// ```
	QueryShape    *string                `json:"queryShape,omitempty"`
	CallbackInput *WorkflowCallbackInput `json:"callbackInput,omitempty"`
}

func (o *ThirdPartyDataInput) GetPartnerID() string {
	if o == nil {
		return ""
	}
	return o.PartnerID
}

func (o *ThirdPartyDataInput) GetQueryShape() *string {
	if o == nil {
		return nil
	}
	return o.QueryShape
}

func (o *ThirdPartyDataInput) GetCallbackInput() *WorkflowCallbackInput {
	if o == nil {
		return nil
	}
	return o.CallbackInput
}
