// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type VideoPlayerSize string

const (
	VideoPlayerSizeUnused   VideoPlayerSize = "UNUSED"
	VideoPlayerSizeUnknown  VideoPlayerSize = "Unknown"
	VideoPlayerSizeSmall    VideoPlayerSize = "Small"
	VideoPlayerSizeMedium   VideoPlayerSize = "Medium"
	VideoPlayerSizeLarge    VideoPlayerSize = "Large"
	VideoPlayerSizeInBanner VideoPlayerSize = "InBanner"
)

func (e VideoPlayerSize) ToPointer() *VideoPlayerSize {
	return &e
}
func (e *VideoPlayerSize) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNUSED":
		fallthrough
	case "Unknown":
		fallthrough
	case "Small":
		fallthrough
	case "Medium":
		fallthrough
	case "Large":
		fallthrough
	case "InBanner":
		*e = VideoPlayerSize(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VideoPlayerSize: %v", v)
	}
}
