// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type VideoPlaybackType string

const (
	VideoPlaybackTypeNone                       VideoPlaybackType = "None"
	VideoPlaybackTypePreRoll                    VideoPlaybackType = "PreRoll"
	VideoPlaybackTypeMidRoll                    VideoPlaybackType = "MidRoll"
	VideoPlaybackTypePostRoll                   VideoPlaybackType = "PostRoll"
	VideoPlaybackTypeUndeclared                 VideoPlaybackType = "Undeclared"
	VideoPlaybackTypeInterstitialSliderFloating VideoPlaybackType = "InterstitialSliderFloating"
	VideoPlaybackTypeAccompanyingContent        VideoPlaybackType = "AccompanyingContent"
	VideoPlaybackTypeStandalone                 VideoPlaybackType = "Standalone"
)

func (e VideoPlaybackType) ToPointer() *VideoPlaybackType {
	return &e
}
func (e *VideoPlaybackType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "None":
		fallthrough
	case "PreRoll":
		fallthrough
	case "MidRoll":
		fallthrough
	case "PostRoll":
		fallthrough
	case "Undeclared":
		fallthrough
	case "InterstitialSliderFloating":
		fallthrough
	case "AccompanyingContent":
		fallthrough
	case "Standalone":
		*e = VideoPlaybackType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VideoPlaybackType: %v", v)
	}
}
