// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type VideoMutedState string

const (
	VideoMutedStateInfrequentlyAutoMuted VideoMutedState = "InfrequentlyAutoMuted"
	VideoMutedStateSometimesAutoMuted    VideoMutedState = "SometimesAutoMuted"
	VideoMutedStateAlwaysAutoMuted       VideoMutedState = "AlwaysAutoMuted"
)

func (e VideoMutedState) ToPointer() *VideoMutedState {
	return &e
}
func (e *VideoMutedState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "InfrequentlyAutoMuted":
		fallthrough
	case "SometimesAutoMuted":
		fallthrough
	case "AlwaysAutoMuted":
		*e = VideoMutedState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VideoMutedState: %v", v)
	}
}
