// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type VideoSkippability string

const (
	VideoSkippabilityUnknown      VideoSkippability = "Unknown"
	VideoSkippabilitySkippable    VideoSkippability = "Skippable"
	VideoSkippabilityNotSkippable VideoSkippability = "NotSkippable"
)

func (e VideoSkippability) ToPointer() *VideoSkippability {
	return &e
}
func (e *VideoSkippability) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Skippable":
		fallthrough
	case "NotSkippable":
		*e = VideoSkippability(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VideoSkippability: %v", v)
	}
}
