// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type VideoQuality string

const (
	VideoQualityUnknown       VideoQuality = "Unknown"
	VideoQualityProfessional  VideoQuality = "Professional"
	VideoQualityProsumer      VideoQuality = "Prosumer"
	VideoQualityUserGenerated VideoQuality = "UserGenerated"
	VideoQualityMixed         VideoQuality = "Mixed"
)

func (e VideoQuality) ToPointer() *VideoQuality {
	return &e
}
func (e *VideoQuality) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Unknown":
		fallthrough
	case "Professional":
		fallthrough
	case "Prosumer":
		fallthrough
	case "UserGenerated":
		fallthrough
	case "Mixed":
		*e = VideoQuality(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VideoQuality: %v", v)
	}
}
