// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type VolumeControlPriority string

const (
	VolumeControlPriorityNeutral       VolumeControlPriority = "Neutral"
	VolumeControlPriorityOne           VolumeControlPriority = "One"
	VolumeControlPriorityTwo           VolumeControlPriority = "Two"
	VolumeControlPriorityFrequencyGoal VolumeControlPriority = "FrequencyGoal"
	VolumeControlPriorityNegative      VolumeControlPriority = "Negative"
)

func (e VolumeControlPriority) ToPointer() *VolumeControlPriority {
	return &e
}
func (e *VolumeControlPriority) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Neutral":
		fallthrough
	case "One":
		fallthrough
	case "Two":
		fallthrough
	case "FrequencyGoal":
		fallthrough
	case "Negative":
		*e = VolumeControlPriority(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VolumeControlPriority: %v", v)
	}
}
