// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type WeatherCondition string

const (
	WeatherConditionThunderstorm WeatherCondition = "Thunderstorm"
	WeatherConditionDrizzle      WeatherCondition = "Drizzle"
	WeatherConditionRain         WeatherCondition = "Rain"
	WeatherConditionSnow         WeatherCondition = "Snow"
	WeatherConditionMist         WeatherCondition = "Mist"
	WeatherConditionSmoke        WeatherCondition = "Smoke"
	WeatherConditionHaze         WeatherCondition = "Haze"
	WeatherConditionDust         WeatherCondition = "Dust"
	WeatherConditionFog          WeatherCondition = "Fog"
	WeatherConditionSand         WeatherCondition = "Sand"
	WeatherConditionAsh          WeatherCondition = "Ash"
	WeatherConditionSquall       WeatherCondition = "Squall"
	WeatherConditionTornado      WeatherCondition = "Tornado"
	WeatherConditionClear        WeatherCondition = "Clear"
	WeatherConditionClouds       WeatherCondition = "Clouds"
	WeatherConditionWind         WeatherCondition = "Wind"
)

func (e WeatherCondition) ToPointer() *WeatherCondition {
	return &e
}
func (e *WeatherCondition) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Thunderstorm":
		fallthrough
	case "Drizzle":
		fallthrough
	case "Rain":
		fallthrough
	case "Snow":
		fallthrough
	case "Mist":
		fallthrough
	case "Smoke":
		fallthrough
	case "Haze":
		fallthrough
	case "Dust":
		fallthrough
	case "Fog":
		fallthrough
	case "Sand":
		fallthrough
	case "Ash":
		fallthrough
	case "Squall":
		fallthrough
	case "Tornado":
		fallthrough
	case "Clear":
		fallthrough
	case "Clouds":
		fallthrough
	case "Wind":
		*e = WeatherCondition(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WeatherCondition: %v", v)
	}
}
