// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WorkflowCallbackInput struct {
	CallbackURL     string            `json:"callbackUrl"`
	CallbackHeaders map[string]string `json:"callbackHeaders,omitempty"`
}

func (o *WorkflowCallbackInput) GetCallbackURL() string {
	if o == nil {
		return ""
	}
	return o.CallbackURL
}

func (o *WorkflowCallbackInput) GetCallbackHeaders() map[string]string {
	if o == nil {
		return nil
	}
	return o.CallbackHeaders
}
