// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WorkflowCallbackInput struct {
	CallbackURL     string            `json:"callbackUrl"`
	CallbackHeaders map[string]string `json:"callbackHeaders,omitempty"`
}

func (w *WorkflowCallbackInput) GetCallbackURL() string {
	if w == nil {
		return ""
	}
	return w.CallbackURL
}

func (w *WorkflowCallbackInput) GetCallbackHeaders() map[string]string {
	if w == nil {
		return nil
	}
	return w.CallbackHeaders
}
