// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"ttd-workflows/models/components"
)

type ProblemDetailsError struct {
	Type                 *string                              `json:"type,omitempty"`
	Title                *string                              `json:"title,omitempty"`
	Status               *int                                 `json:"status,omitempty"`
	Detail               *string                              `json:"detail,omitempty"`
	Instance             *string                              `json:"instance,omitempty"`
	AdditionalProperties map[string]components.ProblemDetails `additionalProperties:"true" json:"-"`
	HTTPMeta             components.HTTPMetadata              `json:"-"`
}

var _ error = &ProblemDetailsError{}

func (e *ProblemDetailsError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
